adding management command to restore es from snapshot
dimagi/commcare-hq pull request #13154
Opened 2016-09-08 18:01 UTC by calellowitz

@esoergel @benrudolph @czue @snopoke 
This management command can be used to restore elasticsearch from a snapshot. It wasnt clear to me whether it belonged in ansible or the hq repo (since we dont really manage scripts like this in ansible but the rest of the work is there). Happy to move to the ansible repo (maybe its own role like rolling restart?) if that seems cleaner.
Ansible work at https://github.com/dimagi/commcarehq-ansible/pull/524

2016-09-08 18:01 UTC, dimagimon commented on corehq/apps/es/management/commands/restore_es_snapshot.py
> +class Command(BaseCommand):
E302 expected 2 blank lines, found 1

2016-09-08 18:01 UTC, dimagimon commented on corehq/apps/es/management/commands/restore_es_snapshot.py
> +
W293 blank line contains whitespace

2016-09-09 07:59 UTC, snopoke commented
Seems OK to have this live here. It is possible to restore only a single index or do we always have to restore all of them?

2016-09-09 13:27 UTC, calellowitz commented
The api supports restoring a single index. I can add an optional argument to restore only a specific index or indices.

2016-09-09 15:41 UTC, dimagimon commented on corehq/apps/es/management/commands/restore_es_snapshot.py
> +        )
E124 closing bracket does not match visual indentation

2016-09-09 15:43 UTC, calellowitz commented
@snopoke 
Added option to restore specific indices

2016-09-09 19:48 UTC, esoergel commented on corehq/apps/es/management/commands/restore_es_snapshot.py
> +        return indices
Does this require the full index name, or are aliases acceptable?

2016-09-09 19:49 UTC, esoergel commented on corehq/apps/es/management/commands/restore_es_snapshot.py
> +        self.restore_snapshot(es, date, indices)
Might want to verify that the snapshots exist before deleting the old indices

2016-09-09 19:52 UTC, esoergel commented
Looks good overall, but I'd add in some more sanity checks, things like:
> This will remove the following indices: ...
Restoring from backup made on <date>
Found snapshot <>
Are you sure you'd like to continue?

2016-09-13 15:52 UTC, calellowitz commented on corehq/apps/es/management/commands/restore_es_snapshot.py
> +        return indices
aliases work

2016-10-04 17:38 UTC, dimagimon commented on corehq/apps/es/management/commands/restore_es_snapshot.py
> +class Command(BaseCommand):
E302 expected 2 blank lines, found 1

2016-10-04 18:27 UTC, calellowitz commented
This should finally be good now. I realized we had to push back pillow checkpoints a bit ago and was trying to figure out how to do that.
After a discussion with @snopoke I decided to just do daily pillow checkpoint snapshots (based on cron job scheduling these should be a few hours before the es index snapshot occurs). I keep these for 3 days, which is the same length of time as the es snapshots.

2016-10-04 18:28 UTC, calellowitz commented
cc: @esoergel as well

2016-10-05 15:47 UTC, dimagimon commented on corehq/apps/es/management/commands/restore_es_snapshot.py
> +        )
E124 closing bracket does not match visual indentation

2016-10-05 16:16 UTC, calellowitz commented
added the hold off on merge tag so i can do some further testing

2016-10-05 19:39 UTC, czue commented on corehq/apps/hqadmin/tasks.py
> +    ESRestorePillowCheckpoints.objects.filter(date_updated__lt=three_days_ago).delete()
wonder if we want to make this a bit longer? it seems very low-cost to save, e.g. a month and sometimes we get into a situation with a cloudant rewind where we need something older than 3 days....

2016-10-07 16:13 UTC, calellowitz commented on corehq/apps/hqadmin/tasks.py
> +    ESRestorePillowCheckpoints.objects.filter(date_updated__lt=three_days_ago).delete()
upped to 30 days. the 3 days was because thats how long we kept the snapshots but it seems like there is no downside to keeping more

2016-10-07 16:16 UTC, calellowitz commented
This is fully tested on staging so i removed the hold off on merge tag
@snopoke @czue 
The one major change to functionality i have made since then is that now all pillows are reset to the old checkpoints, not just those corresponding to restored indices since it does not seem like there is a good way to find all pillows that interact with each index. Im guessing they can catch up pretty quickly so it should not be a huge problem but I have not been able to test it on prod pillows

2016-10-10 07:46 UTC, snopoke requested changes
Generally looks good.

2016-10-10 07:46 UTC, snopoke commented on corehq/apps/es/management/commands/restore_es_snapshot.py
> +        client = self.get_client_and_close_indices(es, indices)
Should add in a user confirmation here before going ahead, especially since the default is to close ALL indices.

2016-10-10 07:46 UTC, snopoke commented on corehq/apps/es/management/commands/restore_es_snapshot.py
> +            pillow.checkpoint.update_to(seq)
I think this requires a pillow restart - would probably be good to tell the user that they need to stop all pillows prior to doing a restore and start them again afterwards.

2016-10-10 07:46 UTC, snopoke commented on corehq/apps/hqadmin/migrations/0007_esrestorepillowcheckpoint_datefield.py
> +        ),
Can combine this with the previous migration (each separate migration has a significant overhead)

2016-10-10 07:46 UTC, snopoke commented on corehq/apps/hqadmin/models.py
> +    def get_pillow_snapshots(cls):
Since this doesn't return anything I'd rename to `create_pillow_checkpoing_snapshots` or event `snapshot_pillow_checkpoints`

2016-10-10 14:04 UTC, calellowitz commented on corehq/apps/hqadmin/migrations/0007_esrestorepillowcheckpoint_datefield.py
> +        ),
If this is already on staging is there a safe way to make it one migration without breaking staging deploys?

2016-10-10 14:09 UTC, snopoke commented
hmm, no. In that case fine to leave as is

2016-10-10 14:18 UTC, calellowitz commented
@snopoke updated

2016-10-10 14:26 UTC, snopoke commented on corehq/apps/hqadmin/models.py
> +    def create_pillow_checkpoint_snaphots(cls):
nit: typo `snaphots`

2016-10-10 14:27 UTC, snopoke approved these changes

2016-10-10 14:28 UTC, calellowitz commented on corehq/apps/hqadmin/models.py
> +    def create_pillow_checkpoint_snaphots(cls):
fixed

2016-10-10 18:24 UTC, calellowitz commented
✅

2016-10-11 08:10 UTC, merged