Testing out Github's new PR review stuff
dimagi/commcare-hq pull request #13229
Opened 2016-09-14 18:24 UTC by esoergel

2016-09-14 18:25 UTC, esoergel commented on README.md
> +Here is a tipo.
*typo

2016-09-14 18:25 UTC, esoergel commented on docs/index.rst
> +  comment comment comment
This comment is useless

2016-09-14 18:25 UTC, esoergel commented on docs/index.rst
> +  comment comment comment
What does this new conversation look like?

2016-09-14 18:26 UTC, esoergel reviewed
Overall looks good!

2016-09-14 18:30 UTC, millerdev commented on docs/index.rst
> +  comment comment comment
threaded comments?

2016-09-14 18:30 UTC, benrudolph commented on docs/index.rst
> +  comment comment comment
it didn't give me the option to start a review 😢

2016-09-14 18:30 UTC, benrudolph commented on docs/index.rst
> +  comment comment comment
now i see how to do it

2016-09-14 18:31 UTC, benrudolph requested changes
Dog you gotta change that before merging

2016-09-14 18:31 UTC, millerdev requested changes
the code won't work unless these typos are fixed.

2016-09-14 18:34 UTC, millerdev approved these changes

2016-09-14 18:47 UTC, esoergel commented
Weird, I can't reply to @millerdev 's comment "threaded comments?".  I wonder if that's because I'm the PR author.  I also dont' have the option to request changes on my own PR.

2016-09-15 04:03 UTC, czue commented on docs/index.rst
> +   commtrack
:skull:

2016-09-15 04:04 UTC, czue commented on README.md
> +Here is a tipo.
should address

2016-09-15 04:05 UTC, czue requested changes
still some outstanding problems

2016-09-15 04:05 UTC, czue commented
neat

2016-10-03 20:09 UTC, closed without merging