Revert "Revert "Mk 235887 configure menu grid""
dimagi/commcare-hq pull request #13232
Opened 2016-09-14 19:24 UTC by mkangia

Reverts dimagi/commcare-hq#13231

2016-09-14 20:27 UTC, mkangia commented
@orangejenny @czue 
Sorry for the confusion here guys. Just checked that if we don't [Retain old values](https://github.com/dimagi/commcare-hq/pull/13232/commits/445ab3b874b3b45845c0243f1699b48a692d5316) it works as expected.
But the question is that [here](https://github.com/dimagi/commcare-hq/pull/13232/files#diff-a0cd4db8a4357e7a1f662e159786c735L350) we have changed the values for the fields and made it a part of the feature flag (along with [this](https://github.com/dimagi/commcare-hq/pull/13232/files#diff-30960a86c22284ec0bd8040403d4bce5L152)) . How does this effect existing applications? Is it ok to change the values without any data migration?

2016-09-14 20:34 UTC, orangejenny commented
I think there needs to be some kind of migration, or else support both the old and new values. The latter is probably easier, it might just be a matter of having `grid_display_for_all_modules` accept either "all" or "yes".

2016-09-17 11:22 UTC, dimagimon commented on corehq/apps/app_manager/tests/test_grid_menus.py
> +    if enable_users is None: enable_users = []
E701 multiple statements on one line (colon)

2016-09-17 11:22 UTC, dimagimon commented on corehq/apps/app_manager/tests/test_grid_menus.py
> +
W391 blank line at end of file

2016-09-19 20:21 UTC, mkangia commented
@orangejenny @czue @amsagoff 
Finally got this working!!!! Had to abort the plan for using the existing fields only.
So overall the change is that we have added one more config "Forms Menu Display" for form views and setup at module setting page along with minor textual changes in existing configs.
This is deployed on staging now.

Please help with review and any text changes if needed.
<img width="623" alt="screen shot 2016-09-20 at 1 50 01 am" src="https://cloud.githubusercontent.com/assets/3864163/18647647/95ac378c-7ed4-11e6-83c5-02693a8882b2.png">

Have added "Set Grid Menus as No for this to be active" since Grid Menus takes priority over these two. Can remove this text if its not needed or can change it to something better?

2016-09-20 04:50 UTC, czue commented
congrats! I'm going to let @orangejenny and @amsagoff lead feedback

On Tuesday, September 20, 2016, Manish Kangia <notifications@github.com>
wrote:

> @orangejenny <https://github.com/orangejenny> @czue
> <https://github.com/czue> @amsagoff <https://github.com/amsagoff>
> Finally got this working!!!! Had to abort the plan for using the existing
> fields only.
> So overall the change is that we have added one more config "Forms Menu
> Display" for form views and setup at module setting page along with minor
> textual changes in existing configs.
> This is deployed on staging now.
>
> Please help with review and any text changes if needed.
> [image: screen shot 2016-09-20 at 1 50 01 am]
> <https://cloud.githubusercontent.com/assets/3864163/18647647/95ac378c-7ed4-11e6-83c5-02693a8882b2.png>
>
> Have added "Set Grid Menus as No for this to be active" since Grid Menus
> takes priority over these two. Can remove this text if its not needed or
> can change it to something better?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/dimagi/commcare-hq/pull/13232#issuecomment-248113574>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAED-_Ohbzqi6ge_w1I7-GwDEoSuhLESks5qru7LgaJpZM4J9JSu>
> .
>

2016-09-20 21:00 UTC, orangejenny commented on corehq/apps/app_manager/models.py
> +    def grid_menu_toggle_enabled(self):
The more standard way to check a toggle is `toggles.GRID_MENUS.enabled(self.domain)`

2016-09-20 21:09 UTC, orangejenny commented on corehq/apps/app_manager/static/app_manager/json/commcare-app-settings.yaml
> +  foot_note: "Set Grid Menus as No for this to be active"
I don't think the text you're displaying as a footnote is really different than help text. I'd just add those explanations to `description` and remove the footnote logic altogether.

2016-09-20 21:39 UTC, orangejenny commented on corehq/apps/app_manager/static/app_manager/json/commcare-app-settings.yaml
> +  foot_note: "Set Grid Menus as No for this to be active"
On second thought, for the `Set Grid Menus as No for this to be active` text specifically, you can remove it and instead use the `requires` property. If you look under "Java Phone General Settings" you'll see that "Auto-Sync Frequency" and "Unsynced Time Limit" are disabled if "Sync Mode" is set to "Push Only." This leads to a display like this:
<img width="691" alt="screen shot 2016-09-20 at 5 33 37 pm" src="https://cloud.githubusercontent.com/assets/1486591/18689788/f530fa06-7f58-11e6-826d-387619926a5b.png">

The `For per-module option...` text for the setting below is still needed, but can be moved into that setting's description.

2016-09-20 21:40 UTC, orangejenny requested changes
Generally looks good, see inline comments for changes.

2016-09-20 21:42 UTC, orangejenny commented
I'm not sure it's a necessary to keep the `Grid Menus` toggle as a gateway for the other two, but defer to @amsagoff

2016-09-20 21:43 UTC, amsagoff commented
also think good to remove

On Tue, Sep 20, 2016 at 5:42 PM, Jenny Schweers <notifications@github.com>
wrote:

> I'm not sure it's a necessary to keep the Grid Menus toggle as a gateway
> for the other two, but defer to @amsagoff <https://github.com/amsagoff>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/dimagi/commcare-hq/pull/13232#issuecomment-248443664>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAazfJNnoEfKorWT-jFFHWBQ0oGCrTjmks5qsFNGgaJpZM4J9JSu>
> .
>

2016-09-20 21:58 UTC, orangejenny commented
Hey Manish, sorry that some of the comments on this are conflicting a bit. To summarize my and Amelia's comments:
- Remove "Grid Menus" setting
- Update toggle logic
- Move "For per-module option..." text into the description and remove the foot_note logic.

2016-09-21 07:11 UTC, mkangia commented on corehq/apps/app_manager/models.py
> +    def grid_menu_toggle_enabled(self):
Awesome!

2016-09-21 07:19 UTC, mkangia commented on corehq/apps/app_manager/static/app_manager/json/commcare-app-settings.yaml
> +  foot_note: "Set Grid Menus as No for this to be active"
`requires` .. nice hook!

2016-09-21 07:22 UTC, mkangia commented on corehq/apps/app_manager/models.py
> +    def grid_menu_toggle_enabled(self):
Nice! Would update this.

2016-09-21 08:58 UTC, mkangia commented
@orangejenny Thanks Jenny..
Have made the code changes.
Though, curious how the existing applications would be effected by removing Grid Menus setting.

2016-09-21 09:57 UTC, proteusvacuum commented on corehq/apps/app_manager/tests/test_grid_menus.py
> +def mock_toggle(slug, enable_users=None):
@mkangia : I don't think you need this function any more.

2016-09-21 09:58 UTC, mkangia commented on corehq/apps/app_manager/tests/test_grid_menus.py
> +def mock_toggle(slug, enable_users=None):
Yup! You are right.

2016-09-22 06:17 UTC, orangejenny commented on corehq/ex-submodules/toggle/models.py
> +    @memoized
This function isn't used anymore

2016-09-22 06:17 UTC, orangejenny requested changes

2016-09-22 06:22 UTC, orangejenny commented
> Though, curious how the existing applications would be effected by removing Grid Menus setting.

Yeah, this is a good point. The most forgiving thing to do would be a lazy migration: keep reading the old setting, and using that value to set the new settings. Isn't having the old setting on equivalent to having both of the new settings set to "Grid"? What do you think of implementing that?

2016-09-22 07:11 UTC, dimagimon commented on corehq/ex-submodules/toggle/models.py
> +from dimagi.utils.decorators.memoized import memoized
F401 'memoized' imported but unused

2016-09-22 07:11 UTC, mkangia commented on corehq/ex-submodules/toggle/models.py
> +    @memoized
Removed!

2016-09-22 07:20 UTC, mkangia commented
@orangejenny i am not very sure about this but i guess the old builds of applications should keep working since they would have setup files retained from the time when the builds were created. Isn't it?

> Isn't having the old setting on equivalent to having both of the new settings set to "Grid"
Yup!

Lazy Migration. i won't prefer doing that. Adds code that we would not be sure about removing ever. Moreover the migrated fields are feature flags, we would need to add feature flag to all these domains as well. Defeats the point of Feature Flags i guess.

The reason i retained the existing config was to avoid surprises for users. If we are announcing the changes and users know then it should be cool.
Thats what i think from my limited context.

2016-09-22 23:03 UTC, orangejenny commented
Ohhh, I forgot this is all feature flagged. Yeah, don't worry about a migration. Good to merge!

>  If we are announcing the changes and users know then it should be cool.

You likely already know this, but this is only true for flagged features. In general we can't rely on users paying attention to announcements.

2016-09-22 23:03 UTC, orangejenny approved these changes

2016-09-22 23:03 UTC, orangejenny commented
Just realized this still has the "hold off on merge" tag, so I'm holding off, but this is good to go from my perspective.

2016-09-23 07:35 UTC, mkangia commented
@orangejenny 
> If we are announcing the changes and users know then it should be cool.
i was referring to removing the 'Grid Menus' option which is available by default. That would go missing now since we are removing it.

Wanted to be sure about removing the field/migration stuff and also do a final test on mobile once .. the tests are passing thought.. so the 'hold off on merge'.

2016-09-26 06:17 UTC, mkangia commented
@orangejenny just removed some unneeded changes done earlier. Tested as well!

2016-09-26 07:13 UTC, merged

2016-09-26 14:52 UTC, orangejenny commented
hurrah, it's merged!