Sr cicons
dimagi/commcare-hq pull request #13331
Opened 2016-09-22 15:18 UTC by sravfeyn

http://manage.dimagi.com/default.asp?233227#edit_0_233227 @nickpell

2016-09-22 22:32 UTC, orangejenny commented on corehq/apps/hqwebapp/static/hqwebapp/js/key-value-mapping.js
> +                placeholder: 'Calculation',
translations please (`gettext`)

2016-09-22 22:33 UTC, orangejenny requested changes

2016-09-23 13:46 UTC, sravfeyn commented on corehq/apps/hqwebapp/static/hqwebapp/js/key-value-mapping.js
> +                placeholder: 'Calculation',
Oh yeah, I was gonna add it. Thanks!

2016-09-23 15:42 UTC, dimagimon commented
There are 6 errors:

* corehq/apps/hqwebapp/static/hqwebapp/js/key-value-mapping.js, line 104 - 'django' is not defined. (no-undef)
* corehq/apps/hqwebapp/static/hqwebapp/js/key-value-mapping.js, line 105 - 'django' is not defined. (no-undef)
* corehq/apps/hqwebapp/static/hqwebapp/js/key-value-mapping.js, line 106 - 'django' is not defined. (no-undef)
* corehq/apps/hqwebapp/static/hqwebapp/js/key-value-mapping.js, line 111 - 'django' is not defined. (no-undef)
* corehq/apps/hqwebapp/static/hqwebapp/js/key-value-mapping.js, line 112 - 'django' is not defined. (no-undef)
* corehq/apps/hqwebapp/static/hqwebapp/js/key-value-mapping.js, line 113 - 'django' is not defined. (no-undef)

2016-09-23 16:08 UTC, orangejenny approved these changes

2016-09-23 16:09 UTC, orangejenny commented
Looks good, just holding off on merge because of label.

2016-09-23 18:32 UTC, sravfeyn commented
@orangejenny I've removed the label, jenny.

2016-09-23 21:39 UTC, merged