custom expresion for jhpiego-test domain
dimagi/commcare-hq pull request #13371
Opened 2016-09-27 06:56 UTC by lwyszomi

@NoahCarnahan

2016-09-27 15:47 UTC, NoahCarnahan requested changes
Left a few comments, otherwise looking good.

2016-09-27 15:47 UTC, NoahCarnahan commented on custom/eqa/expressions.py
> +        incorrect_question = latest_form.get_date(path % (self.section, 'incorrect_questions'))
Looks like this line should also be inside the `if latest_form:` block

2016-09-27 15:47 UTC, NoahCarnahan commented on custom/eqa/expressions.py
> +        incorrect_question = latest_form.get_date(path % (self.section, 'incorrect_questions'))
I think you want `get_data()` not `get_date()`?

2016-09-27 15:47 UTC, NoahCarnahan commented on custom/eqa/expressions.py
> +                    latest_form.get_date(path % (self.section, 'copy-1-of-responsible')).split(',')
Same `get_data()`/`get_date()` issue

2016-09-27 15:47 UTC, NoahCarnahan commented on custom/eqa/expressions.py
> +                'gap': latest_form.get_data('code_to_text/%s' % incorrect_question),
We actually want a slightly different value here. `code_to_text/<incorrect_question>` is a label node, and we want the label of that label from the `corehq.apps.app_manager.xform.XForm` model. As you currently have it here, I believe `gap` will always be the XFormInstance value of the label node, which will always be "OK", or something like that. You can get the value like this:
```python
question_list = Application.get(latest_form.app_id).get_questions()
questions = {x['value']: x for x in question_list}
gap = questions['code_to_text/%s' % incorrect_question].label
```
(this snippet of code is untested)

2016-09-28 07:45 UTC, lwyszomi commented
@NoahCarnahan updated

2016-09-28 14:26 UTC, NoahCarnahan approved these changes

2016-09-28 14:27 UTC, NoahCarnahan commented
Looks good thanks!

2016-09-28 14:27 UTC, merged