One Question Per Screen in Preview
dimagi/commcare-hq pull request #13441
Opened 2016-10-04 04:51 UTC by biyeun

@benrudolph 

cc @dimagi/product 

still need to work out some kinks with a few question types on the backend

![preview-oqps-pt1](https://cloud.githubusercontent.com/assets/716573/19062984/b078aaac-89cc-11e6-9689-53dcb96cf69f.gif)
![preview-oqps-pt2](https://cloud.githubusercontent.com/assets/716573/19062985/b079a3a8-89cc-11e6-85c6-410541c2b306.gif)

2016-10-04 04:52 UTC, dimagimon commented
There are 27 errors:

* corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js, line 95 - Missing trailing comma. (comma-dangle)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js, line 96 - Missing trailing comma. (comma-dangle)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js, line 103 - 'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js, line 106 - Missing trailing comma. (comma-dangle)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js, line 107 - Missing trailing comma. (comma-dangle)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js, line 110 - 'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js, line 378 - 'django' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js, line 386 - 'moment' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js, line 539 - Expected indentation of 8 space characters but found 12. (indent)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js, line 542 - Expected indentation of 8 space characters but found 12. (indent)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js, line 545 - Expected indentation of 8 space characters but found 12. (indent)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 270 - 'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 271 - 'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 272 - 'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 289 - 'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 292 - 'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 295 - 'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 310 - Missing trailing comma. (comma-dangle)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 342 - Expected indentation of 8 space characters but found 12. (indent)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 343 - Expected indentation of 8 space characters but found 12. (indent)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 355 - Expected indentation of 8 space characters but found 12. (indent)
'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 356 - Expected indentation of 4 space characters but found 8. (indent)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 366 - Expected indentation of 8 space characters but found 12. (indent)
'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 367 - Expected indentation of 4 space characters but found 8. (indent)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 377 - Expected indentation of 8 space characters but found 12. (indent)
'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 378 - Expected indentation of 8 space characters but found 12. (indent)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 379 - Expected indentation of 4 space characters but found 8. (indent)

2016-10-04 17:59 UTC, dimagimon commented
There are 24 errors:

* corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js, line 95 - Missing trailing comma. (comma-dangle)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js, line 96 - Missing trailing comma. (comma-dangle)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js, line 103 - 'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js, line 106 - Missing trailing comma. (comma-dangle)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js, line 107 - Missing trailing comma. (comma-dangle)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js, line 110 - 'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js, line 539 - Expected indentation of 8 space characters but found 12. (indent)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js, line 542 - Expected indentation of 8 space characters but found 12. (indent)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js, line 545 - Expected indentation of 8 space characters but found 12. (indent)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 270 - 'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 271 - 'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 272 - 'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 289 - 'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 292 - 'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 295 - 'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 342 - Expected indentation of 8 space characters but found 12. (indent)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 343 - Expected indentation of 8 space characters but found 12. (indent)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 355 - Expected indentation of 8 space characters but found 12. (indent)
'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 356 - Expected indentation of 4 space characters but found 8. (indent)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 366 - Expected indentation of 8 space characters but found 12. (indent)
'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 367 - Expected indentation of 4 space characters but found 8. (indent)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 377 - Expected indentation of 8 space characters but found 12. (indent)
'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 378 - Expected indentation of 8 space characters but found 12. (indent)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 379 - Expected indentation of 4 space characters but found 8. (indent)

2016-10-05 19:09 UTC, benrudolph requested changes

2016-10-05 19:09 UTC, benrudolph commented on corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js
> +                    method: "notifyWhenChangesStop"
cool

2016-10-05 19:09 UTC, benrudolph commented on corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js
> +            self.rawAnswer = ko.observable(Formplayer.Const.NO_ANSWER).extend({
i think this whole thing can be condensed if we do:
```
 self.rawAnswer = ko.observable(self.answer() || Formplayer.Const.NO_ANSWER).extend(...
```
i know it wasn't you originally, but now it's a significant amount of code copying

2016-10-05 19:09 UTC, benrudolph commented on corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js
> +                    method: "notifyWhenChangesStop"
why not always have this enabled?

2016-10-05 19:09 UTC, benrudolph commented on corehq/apps/cloudcare/static/cloudcare/js/form_entry/fullform-ui.js
> +            && self.children()[0].isValid()
should this not be `_.all(self.children(), function(child) { return child.isValid() })`

2016-10-05 19:09 UTC, benrudolph commented on corehq/apps/cloudcare/static/cloudcare/js/form_entry/fullform-ui.js
> +            && !self.children()[0].pendingAnswer();
same here

2016-10-05 19:10 UTC, benrudolph commented
looks good! one question about validating all the children, but other than that g2m when ✔️

2016-10-05 19:23 UTC, biyeun commented on corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js
> +                    method: "notifyWhenChangesStop"
it would add a delay to other widget (checkbox / radios / date)

2016-10-05 19:24 UTC, biyeun commented on corehq/apps/cloudcare/static/cloudcare/js/form_entry/fullform-ui.js
> +            && self.children()[0].isValid()
lol yes I actually did this in a later commit...let me push that upstream

2016-10-05 19:27 UTC, dimagimon commented
There are 24 errors:

* corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js, line 95 - Missing trailing comma. (comma-dangle)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js, line 96 - Missing trailing comma. (comma-dangle)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js, line 103 - 'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js, line 106 - Missing trailing comma. (comma-dangle)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js, line 107 - Missing trailing comma. (comma-dangle)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js, line 110 - 'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js, line 539 - Expected indentation of 8 space characters but found 12. (indent)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js, line 542 - Expected indentation of 8 space characters but found 12. (indent)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js, line 545 - Expected indentation of 8 space characters but found 12. (indent)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 270 - 'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 271 - 'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 272 - 'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 289 - 'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 292 - 'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 295 - 'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 342 - Expected indentation of 8 space characters but found 12. (indent)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 343 - Expected indentation of 8 space characters but found 12. (indent)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 355 - Expected indentation of 8 space characters but found 12. (indent)
'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 356 - Expected indentation of 4 space characters but found 8. (indent)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 366 - Expected indentation of 8 space characters but found 12. (indent)
'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 367 - Expected indentation of 4 space characters but found 8. (indent)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 377 - Expected indentation of 8 space characters but found 12. (indent)
'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 378 - Expected indentation of 8 space characters but found 12. (indent)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 379 - Expected indentation of 4 space characters but found 8. (indent)

2016-10-06 02:43 UTC, benrudolph commented on corehq/apps/cloudcare/static/cloudcare/js/form_entry/fullform-ui.js
> +            return (q.answer() === null && !q.required()) || q.answer() !== null;
nit: in most of the code i use `Const.NO_ANSWER` so it's more explicit. there's a subtle difference between `null` and `undefined` for the answer and i think using the constants make it more clear

2016-10-06 02:44 UTC, benrudolph approved these changes

2016-10-06 02:45 UTC, benrudolph commented
(tests failures are real)

2016-10-06 20:45 UTC, dimagimon commented
There are 32 errors:

* corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js, line 93 - 'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js, line 94 - Missing trailing comma. (comma-dangle)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js, line 97 - 'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js, line 526 - Expected indentation of 8 space characters but found 12. (indent)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js, line 529 - Expected indentation of 8 space characters but found 12. (indent)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/entrycontrols_full.js, line 532 - Expected indentation of 8 space characters but found 12. (indent)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/entrycontrols_full_spec.js, line 82 - 'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/entrycontrols_full_spec.js, line 198 - 'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/entrycontrols_full_spec.js, line 202 - 'entry' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/entrycontrols_full_spec.js, line 203 - 'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/entrycontrols_full_spec.js, line 213 - 'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/entrycontrols_full_spec.js, line 217 - 'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/entrycontrols_full_spec.js, line 221 - 'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/integration_spec.js, line 81 - 'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/integration_spec.js, line 88 - 'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/integration_spec.js, line 124 - 'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/spec/integration_spec.js, line 130 - 'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 270 - 'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 271 - 'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 272 - 'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 289 - 'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 292 - 'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 295 - 'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 343 - Expected indentation of 8 space characters but found 12. (indent)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 344 - Expected indentation of 8 space characters but found 12. (indent)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 356 - Expected indentation of 8 space characters but found 12. (indent)
'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 357 - Expected indentation of 4 space characters but found 8. (indent)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 367 - Expected indentation of 8 space characters but found 12. (indent)
'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 368 - Expected indentation of 4 space characters but found 8. (indent)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 378 - Expected indentation of 8 space characters but found 12. (indent)
'Formplayer' is not defined. (no-undef)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 379 - Expected indentation of 8 space characters but found 12. (indent)
* corehq/apps/cloudcare/static/cloudcare/js/form_entry/webformsession.js, line 380 - Expected indentation of 4 space characters but found 8. (indent)

2016-10-06 20:52 UTC, biyeun commented
@benrudolph you can look now

2016-10-07 14:39 UTC, benrudolph commented on corehq/apps/cloudcare/static/cloudcare/js/form_entry/fullform-ui.js
> +                || q.answer() !== null;
this one still doesn't use the constant

2016-10-07 14:39 UTC, benrudolph commented
nothing blocking! woot woot!

2016-10-07 14:39 UTC, merged

2016-10-07 14:40 UTC, benrudolph commented
just realized this probably broke app preview since we dn't have the formplayer part merged. i think that's fine, but let me know if you think we should revert