Added quarter filter to UCR
dimagi/commcare-hq pull request #13670
Opened 2016-10-21 13:53 UTC by kkrampa

@czue 
We need this filter in a couple of enikshay reports. Probably it's better to have this filter in enikshay custom module but I didn't find way to do it. What do you think about this solution?

![quarter](https://cloud.githubusercontent.com/assets/5538370/19600651/4aa7d468-97a6-11e6-8851-115dc04cd237.png)

2016-10-21 14:28 UTC, czue requested changes
This looks good to me. I think it's ok this to be here since I believe it would be generally useful for other projects/reports. Can you update the UCR docs to include this?

2016-10-21 14:28 UTC, czue commented on corehq/apps/reports_core/filters.py
> +    def __init__(self, name, label='Quarter', css_id=None):
should this be lazy translated?

2016-10-26 15:12 UTC, kkrampa commented
@czue Updated

2016-10-26 15:27 UTC, czue approved these changes
:+1: thanks

2016-10-26 19:36 UTC, kkrampa commented
@czue :white_check_mark:

2016-10-26 19:51 UTC, merged