MDR suspect report
dimagi/commcare-hq pull request #13839
Opened 2016-11-04 14:57 UTC by kkrampa

It's better to review both commits separately. @czue Any suggestions to index column?

2016-11-04 16:28 UTC, czue commented
@kkrampa the purpose of the `IndexColumn` is to just have a column in each row that increments a counter in the report? It feels pretty silly to me - can we potentially check with Erin if we can get rid of it? If we do need it I don't immediately have a better solution, though definitely don't love the tech debt that this one adds. I'll make a few other comments, but maybe we can add this report without the `IndexColumn` and then see what erin says?

2016-11-04 16:31 UTC, czue requested changes

2016-11-04 16:31 UTC, czue commented on corehq/apps/userreports/reports/util.py
> +    return 'index{}'.format(hashlib.sha1(hashlib.sha1(domain).hexdigest()).hexdigest()[:8])
why hash the domain twice?

2016-11-04 16:31 UTC, czue commented on corehq/apps/userreports/tests/test_columns.py
> +        }])
looks like these got copy/pasted to a bunch of places. could we make it a class attribute to avoid that?

2016-11-09 12:35 UTC, kkrampa commented
@czue I will ask Erin if we can drop this field.

2016-11-10 12:33 UTC, kkrampa commented
@czue I removed commit with index column and index column from report.

2016-11-10 12:37 UTC, czue approved these changes
thanks

2016-11-10 14:01 UTC, kkrampa commented
:white_check_mark:

2016-11-10 14:04 UTC, merged