Allow arbitrary xpath in default search properties
dimagi/commcare-hq pull request #13994
Opened 2016-11-21 20:18 UTC by proteusvacuum

Don't wrap default search values in quotes, so generic XPath expressions are evaluated on mobile. Instances referenced in those XPaths are also added into the RemoteRequest. 

This is needed by `m2m` who want to have a default search property that automatically searches cases based on the user's location.

Did a bunch of refactoring and updating of the UI as it was pretty messy and somewhat broken, and I'm planning on doing more work here soon.

@emord @dannyroberts

2016-11-21 20:19 UTC, dimagimon commented on corehq/apps/app_manager/suite_xml/sections/remote_requests.py
> +                url=absolute_reverse('claim_case', args=[self.domain]),
E126 continuation line over-indented for hanging indent

2016-11-21 20:19 UTC, dimagimon commented on corehq/apps/app_manager/suite_xml/sections/remote_requests.py
> +            )
E121 continuation line under-indented for hanging indent

2016-11-21 20:19 UTC, dimagimon commented on corehq/apps/app_manager/tests/test_suite_remote_request.py
> +                    defaultValue="instance('casedb')/case[@case_id='instance('commcaresession')/session/data/case_id']/some_property"),
E501 line too long (135 > 115 characters)

2016-11-22 14:42 UTC, emord approved these changes
Is `querysession` something specific to case search? I don't remember seeing it before

2016-11-22 14:49 UTC, proteusvacuum commented
Yeah, for some reason we named `commcaresession` as `querysession` when it related to case search. I don't think there was any reason for it, other than being a bit clearer what the session was referring to. I had to change it to `commcaresession` here as that is what the Instance builder generates.

2016-11-22 14:56 UTC, emord requested changes

2016-11-22 14:56 UTC, emord commented on corehq/apps/app_manager/tests/data/suite/remote_request.xml
>            relevant="count(instance('casedb')/casedb/case[@case_id=instance('querysession')/session/data/case_id]) = 0">
should be `commcaresession`?

2016-11-22 14:56 UTC, emord commented on corehq/apps/app_manager/suite_xml/sections/remote_requests.py
> +                    # e.g. instance('querysession')/session/data/case_id
`commcaresession`

2016-11-22 15:34 UTC, dimagimon commented on corehq/apps/app_manager/const.py
> +CLAIM_DEFAULT_RELEVANT_CONDITION = "count(instance('casedb')/casedb/case[@case_id=instance('commcaresession')/session/data/case_id]) = 0"
E501 line too long (137 > 115 characters)

2016-11-22 15:44 UTC, emord approved these changes

2016-11-22 17:14 UTC, emord commented
annoying but real failure:

```
======================================================================
FAIL: Suite should include remote-request if searching is configured
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/commcare-hq-ro/corehq/apps/app_manager/tests/test_suite_remote_request.py", line 56, in test_remote_request
    self.assertXmlPartialEqual(self.get_xml('remote_request'), suite, "./remote-request[1]")
  File "/mnt/commcare-hq-ro/corehq/apps/app_manager/tests/util.py", line 26, in assertXmlPartialEqual
    self.assertXmlEqual(expected, actual, normalize=False)
  File "/mnt/commcare-hq-ro/corehq/apps/app_manager/tests/util.py", line 32, in assertXmlEqual
    _check_shared(expected, actual, LXMLOutputChecker(), "xml")
  File "/mnt/commcare-hq-ro/corehq/apps/app_manager/tests/util.py", line 126, in _check_shared
    raise AssertionError(message)
AssertionError: XML mismatch
--- want.xml
+++ got.xml
@@ -10,10 +10,10 @@
         </text>
       </display>
     </command>
+    <instance id="groups" src="jr://fixture/user-groups"/>
     <instance id="locations" src="jr://fixture/commtrack:locations"/>
     <instance id="casedb" src="jr://instance/casedb"/>
     <instance id="commcaresession" src="jr://instance/session"/>
-    <instance id="groups" src="jr://fixture/user-groups"/>
     <session>
       <query storage-instance="results" template="case" url="https://www.example.com/a/test_domain/phone/search/">
         <data key="case_type" ref="'case'"/>
----------------------------------------------------------------------
```

2016-11-23 14:51 UTC, proteusvacuum commented
✅

2016-11-23 14:52 UTC, merged