Revert remaining changes from PR#14004
dimagi/commcare-hq pull request #14154
Opened 2016-12-07 19:29 UTC by biyeun

https://github.com/dimagi/commcare-hq/pull/14004

Causing issues with form loading in firefox...

@benrudolph 
@wpride

2016-12-07 19:33 UTC, benrudolph requested changes

2016-12-07 19:33 UTC, benrudolph commented on corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js
> -            FormplayerFrontend.trigger('navigateHome');
this is still needed

2016-12-07 19:34 UTC, benrudolph commented
@wpride it was causing issues on firefox so we decided to revert until we have updates. when that gets in we can then worry about how to fix these issues

2016-12-08 00:12 UTC, biyeun commented on corehq/apps/cloudcare/static/cloudcare/js/formplayer/app.js
> -            FormplayerFrontend.trigger('navigateHome');
thanks for the catch. putting this back

2016-12-08 19:21 UTC, biyeun commented
@benrudolph responded

2016-12-08 19:24 UTC, benrudolph approved these changes

2016-12-08 20:16 UTC, biyeun commented
@benrudolph ✅

2016-12-08 20:19 UTC, merged