jQuery 3 retry
dimagi/commcare-hq pull request #14233
Opened 2016-12-14 19:30 UTC by orangejenny

Re-releasing jQuery 3, but leaving new cloudcare on jQuery 2 because [Marionette 2 and jQuery 3 seem to be incompatible](https://github.com/marionettejs/backbone.marionette/issues/3018).

I also left old cloudcare on jQuery 2, because it has some incompatibilities, which are likely fixable, but if we're almost done with old cloudcare, doesn't seem worth the trouble to migrate.

It's possible that issues will arise in the future if HQ's base template calls code that's jq2-incompatible, but don't think it's that likely, since the base template doesn't do much. Hoping that new cloudcare will eventually upgrade marionette.

@benrudolph

2016-12-14 19:44 UTC, benrudolph requested changes
one minor thing for app preview

2016-12-14 19:44 UTC, benrudolph commented on corehq/apps/cloudcare/views.py
>      @method_decorator(requires_privilege_for_commcare_user(privileges.CLOUDCARE))
i think we also need it for `PreviewAppView`

2016-12-14 20:02 UTC, orangejenny commented on corehq/apps/cloudcare/views.py
>      @method_decorator(requires_privilege_for_commcare_user(privileges.CLOUDCARE))
confused - doesn't line 363 handle `PreviewAppView`?

2016-12-14 20:17 UTC, benrudolph commented on corehq/apps/cloudcare/views.py
>      @method_decorator(requires_privilege_for_commcare_user(privileges.CLOUDCARE))
oops sorry missed that

2016-12-14 20:18 UTC, benrudolph approved these changes

2016-12-19 14:19 UTC, orangejenny commented
qa passed, this is good to go

2016-12-19 18:21 UTC, orangejenny commented
Since approved, I just added a commit and then later reverted it. Self-merging.

2016-12-19 18:21 UTC, merged