remove duplicated assignment of case_id
dimagi/commcare-hq pull request #14295
Opened 2016-12-20 18:24 UTC by nickpell

re: https://github.com/dimagi/commcare-hq/pull/13293#discussion_r92798593

case_id is already assigned here: https://github.com/dimagi/commcare-hq/blob/master/corehq/ex-submodules/casexml/apps/case/mock/mock.py#L18

@proteusvacuum @czue

2016-12-20 18:31 UTC, proteusvacuum commented on custom/enikshay/nikshay_datamigration/factory.py
> +        self.factory.create_or_update_case(person_structure)
I think you can just remove this call and the one for occurrence too. Both the person and occurrence should get created with this `self.factory.create_or_update_case(episode_structure)`.

2016-12-20 18:33 UTC, proteusvacuum commented on custom/enikshay/nikshay_datamigration/factory.py
> +        self.factory.create_or_update_case(person_structure)
see [here](https://github.com/dimagi/commcare-hq/blob/master/custom/enikshay/tests/utils.py#L84-L85) for an example.

2016-12-20 19:19 UTC, nickpell commented on custom/enikshay/nikshay_datamigration/factory.py
> +        self.factory.create_or_update_case(person_structure)
updated

2016-12-21 03:02 UTC, nickpell commented
✅

2016-12-21 08:10 UTC, czue approved these changes
only reviewed quickly so will let @proteusvacuum merge

2016-12-21 16:37 UTC, proteusvacuum requested changes

2016-12-21 16:37 UTC, proteusvacuum commented on custom/enikshay/nikshay_datamigration/factory.py
> +            matching_occurrence_case = next((
@nickpell to update this with `case-utils` method

2016-12-21 19:58 UTC, nickpell commented on custom/enikshay/nikshay_datamigration/factory.py
> +            matching_occurrence_case = next((
requires https://github.com/dimagi/commcare-hq/pull/14306

2016-12-21 21:58 UTC, dimagimon commented on custom/enikshay/nikshay_datamigration/factory.py
> +from corehq.form_processor.exceptions import CaseNotFound
F401 'CaseNotFound' imported but unused

2016-12-21 21:58 UTC, nickpell commented on custom/enikshay/nikshay_datamigration/factory.py
> +            matching_occurrence_case = next((
updated

2016-12-21 23:31 UTC, proteusvacuum approved these changes
awesome, thanks for updating!

2016-12-21 23:31 UTC, proteusvacuum commented on custom/enikshay/nikshay_datamigration/factory.py
> +        if self.person().attrs['create']:
nice.

2016-12-21 23:31 UTC, proteusvacuum commented on custom/enikshay/nikshay_datamigration/factory.py
> +                    'episode_type': 'confirmed_tb',
👍

2016-12-21 23:31 UTC, merged