assign owner_id
dimagi/commcare-hq pull request #14318
Opened 2016-12-22 18:31 UTC by nickpell

@proteusvacuum @czue

2016-12-22 18:32 UTC, nickpell commented on custom/enikshay/nikshay_datamigration/tests/test_create_enikshay_cases.py
> +        self.assertEqual(person_case.owner_id, '')
is blank ```owner_id``` the right thing to do when there's no location? @proteusvacuum

2016-12-22 18:42 UTC, proteusvacuum requested changes
Coming along! 
I think you also need to set all the owner ids of "extension" cases (`episode`, `occurrence`, `test`) to `'-'`

2016-12-22 18:42 UTC, proteusvacuum commented on custom/enikshay/nikshay_datamigration/tests/test_create_enikshay_cases.py
> +        self.assertEqual(person_case.owner_id, '')
Hmm. I think it might be better to set it to `'_archive_'` and set `person.archive_reason = 'migration_location_not_found'`

2016-12-22 18:42 UTC, proteusvacuum commented on custom/enikshay/nikshay_datamigration/factory.py
> +        if self._location:
I think we should check that this location has location_type "phi", otherwise it should fail.

2016-12-22 19:13 UTC, nickpell commented on custom/enikshay/nikshay_datamigration/factory.py
> +        if self._location:
does ```'_archive_'``` have any special meaning in HQ?

2016-12-22 19:17 UTC, proteusvacuum commented on custom/enikshay/nikshay_datamigration/factory.py
> +        if self._location:
Kind of. It is a "[weird owner id](https://github.com/dimagi/commcare-hq/blob/db17403a17c815ed663943e90afca3d5032d2c07/corehq/apps/users/util.py#L19-L26)" so we don't do stuff in the restore with those IDs. 
We are using it elsewhere in the eNikshay app to signify "a closed case that we might want to open in the app after searching for it with case claim at some point".

2016-12-22 22:05 UTC, nickpell commented on custom/enikshay/nikshay_datamigration/factory.py
> +        if self._location:
added an assert

2016-12-22 22:15 UTC, dimagimon commented on custom/enikshay/nikshay_datamigration/tests/test_create_enikshay_cases.py
> +        self.assertEqual(person_case.dynamic_case_properties()['migration_archive_reason'], 'migration_location_not_found')
E501 line too long (123 > 115 characters)

2016-12-22 22:16 UTC, nickpell commented on custom/enikshay/nikshay_datamigration/tests/test_create_enikshay_cases.py
> +        self.assertEqual(person_case.owner_id, '')
added ```'_archive_'``` and set an archive reason (used the prefix ```migration_``` to be consistent with other case properties added by the migration)

2016-12-23 05:37 UTC, czue commented
fyi conflicts

2016-12-23 14:31 UTC, nickpell commented
fixed conflicts

2016-12-23 14:31 UTC, proteusvacuum requested changes
Couple of comments, sorry I wasn't clear in the first place

2016-12-23 14:31 UTC, proteusvacuum commented on custom/enikshay/nikshay_datamigration/factory.py
> +            kwargs['attrs']['update']['migration_archive_reason'] = 'migration_location_not_found'
this should still be `archive_reason` since that is the property we are going to be using to figure out why the cases were archived

2016-12-23 14:31 UTC, proteusvacuum commented on custom/enikshay/nikshay_datamigration/factory.py
> +        if self._location:
sorry, when, I said "fail", I meant that we should still assign to the `_archive_` owner id, set the `archive_reason`, and `migration_error` to `migration_not_phi_location` or something.

2016-12-23 14:31 UTC, proteusvacuum commented on custom/enikshay/nikshay_datamigration/factory.py
> +            assert self._location.location_type.name == 'phi'
I think you want to use `location_type.code` in this check

2016-12-23 14:31 UTC, proteusvacuum commented on custom/enikshay/nikshay_datamigration/factory.py
> +            kwargs['attrs']['owner_id'] = '_archive_'
I think it might be better if you use the constant defined in `casexml.apps.case.const`

2016-12-23 18:00 UTC, nickpell commented
@proteusvacuum updated

2016-12-23 18:06 UTC, proteusvacuum approved these changes
nit: There's also the "UNOWNED_EXTENSION_OWNER_ID" constant that you could use instead of the hardcoded `-`, but that's not important. 
G2M on ✅

2016-12-23 19:33 UTC, merged