Subscription UI Changes
dimagi/commcare-hq pull request #14473
Opened 2017-01-10 04:10 UTC by sravfeyn

Implements https://docs.google.com/document/d/1SkdI30F1O2MbSKCEn5VSVGjse_DJUQnvmpuSiK77GN8/edit#

@nickpell @esoergel

2017-01-10 04:11 UTC, dimagimon commented on corehq/apps/accounting/static/accounting/js/accounting.credits.js
> +    }
Missing semicolon. (semi)

2017-01-10 04:12 UTC, sravfeyn commented
@nickpell I am putting this up on staging for QA. Let me know if the changes are too simple for QA and I will not proceed for a QA

2017-01-10 19:17 UTC, nickpell commented
@sravfeyn I think an adequate way to test this is to set up several domains on staging, each of which has one combination of credit line types, and check that they are displayed correctly.  I don't think any QA beyond that is necessary.

Example: see https://staging.commcarehq.org/a/general-credit/settings/project/subscription/ and the comment I left in the doc.  This domain has credit in the general subscription credit line and no credit in any account level credit lines or any feature/product level credit lines.

2017-01-13 09:45 UTC, sravfeyn commented
I have responded on the spec doc re. the above comment.

2017-01-13 09:46 UTC, sravfeyn commented on corehq/apps/domain/views.py
> +            has_credits_in_non_general_credit_line = any(
@nickpell This is the core of 'has credits in non general credit lines'. Can you see if it looks good?

Also per the comment on spec, should I set this to True if no credit-lines exist?

2017-01-13 14:50 UTC, nickpell commented on corehq/apps/domain/views.py
> +            has_credits_in_non_general_credit_line = any(
I'd continue to set ```has_credits_in_non_general_credit_line``` to ```False``` if no credit lines exist

2017-01-13 14:51 UTC, nickpell commented
Updated [comment](https://docs.google.com/document/d/1SkdI30F1O2MbSKCEn5VSVGjse_DJUQnvmpuSiK77GN8/edit?disco=AAAAA5qjvDg)

2017-01-16 08:49 UTC, sravfeyn commented on corehq/apps/accounting/models.py
> +    def get_non_general_credits_by_subscription(cls, subscription):
@nickpell I have updated non-general credit query per your comment. Does this look right now?

2017-01-17 19:44 UTC, nickpell commented on corehq/apps/domain/views.py
> +            has_credits_in_non_general_credit_line = len(credit_lines) > 0
you'll still want to check that ```balance``` is greater than 0.

2017-01-17 19:46 UTC, nickpell requested changes
Looking close.  One comment below.  I also noticed that https://staging.commcarehq.org/a/general-credit/settings/project/subscription/ doesn't match the format in https://staging.commcarehq.org/a/no-credit/settings/project/subscription/.  Specifically, "General Credits" should not show and should be "Credits Remaining" instead.

2017-01-18 04:03 UTC, sravfeyn commented on corehq/apps/domain/views.py
> +            has_credits_in_non_general_credit_line = len(credit_lines) > 0
Cool, I have updated this

2017-01-18 04:07 UTC, sravfeyn commented
Re 'General Credits', there is nothing mentioned regarding this in the spec. So I haven't changed its behaviour. That text is shown `if plan.general_credit and plan.general_credit.is_visible ` per [current code](https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/domain/templates/domain/current_subscription.html#L170). When should it show and not show? (I am pretty confused with 'general' vs 'non-general' so I am not able to deduct any spec logic just by looking at the code)

2017-01-29 16:10 UTC, sravfeyn commented
@nickpell

2017-02-07 14:55 UTC, nickpell commented
hey, I should get to this by end of wednesday at the latest

2017-02-08 22:55 UTC, nickpell commented
make that end of thursday

2017-02-09 05:15 UTC, sravfeyn commented
Okay

2017-02-14 18:39 UTC, nickpell commented
Made some updates.  My test cases are as follows:

Show the new UI:
1) When you have general credit: https://staging.commcarehq.org/a/general-credit/settings/project/subscription/
2) When you have no credit: https://staging.commcarehq.org/a/no-credit/settings/project/subscription/

Show the old UI:
1) When you have plan credit: https://staging.commcarehq.org/a/plan-credit/settings/project/subscription/
2) When you have user credit: https://staging.commcarehq.org/a/feature-credit/settings/project/subscription/
4) When you have plan and user credit: https://staging.commcarehq.org/a/plan-feature-credit/settings/project/subscription/
5) When you have plan and general credit: https://staging.commcarehq.org/a/general-and-plan-credit/settings/project/subscription/
6) When you have general and user credit: https://staging.commcarehq.org/a/general-and-featurecredit/settings/project/subscription/

The Usage Summary table is blank in the new UI: https://staging.commcarehq.org/a/no-credit/settings/project/subscription/  Once you fix that and test on staging this PR will be good to merge.

@sravfeyn

2017-02-21 07:27 UTC, sravfeyn commented
Thanks @nickpell for the updates! 

I have fixed the empty value issue. It was caused as you have referenced `limit` atttr of `CreditItem` which wasn't there. [Adding that](https://github.com/dimagi/commcare-hq/pull/14473/commits/dc5d30171e3adca94842842c968874f89e7cb7e4) fixed the issue

2017-02-21 14:01 UTC, nickpell commented
Looks good!

2017-02-21 14:01 UTC, merged