update user buckets;
dimagi/commcare-hq pull request #14475
Opened 2017-01-10 08:23 UTC by sravfeyn

https://docs.google.com/document/d/1aDHbjhpdWwvgKjlOY4f5ksOVQWAv3CwyMep2mDv09uY/edit

@esoergel 

@nickpell Is this all that's needed for that spec?

2017-01-10 18:59 UTC, nickpell requested changes
one comment; otherwise looks good

2017-01-10 18:59 UTC, nickpell commented on corehq/apps/accounting/bootstrap/config/user_buckets_jan_2017.py
> +        'role': 'community_plan_v0',
should be ```community_plan_v1```

2017-01-13 05:28 UTC, sravfeyn commented on corehq/apps/accounting/bootstrap/config/user_buckets_jan_2017.py
> +        'role': 'community_plan_v0',
(Updated) @nickpell

2017-01-13 14:13 UTC, nickpell commented
👍

2017-01-13 14:13 UTC, merged