POC hide reports sidebar on mobile
dimagi/commcare-hq pull request #14517
Opened 2017-01-13 12:35 UTC by snopoke

http://manage.dimagi.com/default.asp?245529

### Menu hidden (default view)
![reports_mobile_menu_hidden](https://cloud.githubusercontent.com/assets/249606/21930169/38927574-d99d-11e6-84a5-b53fa1589793.png)

### Menu shown
![reports_mobile_menu_shown](https://cloud.githubusercontent.com/assets/249606/21930174/3f066bc2-d99d-11e6-9be4-0dc62b76223a.png)

### Menu shown (with border)
![reports_mobile_menu_shows_border](https://cloud.githubusercontent.com/assets/249606/21930183/48b112f8-d99d-11e6-9883-5fbd6df7e499.png)

2017-01-13 13:33 UTC, czue approved these changes
nice this looks great! thanks for taking care of it!

will let @biyeun review and merge but seems great to me.

2017-01-13 15:11 UTC, biyeun requested changes
Can we have the button in line with the header text for the filters? Alternatively, can we remove the button styling on this and just have the icon? The whitespacing is not great here. If there's any confusion I can take a pass by Monday with the styling.

2017-01-13 18:48 UTC, snopoke commented
I took a quick crack at it but didn't get far. Removing the button styling doesn't look great. If you have time on Monday that would be great otherwise I'll fiddle with it next week.

2017-01-14 05:21 UTC, czue commented
@biyeun do you think the style change needs to block merge? just wondering because i think this is already a significant improvement and would be great to demo this workflow for some TB partners early next week

2017-01-17 03:47 UTC, czue commented
@biyeun can you please weigh in on my last question?

2017-01-17 15:56 UTC, biyeun commented
@czue, sorry have been partially offline yesterday and over the weekend and didn't realize this was so pressing. 

@snopoke I think the best thing you can do for the design here is to remove the border and the rounded edges from this button and make the background transparent. Give it a separate style like `btn-corner`. 

@orangejenny not sure if you had any additional thoughts here. 

One of the biggest issues with this is that you have two borders touching each other creating very weird whitespace artifacts. It should be trivial to make this change.

2017-01-17 16:08 UTC, orangejenny commented
@biyeun I defer to you, but yeah, the borders touching is the thing that looks off to me. Removing the button border when the left-hand menu is shown, and moving the button into the "Report Filters" legend when the menu isn't being shown (either as a button or just a plain icon), would fix that.

2017-01-17 16:34 UTC, orangejenny commented
Poked at this in the debugger locally. Just getting rid of the background and border on the icon (new `invisible-btn` class?) makes it a bit better. @biyeun do you think that's all right?

<img width="261" alt="screen shot 2017-01-17 at 11 32 43 am" src="https://cloud.githubusercontent.com/assets/1486591/22029534/d508d67e-dca8-11e6-880b-89c9119a500d.png">
<img width="390" alt="screen shot 2017-01-17 at 11 32 53 am" src="https://cloud.githubusercontent.com/assets/1486591/22029535/d50c78ce-dca8-11e6-9764-7964bde168a5.png">

2017-01-17 16:36 UTC, biyeun commented
@czue To be honest, this particular widget **is going to need a lot more design thought than just a casual glance at this PR**---and this is on me to do this thinking. I'm bogged down getting some stuff thru before Amelia heads out and I go on vacation, but I really want to make it clear that **this widget still needs work**. Since there is pressure to merge this in right away before putting in more design thought, I really want to caution against this widget suddenly being used everywhere. I'm afraid this is going to happen simply due to merging this in. 

It seems strange that this didn't go through an initial design brainstorming / review for the interaction and visual design and was just implemented through the interrupt stream and none of the design people were notified. Any new widget like this that isn't a one-off and client specific should be going through the design team, not slipped in through interrupt. Seems like we could have thought of something better than a drawer slider that would make sense for all the pages' navs not just report builder. @orangejenny not sure if you had more thoughts here.

----

Another thought for @snopoke for this particular PR:
The bar icon doesn't make sense because we use it for additional menus / drop down menus elsewhere on HQ. I would use [this icon](http://fontawesome.io/icon/ellipsis-v/) instead because it isn't really associated with anything else on HQ.

2017-01-17 16:46 UTC, czue commented
hey @biyeun all of that sounds right. understand this is not the ideal process you wanted to go through, and also hope you can also understand that we need to be moving quickly on these things.

given that we don't have time for a design review right now since this is not a product priority, i think the options are merge-as-is, or do extra work to complicate the implementation to put behind a flag so that only TB sees this. if we don't think this change is harmful (which i haven't heard anyone say) i would advocate for letting it through now. 

> I really want to caution against this widget suddenly being used everywhere

this seems totally valid.

> I'm afraid this is going to happen simply due to merging this in.

however i think we need to come up with a better plan than this to enforce it.

2017-01-17 18:16 UTC, snopoke commented
Thanks for the feedback. I completely agree that a general solution to this should go through design review etc. I consider this a stop gap until that happens. I also agree that this should not be applied to any other part of HQ (in fact I'd argue that it isn't useful in most of HQ at all).

I did a quick analytics analysis and found that over the 60 days:

* Mobile + tablet views = 2.5% of total page views
* Mobile + tablet views of reports = 0.38 % of total page views

This indicates to me that the large majority of our users won't even see this change.

I'll update the styling as suggested tomorrow.

2017-01-17 21:54 UTC, biyeun commented
@orangejenny the change is still not ideal, but it's better than without. I still advocate for the icon change

2017-01-18 14:23 UTC, snopoke commented
Updated:

![reports_sidebar_hidden](https://cloud.githubusercontent.com/assets/249606/22055847/ce3e497e-dd65-11e6-961d-820ec13d5028.png)
![reports_sidebar_visible](https://cloud.githubusercontent.com/assets/249606/22055848/ce43bf94-dd65-11e6-9cc0-ebb4f08f2966.png)

2017-01-18 16:01 UTC, orangejenny commented
Code looks fine, thanks for updating both the border/color and the icon. Commented in the ticket on release plan.

2017-01-20 22:28 UTC, biyeun commented
Responded in the original ticket FYI @orangejenny @czue @snopoke

2017-01-23 13:11 UTC, snopoke commented
@biyeun @czue @orangejenny updated per suggestions in the ticket:
* menu button now in breadcrumbsm
* menu is full width when visible

Other points:
* report content is still visible below menu
* not transition for showing menu (I tried a few thing but didn't get anything working smoothly)

2017-01-24 06:41 UTC, czue commented
@biyeun @orangejenny can you take a look at this and see if it is ok to get in now?

2017-01-24 14:41 UTC, orangejenny commented on corehq/apps/reports/templates/reports/standard/base_template.html
> +        $(document).ready(function () {
Should be `$(function() {` for jQuery 3. I think this style will still work, but it's deprecated: https://jquery.com/upgrade-guide/3.0/#deprecated-document-ready-handlers-other-than-jquery-function

2017-01-24 14:42 UTC, orangejenny commented on corehq/apps/reports/templates/reports/standard/base_template.html
> +    <a href="#" class="btn btn-link btn-invisible visible-xs btn-report-menu" data-toggle="offcanvas"><i class="fa fa-bars"></i> Reports Menu</a>
`trans`

2017-01-24 14:47 UTC, orangejenny commented
Looks reasonable to me, just very minor comments, will wait on merging in case you want to respond. Transition would be cool but agree it isn't necessary, and it can be added later without changing the basic interaction/design.

Thank you for being patient with the back & forth on this.

2017-01-24 16:02 UTC, snopoke commented
Updated. Thanks for the great feedback!

2017-01-24 16:04 UTC, orangejenny approved these changes

2017-02-02 07:54 UTC, merged