Allow case lists to handle actions
dimagi/commcare-hq pull request #14703
Opened 2017-01-31 14:44 UTC by wpride

cross-request: https://github.com/dimagi/formplayer/pull/282

fixes: http://manage.dimagi.com/default.asp?246634

2017-01-31 16:29 UTC, benrudolph requested changes

2017-01-31 16:29 UTC, benrudolph commented on corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
> +            }
this is pretty confusing, where is tempData used and why do we need to do this for just the graph style?

2017-01-31 16:29 UTC, benrudolph commented on corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
> +                if(this.options.styles[i] === "graph") {
`if (`

2017-01-31 16:29 UTC, benrudolph commented on corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
> +            for (var i =0; i < tempData.length; i++) {
`i = 0`

2017-01-31 16:29 UTC, benrudolph commented on corehq/apps/cloudcare/templates/formplayer/case_list.html
> +              <button type="button" class="btn btn-success btn-lg" id="double-management" index="<%= index %>"><%= action.text %></button>
the way to add data to html is to use the `data-` prefix. so this should be `data-index=`

2017-01-31 16:29 UTC, benrudolph commented on corehq/apps/cloudcare/static/cloudcare/js/formplayer/menus/views.js
> +            var index = e.currentTarget.getAttribute('index')
if you use `data-index` you can then do `$(e.currentTarget).data().index`

2017-01-31 16:56 UTC, czue commented
thanks bud

2017-02-01 14:51 UTC, wpride commented
@benrudolph thanks - the graph stuff shouldn't have been in here

2017-02-01 17:09 UTC, benrudolph approved these changes
nice 👍

2017-02-02 08:55 UTC, merged