py3 userreports filters
dimagi/commcare-hq pull request #14735
Opened 2017-02-03 19:43 UTC by nickpell

@emord @millerdev

2017-02-06 14:50 UTC, millerdev requested changes
Test failure is real:
```
ERROR: test_complex_structure (corehq.apps.userreports.tests.test_filters.ComplexFilterTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/commcare-hq-ro/corehq/apps/userreports/tests/test_filters.py", line 359, in test_complex_structure
    self.assertTrue(filter(dict(foo='bar')))
  File "/mnt/commcare-hq-ro/corehq/apps/userreports/filters/__init__.py", line 48, in __call__
    return any(list(filter(item, context)) for filter in self.filters)
  File "/mnt/commcare-hq-ro/corehq/apps/userreports/filters/__init__.py", line 48, in <genexpr>
    return any(list(filter(item, context)) for filter in self.filters)
TypeError: 'bool' object is not iterable
```

2017-02-06 14:50 UTC, millerdev commented on corehq/apps/userreports/filters/__init__.py
> +        return all(list(filter(item, context)) for filter in self.filters)
This doesn't look right. `filter` is a local here, not the global/builtin `filter`. Does it return a list?

2017-02-06 14:50 UTC, millerdev commented on corehq/apps/userreports/filters/__init__.py
> +        return any(list(filter(item, context)) for filter in self.filters)
Same as above

2017-02-07 23:40 UTC, nickpell commented on corehq/apps/userreports/filters/__init__.py
> +        return all(list(filter(item, context)) for filter in self.filters)
nice catch

2017-02-08 14:35 UTC, millerdev approved these changes

2017-02-08 22:58 UTC, merged