Update toggles.py
dimagi/commcare-hq pull request #14744
Opened 2017-02-03 21:27 UTC by krsdimagi

[ci skip]

@esoergel @robin824 adding help links to the feature flags page.

2017-02-03 22:31 UTC, esoergel requested changes

2017-02-03 22:31 UTC, esoergel commented on corehq/toggles.py
> +    namespaces=[NAMESPACE_DOMAIN]
@krsdimagi both versions of this are actually valid.  In python, you can use both "positional" arguments and "keyword" (aka "named") arguments.  The interplay between the two is a little strange, if you're interested in learning more, those are some terms to google.

2017-02-03 22:31 UTC, esoergel commented on corehq/toggles.py
> +    namespace=[NAMESPACE_DOMAIN]
This should be `namespaces`

2017-02-03 22:49 UTC, krsdimagi commented on corehq/toggles.py
> +    namespaces=[NAMESPACE_DOMAIN]
Thanks!  Will take a look.

2017-02-04 01:27 UTC, esoergel approved these changes

2017-05-16 04:08 UTC, merged