Add repeaters and corresponding generators to FollowUp and HIVTest Ap…
dimagi/commcare-hq pull request #14758
Opened 2017-02-06 15:31 UTC by mkangia

…i end points

2017-02-06 15:32 UTC, dimagimon commented on custom/enikshay/integrations/nikshay/repeaters.py
> +        person_case_properties = person_case.dynamic_case_properties()
F841 local variable 'person_case_properties' is assigned to but never used

2017-02-10 10:38 UTC, mkangia commented on custom/enikshay/integrations/nikshay/repeater_generator.py
> +            "LabNo": test_case_properties.get('lab_serial_number', 0),
@proteusvacuum Tested this for length constraints for length 5 as highlighted [here](https://docs.google.com/spreadsheets/d/1AdhiHTn9Z47VCGIKXCYL-UXDvV9-aV1d8gRzVYVEh94/edit#gid=609100483). Could submit a lab number `234567891078`, so seems like a false restriction.

2017-02-10 16:26 UTC, proteusvacuum requested changes
Looking good! Couple of comments.

2017-02-10 16:26 UTC, proteusvacuum commented on custom/enikshay/integrations/nikshay/repeater_generator.py
> +        # Simple success message that has {"Nikshay_Message": "Success"...}
Are we sure that every success from Nikshay gives a `200` range response?

2017-02-10 16:26 UTC, proteusvacuum commented on custom/enikshay/integrations/nikshay/repeater_generator.py
> +        except NikshayResponseException as e:
This code as is won't ever raise this exception.

2017-02-10 16:26 UTC, proteusvacuum commented on custom/enikshay/integrations/nikshay/repeater_generator.py
> +        pass
This needs to be added.

2017-02-10 16:26 UTC, proteusvacuum commented on custom/enikshay/integrations/nikshay/repeaters.py
> +from ...case_utils import (
can you use the full path for the import? This syntax always confuses me.

2017-02-10 16:26 UTC, proteusvacuum commented on custom/enikshay/integrations/nikshay/repeaters.py
> +    followup_for_tests = ['end_of_ip', 'end_of_cp', 'posttreatment_6month']
why did you make this a class variable? Would be good to keep consistent with this and the other values you use in the checks.

2017-02-10 16:26 UTC, proteusvacuum commented on custom/enikshay/integrations/nikshay/repeaters.py
> +case_post_save.connect(create_followup_repeat_records, CommCareCaseSQL)
this is going to create 2 repeat records for each case. Did you mean `CommCareCase` here?

2017-02-10 16:26 UTC, proteusvacuum commented on custom/enikshay/integrations/nikshay/urls.py
> +        r'^new_register_patient_repeater$',
the URL here is not correct.

2017-02-10 16:26 UTC, proteusvacuum commented on custom/enikshay/integrations/nikshay/urls.py
> +        r'^new_register_patient_repeater$',
This is the same URL as above.

2017-02-12 11:31 UTC, mkangia commented on custom/enikshay/integrations/nikshay/repeater_generator.py
> +        # Simple success message that has {"Nikshay_Message": "Success"...}
There is only one success message. 
```
{
  "Nikshay_Message": "Success",
  "Results": [
    {
      "FieldName": "Message",
      "Fieldvalue": "Updated"
    }
  ]
}
```
the response is a 202.

2017-02-12 11:40 UTC, mkangia commented on custom/enikshay/integrations/nikshay/repeater_generator.py
> +        pass
Considering updating `hiv_test_nikshay_registered` here on the payload_doc which is a person unless there is specific case(may be, test) that is present for HIV test done.

2017-02-12 11:44 UTC, mkangia commented
Thanks for the review @proteusvacuum. Apologies you had to look at some really silly mistakes there.

2017-02-12 22:45 UTC, dimagimon commented on custom/enikshay/tests/utils.py
> +                    date_tested=datetime(2016,8,6).date(),
E231 missing whitespace after ','

2017-02-13 11:09 UTC, dimagimon commented on custom/enikshay/integrations/nikshay/repeater_generator.py
> +                                        testing_purpose=testing_purpose,
E121 continuation line under-indented for hanging indent

2017-02-13 11:09 UTC, dimagimon commented on custom/enikshay/integrations/nikshay/tests/test_repeaters.py
> +                                        testing_purpose="testing",
E121 continuation line under-indented for hanging indent

2017-02-13 11:09 UTC, dimagimon commented on custom/enikshay/integrations/nikshay/tests/test_repeaters.py
> +                ):
E123 closing bracket does not match indentation of opening bracket's line

2017-02-14 10:43 UTC, mkangia commented
@proteusvacuum @NoahCarnahan Co-ordinating with team for some of the requirements on this. Will update and notify on completion. Please don't review till then.

2017-03-08 10:47 UTC, dimagimon commented
There are 411 errors:

* corehq/apps/accounting/static/accounting/js/accounting.billing_info_handler.js, line 115 - 'form' is defined but never used (no-unused-vars)
* corehq/apps/accounting/static/accounting/js/accounting.subscription_info_handler.js, line 37 - Expected indentation of 8 space characters but found 7. (indent)
* corehq/apps/accounting/static/accounting/js/accounting.subscription_info_handler.js, line 38 - Expected indentation of 8 space characters but found 7. (indent)
* corehq/apps/accounting/static/accounting/js/subscriptions.js, line 10 - Missing semicolon. (semi)
* corehq/apps/app_manager/static/app_manager/js/app_manager.js, line 293 - Missing semicolon. (semi)
* corehq/apps/app_manager/static/app_manager/js/app_summary.ng.js, line 46 - Missing semicolon. (semi)
* corehq/apps/app_manager/static/app_manager/js/app_summary.ng.js, line 53 - Missing semicolon. (semi)
* corehq/apps/app_manager/static/app_manager/js/app_summary.ng.js, line 57 - 'target_lang' is defined but never used (no-unused-vars)
* corehq/apps/app_manager/static/app_manager/js/app_summary.ng.js, line 60 - Missing semicolon. (semi)
* corehq/apps/app_manager/static/app_manager/js/app_summary.ng.js, line 64 - 'target_lang' is defined but never used (no-unused-vars)
* corehq/apps/app_manager/static/app_manager/js/app_summary.ng.js, line 67 - Missing semicolon. (semi)
* corehq/apps/app_manager/static/app_manager/js/apps_base.js, line 2 - 'COMMCAREHQ' is not defined. (no-undef)
* corehq/apps/app_manager/static/app_manager/js/apps_base.js, line 7 - Missing trailing comma. (comma-dangle)
* corehq/apps/app_manager/static/app_manager/js/apps_base.js, line 13 - 'hqLayout' is not defined. (no-undef)
* corehq/apps/app_manager/static/app_manager/js/apps_base.js, line 20 - 'hqLayout' is not defined. (no-undef)
* corehq/apps/app_manager/static/app_manager/js/import_app.js, line 7 - 'formElement' is defined but never used (no-unused-vars)
* corehq/apps/app_manager/static/app_manager/js/import_app.js, line 10 - 'LZW' is not defined. (no-undef)
* corehq/apps/app_manager/static/app_manager/js/managed_app.js, line 4 - 'COMMCAREHQ' is not defined. (no-undef)
* corehq/apps/app_manager/static/app_manager/js/managed_app.js, line 14 - 'langcodeTag' is not defined. (no-undef)
* corehq/apps/app_manager/static/app_manager/js/managed_app.js, line 20 - Expected '===' and instead saw '=='. (eqeqeq)
* corehq/apps/app_manager/static/app_manager/js/managed_app.js, line 47 - Missing trailing comma. (comma-dangle)
* corehq/apps/app_manager/static/app_manager/js/managed_app.js, line 90 - 'gaTrackLink' is not defined. (no-undef)
* corehq/apps/app_manager/static/app_manager/js/managed_app.js, line 93 - 'gaTrackLink' is not defined. (no-undef)
* corehq/apps/app_manager/static/app_manager/js/managed_app.js, line 94 - 'gaTrackLink' is not defined. (no-undef)
* corehq/apps/app_manager/static/app_manager/js/source_files.js, line 13 - Expected '!==' and instead saw '!='. (eqeqeq)
* corehq/apps/app_manager/static/app_manager/js/source_files.js, line 15 - 'version_map' is not defined. (no-undef)
* corehq/apps/app_manager/static/app_manager/js/source_files.js, line 31 - 'version_map' is not defined. (no-undef)
* corehq/apps/app_manager/static/app_manager/js/source_files.js, line 35 - 'version_map' is not defined. (no-undef)
* corehq/apps/app_manager/static/app_manager/js/value-or-none-ui.js, line 2 - 'bindingContext' is defined but never used (no-unused-vars)
* corehq/apps/app_manager/static/app_manager/js/value-or-none-ui.js, line 10 - 'ValueOrNoneUI' is not defined. (no-undef)
* corehq/apps/app_manager/static/app_manager/js/value-or-none-ui.js, line 17 - Missing trailing comma. (comma-dangle)
* corehq/apps/app_manager/static/app_manager/js/vellum_beta/lib/ckeditor/build-config.js, line 1 - Expected linebreaks to be 'LF' but found 'CRLF'. (linebreak-style)
* corehq/apps/app_manager/static/app_manager/js/vellum_beta/lib/ckeditor/build-config.js, line 2 - Expected linebreaks to be 'LF' but found 'CRLF'. (linebreak-style)
* corehq/apps/app_manager/static/app_manager/js/vellum_beta/lib/ckeditor/build-config.js, line 3 - Expected linebreaks to be 'LF' but found 'CRLF'. (linebreak-style)
* corehq/apps/app_manager/static/app_manager/js/vellum_beta/lib/ckeditor/build-config.js, line 4 - Expected linebreaks to be 'LF' but found 'CRLF'. (linebreak-style)
* corehq/apps/app_manager/static/app_manager/js/vellum_beta/lib/ckeditor/build-config.js, line 5 - Expected linebreaks to be 'LF' but found 'CRLF'. (linebreak-style)
* corehq/apps/app_manager/static/app_manager/js/vellum_beta/lib/ckeditor/build-config.js, line 6 - Expected linebreaks to be 'LF' but found 'CRLF'. (linebreak-style)
* corehq/apps/app_manager/static/app_manager/js/vellum_beta/lib/ckeditor/build-config.js, line 7 - Expected linebreaks to be 'LF' but found 'CRLF'. (linebreak-style)
* corehq/apps/app_manager/static/app_manager/js/vellum_beta/lib/ckeditor/build-config.js, line 8 - Expected linebreaks to be 'LF' but found 'CRLF'. (linebreak-style)
* corehq/apps/app_manager/static/app_manager/js/vellum_beta/lib/ckeditor/build-config.js, line 9 - Expected linebreaks to be 'LF' but found 'CRLF'. (linebreak-style)
* corehq/apps/app_manager/static/app_manager/js/vellum_beta/lib/ckeditor/build-config.js, line 10 - Expected linebreaks to be 'LF' but found 'CRLF'. (linebreak-style)
* corehq/apps/app_manager/static/app_manager/js/vellum_beta/lib/ckeditor/build-config.js, line 11 - Expected linebreaks to be 'LF' but found 'CRLF'. (linebreak-style)
* corehq/apps/app_manager/static/app_manager/js/vellum_beta/lib/ckeditor/build-config.js, line 12 - Expected linebreaks to be 'LF' but found 'CRLF'. (linebreak-style)
* corehq/apps/app_manager/static/app_manager/js/vellum_beta/lib/ckeditor/build-config.js, line 13 - Expected linebreaks to be 'LF' but found 'CRLF'. (linebreak-style)
* corehq/apps/app_manager/static/app_manager/js/vellum_beta/lib/ckeditor/build-config.js, line 14 - Expected linebreaks to be 'LF' but found 'CRLF'. (linebreak-style)
* corehq/apps/app_manager/static/app_manager/js/vellum_beta/lib/ckeditor/build-config.js, line 15 - Expected linebreaks to be 'LF' but found 'CRLF'. (linebreak-style)
* corehq/apps/app_manager/static/app_manager/js/vellum_beta/lib/ckeditor/build-config.js, line 16 - Expected linebreaks to be 'LF' but found 'CRLF'. (linebreak-style)
* corehq/apps/app_manager/static/app_manager/js/vellum_beta/lib/ckeditor/build-config.js, line 17 - Expected linebreaks to be 'LF' but found 'CRLF'. (linebreak-style)
* corehq/apps/app_manager/static/app_manager/js/vellum_beta/lib/ckeditor/build-config.js, line 18 - Expected linebreaks to be 'LF' but found 'CRLF'. (linebreak-style)
* corehq/apps/app_manager/static/app_manager/js/vellum_beta/lib/ckeditor/build-config.js, line 19 - Expected linebreaks to be 'LF' but found 'CRLF'. (linebreak-style)
* corehq/apps/app_manager/static/app_manager/js/vellum_beta/lib/ckeditor/build-config.js, line 20 - Expected linebreaks to be 'LF' but found 'CRLF'. (linebreak-style)
* corehq/apps/app_manager/static/app_manager/js/vellum_beta/lib/ckeditor/build-config.js, line 21 - Expected linebreaks to be 'LF' but found 'CRLF'. (linebreak-style)
* corehq/apps/app_manager/static/app_manager/js/vellum_beta/lib/ckeditor/build-config.js, line 22 - Expected linebreaks to be 'LF' but found 'CRLF'. (linebreak-style)
* corehq/apps/app_manager/static/app_manager/js/vellum_beta/lib/ckeditor/build-config.js, line 23 - Expected linebreaks to be 'LF' but found 'CRLF'. (linebreak-style)
* corehq/apps/app_manager/static/app_manager/js/vellum_beta/lib/ckeditor/build-config.js, line 24 - Expected linebreaks to be 'LF' but found 'CRLF'. (linebreak-style)
* corehq/apps/app_manager/static/app_manager/js/vellum_beta/lib/ckeditor/build-config.js, line 25 - Expected linebreaks to be 'LF' but found 'CRLF'. (linebreak-style)
* corehq/apps/app_manager/static/app_manager/js/vellum_beta/lib/ckeditor/build-config.js, line 26 - Expected linebreaks to be 'LF' but [...]

2017-03-08 17:26 UTC, dimagimon commented on custom/enikshay/integrations/nikshay/tests/test_repeaters.py
> +                ):
E123 closing bracket does not match indentation of opening bracket's line

2017-03-12 10:29 UTC, mkangia commented
@NoahCarnahan @proteusvacuum 
I have extracted out changes for HIVTest Api in https://github.com/dimagi/commcare-hq/pull/15340 since this end point is ready but FollowUp is still stuck, So good to at least HIVTest rolled out.

2017-03-12 10:33 UTC, dimagimon commented on custom/enikshay/integrations/nikshay/repeater_generator.py
> +                                            testing_purpose=testing_purpose,
E126 continuation line over-indented for hanging indent

2017-03-16 19:05 UTC, proteusvacuum commented
Should I still look at this one?

2017-03-26 10:34 UTC, dimagimon commented on custom/enikshay/integrations/nikshay/repeater_generator.py
> +from custom.enikshay.case_utils import (
F401 'get_lab_referral_from_test' imported but unused

2017-03-26 12:17 UTC, mkangia commented
Considering the number of conflicts and the changes that have happened since this was touched last i thought it was better to pick up changes and start afresh with #15521 

@proteusvacuum
Critical additions:
1. field for bacilli count changed, added by kriti in app (with inputs from @NoahCarnahan )
2. There was a little back and forth on DMC code not being the actual dmc conducting test but considering this is triggered only for `['microscopy-zn', 'microscopy-fluorescent']`, seems like this was good.
3. With result grade as scanty and bacilli count 0, i have mapped it to positive.

2017-03-26 12:17 UTC, closed without merging

2017-03-28 15:52 UTC, proteusvacuum commented
Cool, thanks @mkangia . 
Did you get sign off on point 3 from requirements?