Coerce location metadata to unicode in fixture
dimagi/commcare-hq pull request #14822
Opened 2017-02-08 18:28 UTC by proteusvacuum

https://github.com/dimagi/commcare-hq/pull/14799#issuecomment-278372147
@czue @emord

2017-02-08 23:22 UTC, esoergel requested changes

2017-02-08 23:22 UTC, esoergel commented on corehq/apps/locations/tests/test_location_fixtures.py
> +                'appeared_in_num_episodes': 2,
Actually he's in 3 episodes...

2017-02-08 23:24 UTC, proteusvacuum commented on corehq/apps/locations/tests/test_location_fixtures.py
> +                'appeared_in_num_episodes': 2,
https://github.com/dimagi/commcare-hq/pull/14822/commits/81665f66885643e9e3c75396ecc2694c3ee271bf

2017-02-08 23:29 UTC, esoergel approved these changes

2017-02-09 05:50 UTC, czue commented on corehq/apps/locations/tests/test_location_fixtures.py
> +                'appeared_in_num_episodes': 2,
thank goodness for code review!

2017-02-09 11:46 UTC, kaapstorm commented
This is probably going to resolve [FB 247293](http://manage.dimagi.com/default.asp?247293) too.

2017-02-09 11:46 UTC, merged