ICDS Branding
dimagi/commcare-hq pull request #14881
Opened 2017-02-13 09:09 UTC by sravfeyn

https://docs.google.com/document/d/1QCUHA7PLvZPspuY23Pn98HIrD4zv_KuakFoJwi1dGiE/edit#

@nickpell @snopoke

2017-02-13 09:11 UTC, sravfeyn commented
Corresponding ansible change https://github.com/dimagi/commcarehq-ansible/commit/96cd91e1498b06dafcb581c7a4fae9ebe3459b00

2017-02-13 09:12 UTC, snopoke requested changes
Looking good so far

2017-02-13 09:12 UTC, snopoke commented on corehq/apps/export/templates/export/partial/export_list_controller.html
> +            Exports are a way to download data from {{ hq_name }}
missing `endblocktrans`

2017-02-13 09:12 UTC, snopoke commented on corehq/util/context_processors.py
> +        'django_settings': settings
I don't think it's a good idea to expose ALL settings here.

2017-02-13 09:28 UTC, sravfeyn commented on corehq/util/context_processors.py
> +        'django_settings': settings
Why is this bad?

2017-02-13 09:57 UTC, snopoke commented on corehq/util/context_processors.py
> +        'django_settings': settings
It just makes it easier to expose secrets to the world. A typo that got missed in code review could put our entire settings dict into a template. Best to be explicit about what templates should have access to.

2017-02-21 11:16 UTC, sravfeyn commented
@snopoke Updated. Except for 1,2,3 and 5 in the spec, everything else is implemented.

2017-02-21 13:48 UTC, merged