A wild stab in the dark
dimagi/commcare-hq pull request #14983
Opened 2017-02-15 09:53 UTC by kaapstorm

Opening for sake of discussion. Untested. 

Context: [FB 246992](http://manage.dimagi.com/default.asp?246992)
TL;DR: The first index in the XPath in a case list detail field template is relative: 
```xml
    <xpath function="instance('casedb')/casedb/case[
        @case_id=instance('casedb')/casedb/case[
            @case_id=index/host
        ]/index/host
    ]/case_name"/>
```
but it should be absolute:
```xml
    <xpath function="instance('casedb')/casedb/case[
        @case_id=instance('casedb')/casedb/case[
            @case_id=current()/index/host
        ]/index/host
    ]/case_name"/>
```

@snopoke cc @benrudolph @czue

2017-02-15 10:09 UTC, snopoke commented on corehq/apps/app_manager/detail_screen.py
> +        if property == '#owner_name' or self.is_case_list_column:
could you not just say `use_relative = bool(indexes) or property != '#owner_name'`

2017-02-15 11:39 UTC, snopoke commented
yes, sorry, `not indexes`. I'm pretty sure what Clayton was saying is that
the first index query for ALL indexed details queries should use `current()`

2017-02-15 14:02 UTC, snopoke commented
Pretty sure this will break tests

2017-02-15 14:04 UTC, kaapstorm commented
:open_mouth: It didn't when I ran app_manager tests locally. So I'm adding a test.

2017-02-18 15:25 UTC, czue commented
what's the status of this PR?

2017-02-20 08:37 UTC, kaapstorm commented
I think it's good to go. What do you reckon, @snopoke ?

2017-02-20 10:08 UTC, snopoke requested changes
minor changes

2017-02-20 10:08 UTC, snopoke commented on corehq/apps/app_manager/tests/test_case_list_form.py
> +                field='house/case_name',  # Include a parent case property in the case list
Although this is technically legal I'd prefer if we stuck to the normal references and made this `parent/case_name`

2017-02-20 10:08 UTC, snopoke commented on corehq/apps/app_manager/detail_screen.py
> +        use_relative = not indexes and property != '#owner_name'
I think this would be easier to read if it was inverted:
```python
use_absolute = indexes or property == '#owner_name'
```

2017-02-21 07:30 UTC, kaapstorm commented on corehq/apps/app_manager/detail_screen.py
> +        use_relative = not indexes and property != '#owner_name'
Agreed

2017-02-21 08:57 UTC, merged

2017-02-21 16:00 UTC, czue commented
thanks for powering through this!