Include export name in sheet names for bulk exports
dimagi/commcare-hq pull request #15145
Opened 2017-02-24 18:19 UTC by NoahCarnahan

Addresses: http://manage.dimagi.com/default.asp?247678

Makes it easier to figure out which sheets correspond to which exports, otherwise they will just be named "Forms1", "Forms2", etc.

2017-02-24 18:19 UTC, NoahCarnahan commented
@benrudolph cc @kaapstorm

2017-02-24 18:19 UTC, dimagimon commented on corehq/apps/export/export.py
> +                    sheet_name = table.label or "Sheet{}".format(table_index+1)
E226 missing whitespace around arithmetic operator

2017-02-24 18:19 UTC, dimagimon commented on corehq/apps/export/export.py
> +                            instance.name or "Export{}".format(instance_index+1),
E226 missing whitespace around arithmetic operator

2017-02-24 21:07 UTC, emord commented on corehq/apps/export/export.py
> +                        sheet_name = "{}-{}".format(
Does this need to be truncated?

2017-02-24 21:08 UTC, NoahCarnahan commented on corehq/apps/export/export.py
> +                        sheet_name = "{}-{}".format(
It gets truncated later (somewhere in `self.writer.open(headers, file, table_titles=table_titles, archive_basepath=name)`)

2017-02-24 21:08 UTC, emord approved these changes

2017-02-26 20:02 UTC, benrudolph commented on corehq/apps/export/export.py
> +                        sheet_name = "{}-{}".format(
i think this'll fail for unicode export names (which i think is fairly common)

2017-02-26 20:03 UTC, benrudolph requested changes
looks fine, just think the unicode thing should be updated before merged

2017-02-26 20:25 UTC, NoahCarnahan commented on corehq/apps/export/export.py
> +                        sheet_name = "{}-{}".format(
Good catch thanks

2017-02-27 07:35 UTC, benrudolph approved these changes
👢 🚧

2017-02-27 13:45 UTC, merged