don't let raise_conflicting_dates go off against a canceled subscription
dimagi/commcare-hq pull request #15144
Opened 2017-02-24 16:57 UTC by nickpell

http://manage.dimagi.com/default.asp?248270

@esoergel @biyeun

2017-02-24 19:00 UTC, esoergel requested changes

2017-02-24 19:00 UTC, esoergel commented on corehq/apps/accounting/models.py
> +            CONSISTENT_DATES_CHECK,
I think this should be `filter`, not `exclude`

2017-02-24 23:37 UTC, nickpell commented on corehq/apps/accounting/models.py
> +            CONSISTENT_DATES_CHECK,
updated

2017-02-27 15:21 UTC, esoergel approved these changes

2017-02-27 15:21 UTC, merged