Mk 248129 Notify Daily Saved Exports Change
dimagi/commcare-hq pull request #15158
Opened 2017-02-27 13:23 UTC by mkangia

2017-02-27 13:30 UTC, mkangia commented
@NoahCarnahan Considering you would know the best for whats needed here to ensure this renders only for domains that have access to Daily Saved Exports and Export Dashboard Integration.
For now have added just domain privileges check for both. Thats sufficient right?
Also if you have any feedback for changes.

2017-02-27 16:00 UTC, NoahCarnahan requested changes

2017-02-27 16:00 UTC, NoahCarnahan commented on corehq/apps/export/views.py
> +        if domain_has_daily_saved_export_access(self.domain) or domain_has_excel_dashboard_access(self.domain):
I think you also want to do this check:
https://github.com/dimagi/commcare-hq/blob/2d42bbf3088f7ac1ec7a881df1f7f4d27ca5909c/corehq/apps/export/views.py#L1511

2017-02-27 16:00 UTC, NoahCarnahan commented on corehq/apps/export/views.py
> +            self.request.session['notify_new_daily_saved_export'] = False
I don't think it's a great user experience for the modal to show on every new session. I think it should be a one-time thing. I know it's a bit more work, but I think the "read" status of the notification should reside somewhere in permanent storage. You could look at the [`corehq.apps.notifications.models.Notification`](https://github.com/dimagi/commcare-hq/blob/2d42bbf3088f7ac1ec7a881df1f7f4d27ca5909c/corehq/apps/notifications/models.py#L20) model might provide some inspiration.

2017-03-09 09:34 UTC, dimagimon commented on corehq/apps/export/views.py
> +                )):
E123 closing bracket does not match indentation of opening bracket's line

2017-03-09 10:52 UTC, dimagimon commented on corehq/apps/export/views.py
> +                ):
E123 closing bracket does not match indentation of opening bracket's line

2017-03-09 12:46 UTC, NoahCarnahan approved these changes
Looks good!

2017-03-09 13:33 UTC, mkangia commented
@NoahCarnahan thanks for the review. Just added one more [change](https://github.com/dimagi/commcare-hq/pull/15158/commits/c2fd9c030c46ca193cf750ab7d5d46cb8cbd8f97) to check that user joined before the feature release. I have just added a random date for now. 
Do you know the exact date to be checked against? Also pinging kevin for the same on ticket.

2017-03-09 14:16 UTC, NoahCarnahan commented on corehq/apps/export/models/new.py
> +        return user_added_on < datetime(2016, 2, 1)
I think `datetime(2017, 1, 25)` is when it was released.

2017-03-09 15:38 UTC, NoahCarnahan commented
Looks good thanks. Ok to merge? (I see the "hold off on merge" tag is still on the PR)

2017-03-09 15:46 UTC, mkangia commented
@NoahCarnahan just keeping some time if any feedback by UX team or kevin. Will merge in a while then but before todays deploy

2017-03-09 15:49 UTC, NoahCarnahan commented
👍

2017-03-09 17:08 UTC, orangejenny commented
Hi Manish, ux feedback: Could this be an `alert-warning` box instead, in or right above the Exports panel, instead of a modal? A modal seems too in-your-face to me, especially since it looks like users will see this modal every time they visit the page. Modals are more for blocking issues, things the user *has* to deal with. Someone who's looking for their daily saved exports will already be scanning the page. 

One other minor thing: making `Daily Saved Exports` and `Excel Dashboard Integration` text into links would be a nice touch.

2017-03-09 17:26 UTC, mkangia commented
@orangejenny the users would see this only once and also only for domains that were moved to new daily saved export. Happy to change this if you think it should be still done.

2017-03-09 18:17 UTC, orangejenny commented
Hey, if they'll only see it once, and it's limited to people who actually have daily saved exports (which it looks like it is), then it works for me.

Curious, how are we going to decide when to remove this code?

2017-03-09 19:00 UTC, mkangia commented
Thanks @orangejenny. since its just as a notification for very few users hence keeping effort low.

As of now the plan is to remove this post march. By that time we are hoping all would know. Also we are storing when the notification is viewed. So we can always check how many users saw this. Also, I think we have an idea about how many domains were moved to this new export. So we can tally if thats available @NoahCarnahan.

2017-03-09 19:02 UTC, merged

2017-03-09 19:23 UTC, orangejenny commented
Cool, thanks for the explanation!