Highlight feature flags for debugging help in App Manager
dimagi/commcare-hq pull request #15332
Opened 2017-03-10 20:34 UTC by biyeun

- tags are only visible if the flag `Highlight / Mark Feature Flags in UI` is enabled
- not meant to look pretty, just for debugging between v2 and v1

<img width="879" alt="screen shot 2017-03-10 at 3 32 41 pm" src="https://cloud.githubusercontent.com/assets/716573/23812094/0470ff8c-05a7-11e7-9c0b-82e2a6d5969e.png">

@orangejenny 
cc @benrudolph

2017-03-10 20:35 UTC, dimagimon commented on corehq/apps/hqwebapp/templatetags/hq_shared_tags.py
> +@register.filter
E302 expected 2 blank lines, found 1

2017-03-10 20:35 UTC, dimagimon commented on corehq/apps/hqwebapp/templatetags/hq_shared_tags.py
> +    return mark_safe("""<div class="label label-{css_class} label-flag{css_disabled}">{tag_name}: {description}{status}</div>""".format(
E501 line too long (136 > 115 characters)

2017-03-10 20:35 UTC, dimagimon commented on corehq/toggles.py
> +
W391 blank line at end of file

2017-03-11 00:36 UTC, orangejenny commented on corehq/apps/app_manager/templates/app_manager/v1/partials/case_list.html
> +{{ request|toggle_tag_info:"FIXTURE_CASE_SELECTION" }}
Why is this here twice?

2017-03-11 00:37 UTC, orangejenny commented on corehq/apps/app_manager/templates/app_manager/v2/partials/case_list.html
> +                            {% elif request|toggle_enabmed:'SHOW_DEV_TOGGLE_INFO' %}
typo in `toggle_enabmed`

2017-03-11 00:37 UTC, orangejenny commented on corehq/apps/app_manager/templates/app_manager/v2/partials/case_list.html
> +                            {% elif request|toggle_enabmed:'SHOW_DEV_TOGGLE_INFO' %}
typo in `toggle_enabmed`

2017-03-11 00:38 UTC, biyeun commented on corehq/apps/app_manager/templates/app_manager/v2/partials/case_list.html
> +                            {% elif request|toggle_enabmed:'SHOW_DEV_TOGGLE_INFO' %}
yikes. thanks

2017-03-11 00:40 UTC, biyeun commented on corehq/apps/app_manager/templates/app_manager/v1/partials/case_list.html
> +{{ request|toggle_tag_info:"FIXTURE_CASE_SELECTION" }}
typo. thanks

2017-03-11 00:40 UTC, orangejenny commented on corehq/toggles.py
> +TAG_DEV_TOOLS = Tag(
Nit, but `TAG_ONE_OFF` seems fine to use here and sufficient to warn people away from turning this on.

2017-03-11 00:41 UTC, orangejenny commented on corehq/apps/app_manager/templates/app_manager/v1/partials/add_property_button.html
> -        {% if request|toggle_enabled:'GRAPH_CREATION' %}
Why was this `if` removed?

2017-03-11 00:41 UTC, orangejenny requested changes
Just a couple of small things to address.

2017-03-11 00:42 UTC, biyeun commented on corehq/apps/app_manager/templates/app_manager/v1/partials/add_property_button.html
> -        {% if request|toggle_enabled:'GRAPH_CREATION' %}
it's inside an if with the same criteria

2017-03-11 00:46 UTC, dimagimon commented on corehq/toggles.py
> +
W391 blank line at end of file

2017-03-11 01:02 UTC, biyeun commented
@orangejenny responded

2017-03-11 01:18 UTC, orangejenny approved these changes

2017-03-13 07:12 UTC, benrudolph reviewed
very cool, didn't review closely because it looks like jenny is taking a look

2017-03-13 10:39 UTC, snopoke commented on corehq/apps/hqwebapp/templatetags/hq_shared_tags.py
> +    if not toggles.SHOW_DEV_TOGGLE_INFO.enabled_for_request(request):
this toggle is so meta, love it

2017-03-13 12:41 UTC, merged