set nikshay id on person case instead of episode case on patient regi…
dimagi/commcare-hq pull request #15382
Opened 2017-03-15 16:58 UTC by mkangia

…stration

2017-03-16 16:00 UTC, nickpell approved these changes

2017-03-16 17:13 UTC, NoahCarnahan approved these changes
Looks ok to me

2017-03-16 17:39 UTC, proteusvacuum requested changes
what's the rationale behind this? in the app we store Nikshay id on the episode. If you were to update the Nikshay ID in the app, it would conflict with the one on the person case that comes from Nikshay.

2017-03-21 13:56 UTC, mkangia commented
Closing this as this is not needed.

> Nikshay id always is on episode case.

2017-03-21 13:56 UTC, closed without merging