send timestamp metric to datadog
dimagi/commcare-hq pull request #15544
Opened 2017-03-28 07:23 UTC by sravfeyn

2017-03-28 07:34 UTC, snopoke requested changes

2017-03-28 07:34 UTC, snopoke commented on corehq/ex-submodules/pillowtop/pillow/interface.py
> +                u'publist_timestamp:{}'.format(change.metadata.publish_timestamp),
This won't work - you need a new guage metric which records the timestamp as an epoch

2017-03-28 12:48 UTC, sravfeyn commented
@snopoke Updated

2017-03-28 13:55 UTC, snopoke requested changes

2017-03-28 13:55 UTC, snopoke commented on corehq/ex-submodules/pillowtop/pillow/interface.py
> +            datadog_gauge('commcare.change_feed.change_lag', change_lag, tags=tags)
I don't think all these tags make sense for this metric. I think we could limit it to:
* pillow_name
* topic

I think you may have to add the topic to the change though. You can add it here: https://github.com/dimagi/commcare-hq/blob/be5c8ce9ea6f9cf1c16894570505172911ccbb7c/corehq/apps/change_feed/consumer/feed.py#L179
```
topic = message.topic
```

2017-03-29 09:11 UTC, sravfeyn commented on corehq/ex-submodules/pillowtop/pillow/interface.py
> +            datadog_gauge('commcare.change_feed.change_lag', change_lag, tags=tags)
https://github.com/dimagi/commcare-hq/pull/15544/commits/33f627431237443bdc2b4a45aa35f8d6925e2d67

2017-03-29 09:41 UTC, snopoke requested changes

2017-03-29 09:41 UTC, snopoke commented on corehq/apps/change_feed/consumer/feed.py
> +        topic=message.topic,
You'll need to add this kwarg to the `Change` class as well

2017-03-29 10:16 UTC, sravfeyn commented on corehq/apps/change_feed/consumer/feed.py
> +        topic=message.topic,
Sorry, thought it was already there

Updated now

2017-03-29 10:20 UTC, snopoke approved these changes

2017-03-31 05:46 UTC, merged

2017-03-31 05:46 UTC, sravfeyn commented
Is there anything else needed to be done on datadog UI for this metric to reflect there?

2017-03-31 08:03 UTC, snopoke commented
@sravfeyn you'll need to add a graph to see the data but you don't have to do anything for it to be collected