ICDS: Update case history expression and data sources
dimagi/commcare-hq pull request #15551
Opened 2017-03-28 18:44 UTC by sheelio

@emord 

Updated the data sources and also changed your case history expression slightly.

2017-03-28 18:56 UTC, emord requested changes

2017-03-28 18:56 UTC, emord commented on custom/icds_reports/ucr/expressions.py
> +    if spec['xmlns'] is not None and len(spec['xmlns']) > 0:
I think this can just be `if spec['xmlns']`

2017-03-28 18:56 UTC, emord commented on custom/icds_reports/ucr/data_sources/ccs_record_cases_monthly_tableau.json
> +          "type": "icds_get_case_forms_in_date",
This needs a `case_id_expression`. Can either add it here or make it not required in ucr/expressions

2017-03-28 19:49 UTC, emord commented
@sheelio I added https://github.com/dimagi/commcare-hq/pull/15551/commits/fb6baae7434fd5f3318be06329a5a270a9d94831 I used from_date_expression/to_date_expression as that was the terminology used in the core ucr code.

There's still an issue with your refactor to `nutrition_status_last_recorded` and `current_month_nutrition_status` that causes tests to fail. It looks like a great simplification but not sure I have enough context to debug that. I tried reverting those two changes and the tests pass, so I think that's all that's blocking this PR

2017-03-29 16:13 UTC, emord approved these changes

2017-03-29 16:14 UTC, emord commented
@sheelio I added https://github.com/dimagi/commcare-hq/pull/15551/commits/445296a2f3d9f0ba988de88cf8b6f6b3d15d3137 I decided to rely on get_case_forms cache because this class was mostly a pass through for the json. In between  runs the start_date and end_date that are passed here are the same `{end_date: icds_month_end}` which didn't look as easy to refactor

2017-03-29 17:53 UTC, sheelio commented
Awesome thanks!

2017-03-29 18:01 UTC, merged