Auto Case Update Refactor
dimagi/commcare-hq pull request #15680
Opened 2017-04-07 17:22 UTC by gcapalbo

Details here:
https://docs.google.com/document/d/1M3OWqYyTQKBGvB_xEmkB9bsTH1ZvCGNXqIs3nvRQxR0/edit#

Demo here:
https://staging.commcarehq.org/a/gc-staging/data/edit/automatic_updates/

buddy @mkangia 
cc @calellowitz for updates to rule running processes (this extends the work you had done)

2017-04-07 17:23 UTC, dimagimon commented on corehq/apps/data_interfaces/static/data_interfaces/js/case_rule_actions.js
> +var CaseRuleActions = function(initial) {
'CaseRuleActions' is defined but never used (no-unused-vars)

2017-04-07 17:23 UTC, dimagimon commented on corehq/apps/data_interfaces/static/data_interfaces/js/case_rule_actions.js
> +    var self = this;
'self' is defined but never used (no-unused-vars)

2017-04-07 17:23 UTC, dimagimon commented on corehq/apps/data_interfaces/static/data_interfaces/js/case_rule_criteria.js
> +var CaseRuleCriteria = function(initial, constants) {
'CaseRuleCriteria' is defined but never used (no-unused-vars)

2017-04-07 17:23 UTC, dimagimon commented on corehq/apps/data_interfaces/static/data_interfaces/js/case_rule_criteria.js
> +                var obj;
'obj' is already defined (no-redeclare)

2017-04-07 17:23 UTC, gcapalbo commented
fine to review, but i want to add tests before merging

2017-04-12 09:25 UTC, mkangia approved these changes
I don't have any context on this and would take quite a lot of digging in. Will defer to @calellowitz  for review or if you want to add some more reviewers @gcapalbo

2017-04-12 20:11 UTC, calellowitz requested changes
left one real change request, hopefully it came through and isnt lost to an old diff

2017-04-12 20:11 UTC, calellowitz commented on corehq/apps/data_interfaces/templates/data_interfaces/edit_case_rule.html
> +        custom_action_definitions: {{ actions_form.custom_action_definitions.value|default:"[]"|safe }},
same comment as above

2017-04-12 20:12 UTC, calellowitz commented
Looks good besides the one comment, though admittedly it was large enough of a PR that I was not able to read every part super closely. Let me know if github hides the comment since you ended up modifying the section i made it on.

2017-04-21 11:59 UTC, dimagimon commented
There are 5 errors:

* corehq/apps/data_interfaces/models.py, line 956 - F821 undefined name 'domain'
* corehq/apps/data_interfaces/models.py, line 964 - F821 undefined name 'since'
* corehq/apps/data_interfaces/models.py, line 982 - F821 undefined name 'FormAccessors'
* corehq/apps/data_interfaces/models.py, line 985 - F821 undefined name 'instance'
* corehq/apps/data_interfaces/tests/test_case_rule_migration.py, line 1 - F401 'json' imported but unused

2017-04-21 12:46 UTC, dimagimon commented on corehq/apps/data_interfaces/tests/test_case_rule_migration.py
> +import json
F401 'json' imported but unused

2017-04-25 00:39 UTC, dimagimon commented on corehq/apps/data_interfaces/static/data_interfaces/js/case_rule.js
> +        $("#rule-definition-form").submit(function(event) {
'event' is defined but never used (no-unused-vars)

2017-04-25 00:39 UTC, dimagimon commented on corehq/apps/data_interfaces/static/data_interfaces/js/case_rule_actions.js
> +        var self = this;
'self' is defined but never used (no-unused-vars)

2017-04-25 00:39 UTC, dimagimon commented on corehq/apps/data_interfaces/static/data_interfaces/js/case_rule_actions.js
> +    }
Missing semicolon. (semi)

2017-04-25 00:39 UTC, dimagimon commented on corehq/apps/data_interfaces/static/data_interfaces/js/case_rule_criteria.js
> +    }
Missing semicolon. (semi)

2017-04-26 11:40 UTC, dimagimon commented on corehq/apps/data_interfaces/tests/test_auto_case_updates.py
> +    @run_with_all_backends
F811 redefinition of unused 'test_case_property_equal' from line 619

2017-04-27 15:57 UTC, dimagimon commented on corehq/apps/data_interfaces/tests/test_auto_case_updates.py
> +        rule4 = _create_empty_rule(self.domain, case_type='person-2', active=False)
F841 local variable 'rule4' is assigned to but never used

2017-04-27 15:57 UTC, dimagimon commented on corehq/apps/data_interfaces/tests/test_auto_case_updates.py
> +        rule5 = _create_empty_rule(self.domain, case_type='person-3', deleted=True)
F841 local variable 'rule5' is assigned to but never used

2017-04-27 15:57 UTC, dimagimon commented on corehq/apps/data_interfaces/tests/test_auto_case_updates.py
> +        rule4 = _create_empty_rule(self.domain, case_type='person-2')
F841 local variable 'rule4' is assigned to but never used

2017-05-09 00:25 UTC, gcapalbo commented
@calellowitz I externalized all the js and added some more tests - this should be good to go now.

(Leaving the don't merge label just so it doesn't get accidentally deployed overnight or something)

2017-05-09 11:47 UTC, calellowitz approved these changes

2017-05-09 11:47 UTC, merged