App Manager V2: Hide Case Settings in survey module
dimagi/commcare-hq pull request #15937
Opened 2017-04-27 21:13 UTC by biyeun

@orangejenny // buddy @kaapstorm 

fixes https://manage.dimagi.com/default.asp?252950#1324073

2017-04-27 21:30 UTC, orangejenny requested changes
This looks like it's going to hide a bunch of legitimate settings from survey modules: parent module, source module, menu mode, etc.

2017-04-28 15:54 UTC, biyeun commented
@orangejenny so maybe what needs to happen if parent, source, and menu module are not showing up, hide the div. I think the issue in the ticket was it was just an empty panel

2017-04-28 17:14 UTC, orangejenny commented
Yeah, the panel needs to be hidden if nothing is inside of it, some kind of {% if not shadow and not child and and not advanced_app_builder ... blah blah %}

2017-05-04 17:14 UTC, biyeun commented
@orangejenny  responded to your feedback btw

2017-05-04 22:45 UTC, orangejenny requested changes

2017-05-04 22:45 UTC, orangejenny commented on corehq/apps/app_manager/templates/app_manager/v2/partials/module_view_settings.html
> +          {% if child_module_enabled or module.module_type == 'shadow' or app.advanced_app_builder or module.put_in_root or app.grid_display_for_some_modules or value or ko_value or not module.is_sur
I think instead of `value or ko_value` you want to check for `module.module_filter`

2017-05-11 19:04 UTC, biyeun commented
@orangejenny hey responded btw

2017-05-11 21:17 UTC, orangejenny approved these changes

2017-05-11 21:17 UTC, merged