fix async restore
dimagi/commcare-hq pull request #15942
Opened 2017-04-28 14:54 UTC by dannyroberts

@benrudolph agrees this looks like just a typo—
self.payload is a file and we wouldn't expect it to respond to
`.get_content_length()`, whereas self has a specific method defined for
that (`get_content_length`)

2017-04-28 14:55 UTC, dannyroberts commented
@snopoke @kaapstorm cc: @orangejenny, @amstone326

2017-04-28 14:58 UTC, benrudolph commented
thank you danny!

2017-04-28 15:07 UTC, orangejenny approved these changes

2017-04-28 18:38 UTC, kaapstorm commented on corehq/ex-submodules/casexml/apps/phone/restore.py
>          return stream_response(self.payload.as_file(), headers)
Shouldn't this be `self.as_file()` then?

2017-04-28 18:47 UTC, kaapstorm requested changes
This makes sense. But should `self.payload.as_file()` in line 391 then be `self.as_file()` if `self.payload` is potentially a file?

2017-04-28 19:38 UTC, dannyroberts commented on corehq/ex-submodules/casexml/apps/phone/restore.py
>          return stream_response(self.payload.as_file(), headers)
Yeah I think you're right. And `self.as_file()` is now just `self.payload` (Actually it's defined twice but I think the second time is a mistake.)

2017-04-28 21:48 UTC, merged

2017-05-01 14:52 UTC, proteusvacuum commented
I'm a bit confused. Does this mean that this code never worked and that particular code path was never hit? Or did the recent change to the restore change the way this was reacting?