ReportConfigs might use old slug
dimagi/commcare-hq pull request #16063
Opened 2017-05-09 11:21 UTC by kaapstorm

Context: [FB 251023](https://manage.dimagi.com/default.asp?251023)

Saved or e-mailed reports use ReportConfig instances that store their filters keyed by old slugs. This allows the Application Status report to accept users specified with either the new or the old slug. (Changing the filter will use the new slug.)

@mkangia @calellowitz

2017-05-09 11:52 UTC, kaapstorm commented
@calellowitz I'm not sure of the implications of this change. An alternative would be to migrate ReportConfigs that have an "emw" filter to "location_restricted_mobile_worker" filter instead.

2017-05-09 13:22 UTC, mkangia commented
Would be nice to update the reports instead of adding support for old filter unless you are trying to avoid it for some reason.

2017-05-16 12:02 UTC, mkangia requested changes
@kaapstorm Are you thinking of revisiting this?

2017-05-17 09:54 UTC, kaapstorm commented
Hey @mkangia. I've added a soft-migrate to change existing ReportConfigs from using `ExpandedMobileWorkerFilter` ("emw") filter to `LocationRestrictedMobileWorkerFilter` ("location_restricted_mobile_worker") filter instead. But I haven't tested this yet.

2017-05-17 09:56 UTC, kaapstorm commented on corehq/apps/reports/models.py
> +        except AttributeError:
(Catching `AttributeError` because parent `wrap()` method may not be found by method resolution.)

2017-11-10 12:24 UTC, closed without merging