add Subscription.get_active_subscription_by_domain()
dimagi/commcare-hq pull request #16111
Opened 2017-05-11 17:30 UTC by nickpell

This is the second half to https://github.com/dimagi/commcare-hq/pull/15852 (wanted to wait one invoicing period to make sure nothing unexpectedly broke).

Since we can now know that there is at most one active subscription per domain, we're able to clean up the query to find a domain's active subscription (https://github.com/dimagi/commcare-hq/commit/39188fd4f0b3e45922649b67365bfb1485981b42).

@orangejenny

2017-05-12 00:12 UTC, orangejenny commented on corehq/apps/accounting/models.py
> +        else:
nitpick, but this doesn't need to be inside an `else`

2017-05-12 00:12 UTC, orangejenny commented on corehq/apps/accounting/models.py
> +            else:
same here

2017-05-12 00:19 UTC, orangejenny commented on corehq/apps/api/domain_metadata.py
> +            "plan_version": subscription.plan_version,
is it guaranteed that `subscription` won't be `None` here?

2017-05-12 00:22 UTC, orangejenny commented on corehq/apps/domain/views.py
> +        plan_version = subscription.plan_version
This should probably check for `subscription` being `None` (there are similar checks in this function)

2017-05-12 00:23 UTC, orangejenny commented on corehq/apps/accounting/models.py
> +        Returns SoftwarePlanVersion for the given domain.
so much nicer!

2017-05-12 00:24 UTC, orangejenny commented on corehq/apps/userreports/views.py
> +        return Subscription.get_subscribed_plan_by_domain(self.domain).plan.name
should this check for `None`?

2017-05-12 00:25 UTC, orangejenny requested changes
There are a couple of places where it looks like you should check for `None`. Otherwise looks good.

2017-05-19 22:07 UTC, nickpell commented on corehq/apps/api/domain_metadata.py
> +            "plan_version": subscription.plan_version,
updated

2017-05-19 22:07 UTC, nickpell commented on corehq/apps/domain/views.py
> +        plan_version = subscription.plan_version
updated

2017-05-19 22:07 UTC, nickpell commented on corehq/apps/userreports/views.py
> +        return Subscription.get_subscribed_plan_by_domain(self.domain).plan.name
```get_subscribed_plan_by_domain``` won't return ```None```, so this one is all set

2017-05-19 22:10 UTC, nickpell commented
updated ```None``` checks

2017-05-22 13:33 UTC, orangejenny commented
New code looks good, but test failure looks real:
```
File "/mnt/commcare-hq-ro/corehq/apps/users/util.py", line 175, in can_add_extra_mobile_workers
    user_limit = request.plan.user_limit
AttributeError: 'WSGIRequest' object has no attribute 'plan'```

2017-05-22 17:05 UTC, nickpell commented
✅

2017-05-22 17:39 UTC, orangejenny approved these changes

2017-05-22 17:39 UTC, merged