Added Worker Activity Report
dimagi/commcare-hq pull request #16180
Opened 2017-05-16 13:11 UTC by kkrampa

@benrudolph @snopoke @sheelio 
http://manage.dimagi.com/default.asp?252766

2017-05-16 13:45 UTC, snopoke requested changes
This report will need to be paginated since it's going to be used to report on 100k users.

2017-05-16 13:45 UTC, snopoke commented on custom/enikshay/reports/worker_activity.py
> +        avg_submissions_by_user = get_submission_counts_by_user(self.domain, self.avg_datespan)
Running these queries over the whole domain is going to be prohibitively expensive. You should add in the `user_ids` kwarg to limit it to only those users being displayed.

2017-05-17 06:39 UTC, kkrampa commented
@snopoke updated

2017-05-17 07:05 UTC, benrudolph commented on custom/enikshay/reports/worker_activity.py
> +        location_ids = self.locations_id
nit: weird that this is called `location_id` and then you set it to var called `location_ids`

2017-05-17 07:05 UTC, benrudolph commented on custom/enikshay/reports/worker_activity.py
> +                .sort('username', desc=self.pagination.desc)
guessing this report will have to be able to be sorted on other columns. not a super easy way to do that at the moment

2017-05-17 07:47 UTC, snopoke approved these changes
pending Ben's comment on variable name

2017-05-17 07:47 UTC, snopoke commented on custom/enikshay/reports/worker_activity.py
> +                .sort('username', desc=self.pagination.desc)
I don't think you could sort on anything other than username and still do performant pagination since ES doesn't support pagination on aggregations.

2017-05-17 07:55 UTC, kkrampa commented
@snopoke @benrudolph Updated

2017-05-17 08:17 UTC, benrudolph commented on custom/enikshay/reports/worker_activity.py
> +                .sort('username', desc=self.pagination.desc)
i agree, just flagging that this most likely won't be that useful to the team once they have thousands of users

2017-05-17 08:18 UTC, benrudolph commented on custom/enikshay/reports/worker_activity.py
> +                .sort('username', desc=self.pagination.desc)
they can always filter the results down by a lot though

2017-05-17 08:38 UTC, snopoke commented on custom/enikshay/reports/worker_activity.py
> +                .sort('username', desc=self.pagination.desc)
One approach could be to check the total number of users selected and if it's below some threshold then we just pull all the data for those users and sort in python.

2017-05-17 08:39 UTC, merged