don't 500, 404
dimagi/commcare-hq pull request #16571
Opened 2017-06-12 09:42 UTC by sravfeyn

http://manage.dimagi.com/default.asp?255970#edit_0_255970

2017-06-12 09:51 UTC, snopoke requested changes

2017-06-12 09:51 UTC, snopoke commented on custom/enikshay/reports/historical_adherence.py
> +        except:
This should only catch `CaseNotFound`

2017-06-12 09:55 UTC, sravfeyn commented on custom/enikshay/reports/historical_adherence.py
> +        except:
Yeah, just updated

2017-06-14 06:12 UTC, sravfeyn commented
Updated

2017-06-14 08:05 UTC, merged