ENikshay model migration: episode facility id migrations
dimagi/commcare-hq pull request #16664
Opened 2017-06-16 05:05 UTC by proteusvacuum

https://docs.google.com/document/d/1w6T1ShTdZCB1UZjogckh1uBUYynMUOY-OfOi5d4IFt8/edit#

This ended up being much harder than I had expected... We don't have a good way of saying "get this case property at this date", so I had to hack it a little. 

This should only get run once per case, only if the case doesn't already have the property we are looking for.
This task will get deleted at some point, after everyone updates their apps to the latest version, which sets this property automatically... 😈 

buddy @snopoke  (also, if you can think of a better way of doing this, I'm all 👂 )
@sravfeyn

2017-06-16 05:53 UTC, sravfeyn commented on custom/enikshay/tasks.py
> +                episode_facility_id_migration = EpisodeFacilityIDMigration(self.domain, episode)
Isn't this a one time migration, why not put this in a management command instead of a periodic task that repeats?

2017-06-16 06:00 UTC, sravfeyn commented on custom/enikshay/model_migration_sets/episode_facility_id_migration.py
> +                'facility_id_migration_complete': 'true',
Will this not repeatedly submit this update for cases that already have this?

2017-06-16 06:27 UTC, sravfeyn commented on custom/enikshay/model_migration_sets/episode_facility_id_migration.py
> +    def get_owner_id_at_date(self, date):
docstrings will be useful in future when deciphering specs like these.

2017-06-19 09:46 UTC, snopoke requested changes
I don't see a better way of doing this but it's going to be slow and put quite a bit of load on riak.

2017-06-19 09:46 UTC, snopoke commented on custom/enikshay/model_migration_sets/episode_facility_id_migration.py
> +                'facility_id_migration_complete': 'true',
agree this logic should change to make the migration idempotent

2017-06-21 21:19 UTC, proteusvacuum commented
✅

2017-06-21 21:36 UTC, proteusvacuum commented
✅

2017-06-22 06:45 UTC, sravfeyn commented on custom/enikshay/tasks.py
> +                episode_facility_id_migration = EpisodeFacilityIDMigration(self.domain, episode)
Hey @proteusvacuum this is still unclear to me

2017-06-22 09:15 UTC, snopoke approved these changes

2017-06-22 09:16 UTC, merged

2017-06-22 13:11 UTC, proteusvacuum commented on custom/enikshay/tasks.py
> +                episode_facility_id_migration = EpisodeFacilityIDMigration(self.domain, episode)
because users won't all migrate to the new app version at the same time, so cases without these case properties will still get created.