pick inline detail from same module as persistent case tiles
dimagi/commcare-hq pull request #16690
Opened 2017-06-17 16:45 UTC by mkangia

2017-06-19 09:30 UTC, snopoke requested changes

2017-06-19 09:30 UTC, snopoke commented on corehq/apps/app_manager/tests/test_suite.py
> +        def ensure_module_session_datum_xml(detail_inline_attr, detail_persistent_attr):
This is basically identical to the one in `test_persistent_case_tiles_from_another_module`. Why not make it a reusable function.

2017-06-21 08:20 UTC, mkangia commented on corehq/apps/app_manager/tests/test_suite.py
> +        def ensure_module_session_datum_xml(detail_inline_attr, detail_persistent_attr):
Extracting a common method.
They just had different arguments since other didnt need `detail_inline_attr` so just kept it under the particular test.

2017-06-21 08:55 UTC, snopoke approved these changes

2017-06-21 17:41 UTC, merged