adding static ucrs to linked apps
dimagi/commcare-hq pull request #16781
Opened 2017-06-26 03:26 UTC by calellowitz

@snopoke cc: @emord 
Took a stab at this over the weekend as we think about next steps for icds app building.

2017-06-26 10:29 UTC, snopoke requested changes

2017-06-26 10:29 UTC, snopoke commented on corehq/apps/userreports/util.py
> +            raise UserReportsError("Found dynamic UCR when static expected")
I don't think this will ever get raised since this loop is only iterating over static UCRs.

2017-06-27 07:07 UTC, snopoke approved these changes
Would be great to have a test for this.

2017-06-27 12:56 UTC, emord approved these changes

2017-06-29 14:15 UTC, merged