group_by doesn't seem to apply for form reports
dimagi/commcare-hq pull request #16845
Opened 2017-06-29 15:59 UTC by esoergel

Getting a validation error here: https://manage.dimagi.com/default.asp?257168
Introduced in https://github.com/dimagi/commcare-hq/pull/16602

@biyeun, can you verify that this is appropriate?

@NoahCarnahan @biyeun cc @emord

2017-06-29 17:07 UTC, NoahCarnahan requested changes
Hey, `group_by` is actually relevant for some form based reports. However it is not relevant for form/case list reports, or for chart reports (this type is stored in `report_type`).

2017-06-29 19:54 UTC, esoergel commented on corehq/apps/userreports/templates/userreports/reportbuilder/configure_report.html
> +        var groupByInitialValue = {{ form.fields.group_by.widget.value|JSON}};
This widget's initial value was no longer being populated, so I added that in in this somewhat hacky fashion

2017-06-29 19:54 UTC, esoergel commented
@NoahCarnahan ready for review again

2017-06-29 20:18 UTC, NoahCarnahan approved these changes
Nice, looks good to me.

2017-06-30 09:21 UTC, kaapstorm commented on corehq/apps/userreports/reports/builder/forms.py
> +            self.fields['group_by'].widget = QuestionSelect(
Should this be `self.fields['location'].widget`, considering this is a Map Report, or should line 1498 also be `self.fields['group_by'].widget`?

2017-06-30 13:22 UTC, esoergel commented on corehq/apps/userreports/reports/builder/forms.py
> +            self.fields['group_by'].widget = QuestionSelect(
you're absolutely right - I must've just copypasted this.  Thanks!

2017-06-30 13:23 UTC, merged

2017-06-30 16:50 UTC, biyeun commented on corehq/apps/userreports/reports/builder/forms.py
> +            'value: {}'.format(self.ko_value or self.value)
hey, this isn't right. value is specifically the KO variable, not the text value of whatever is contained in the field

2017-06-30 17:54 UTC, esoergel commented on corehq/apps/userreports/reports/builder/forms.py
> +            'value: {}'.format(self.ko_value or self.value)
Right, but when `ko_value` isn't provided, there is no knockout variable to bind to.  This widget is called both in contexts where it's bound to a model, and contexts where it isn't.  This falls back to the old behavior when it's not a knockout-bound widget.  That is, https://github.com/dimagi/commcare-hq/pull/16845/files#diff-66cf616ff719298fed0e5e58ca5165ccL123
Actually I just realized that this should be
```python
'value: {}'.format(self.ko_value) if self.ko_value else 'value: "{}"'.format(self.value) 
```
(I forgot the quotes when it's a literal)  Does that sound right to you?

2017-07-03 14:53 UTC, biyeun commented on corehq/apps/userreports/reports/builder/forms.py
> +            'value: {}'.format(self.ko_value or self.value)
@esoergel if there is no knockout variable to bind to, it needs to be passed to the `value` attr, otherwise `data-bind` has no meaning....

2017-07-03 22:12 UTC, esoergel commented on corehq/apps/userreports/reports/builder/forms.py
> +            'value: {}'.format(self.ko_value or self.value)
https://github.com/dimagi/commcare-hq/pull/16889