ICDS - Update Aggregation and View for Dashboard v2
dimagi/commcare-hq pull request #16844
Opened 2017-06-29 15:19 UTC by sheelio

@emord 

This does a few things:
- Adds new columns to the existing aggregate tables
- Updates the views for those aggregate tables
- Adds a new aggregate table (for daily tracking)

(One open TODO is purging any daily tables > 15 days old.  Not sure the best way to do that.

2017-06-29 23:43 UTC, sheelio commented
@emord 
It looks like @kkrampa has added a migration to specify views that are already present in the aggregation scripts (they're on master, not in this PR).  Is that going to create issues with the views that are being manually created?

2017-06-30 13:27 UTC, emord commented
@sheelio do you mean these? https://github.com/dimagi/commcare-hq/blob/master/custom/icds_reports/migrations/0016_aggawcmonthly_aggccsrecordmonthly_aggchildhealthmonthly_aggdailyusageview_aggthrmonthly_awclocation_.py

It looks like managed = False so it should be fine https://docs.djangoproject.com/en/1.11/ref/models/options/#managed

2017-06-30 13:49 UTC, emord requested changes
I think I was wrong actually. Since you're add columns you'll probably want to change the model definitions that he wrote. and make another migration

2017-06-30 13:49 UTC, emord commented on custom/icds_reports/migrations/0016_add_v2_indicators.py
> +class Migration(migrations.Migration):
You'll probably need to rebase branch this onto master and rename this migration and change the dependency

2017-07-05 14:46 UTC, closed without merging