Ce/linked form
dimagi/commcare-hq pull request #17129
Opened 2017-07-21 15:35 UTC by calellowitz

@snopoke @orangejenny cc: @mkangia 
This will ensure that future migrations with the management command on ICDS work until we get linked apps set up there. I am holding off on truly unique ids for linked apps until the new mobile version comes out that fixes updates when a form id has changed. Otherwise it could break all existing linked app deployments. But I will just be able to remove the conditional and extra argument at that point, then add linked apps to the `xforms_index`.

2017-07-21 16:14 UTC, orangejenny commented
Looks fine in general, but there's rather a lot of code that overlaps with `update_unique_ids`, any possibility of refactoring?

2017-07-31 08:49 UTC, snopoke commented
Agree with @orangejenny about refactoring to reduce code duplication

2017-07-31 21:06 UTC, calellowitz commented
refactored a bit @orangejenny

2017-08-01 08:11 UTC, snopoke requested changes
small changes

2017-08-01 08:11 UTC, snopoke commented on corehq/apps/app_manager/views/utils.py
> +    id_map = _get_form_id_map(app)
Could put this under the `if maintain_ids` check

2017-08-01 08:11 UTC, snopoke commented on corehq/apps/app_manager/views/utils.py
> +    return app
don't think this is needed anymore

2017-08-02 07:17 UTC, snopoke commented on corehq/apps/app_manager/views/utils.py
> +        id_map = {}
nit: the only place I see this getting used is on line 159 where it's passed to `_update_form_ids`. That line is also under the same if check `if maintain_ids` so it seems to me like `id_map` can be defined there:
```
if maintain_ids:
    id_map = _get_from_id_map(app)
    wrapped_app = _update_form_ids(wrapped_app, master_build, id_map)
```

2017-08-03 13:43 UTC, merged