Add first pass at BETS location dump
dimagi/commcare-hq pull request #17385
Opened 2017-08-07 21:31 UTC by esoergel

@proteusvacuum @mkangia

2017-08-08 09:33 UTC, mkangia requested changes

2017-08-08 09:33 UTC, mkangia commented on custom/enikshay/management/commands/get_locations_for_bets.py
> +                if loc.metadata.get('is_test') == "yes":
should that be a "no" to ignore test locations?
Also it might just possible be neither if its not set?

2017-08-08 13:22 UTC, esoergel commented on custom/enikshay/management/commands/get_locations_for_bets.py
> +                if loc.metadata.get('is_test') == "yes":
Right - it should be `!= 'yes'` to mirror the logic in the `BETSLocationRepeater`.  Updated

2017-08-08 14:18 UTC, mkangia approved these changes
I think there is just one ToDo item left on this.

2017-08-09 00:39 UTC, esoergel commented
@mkangia @proteusvacuum just updated with two more commits to match finalized format.

2017-08-09 00:40 UTC, esoergel commented on custom/enikshay/integrations/bets/utils.py
> +    }
@proteusvacuum FYI, I'm freezing the locations API to what's described in the spec doc

2017-08-09 15:42 UTC, NoahCarnahan requested changes

2017-08-09 15:42 UTC, NoahCarnahan commented on custom/enikshay/management/commands/get_locations_for_bets.py
> +                if True or loc.metadata.get('is_test') != "yes":
This will always be True.

2017-08-09 18:24 UTC, esoergel commented on custom/enikshay/management/commands/get_locations_for_bets.py
> +                if True or loc.metadata.get('is_test') != "yes":
Thank you, good catch.  I put that in there to test this out locally and forgot to remove it

2017-08-09 18:25 UTC, NoahCarnahan approved these changes

2017-08-09 18:28 UTC, merged

2017-08-10 17:00 UTC, proteusvacuum commented
👍