Add script to get a csv of eNikshay agency data
dimagi/commcare-hq pull request #17382
Opened 2017-08-07 19:59 UTC by esoergel

2017-08-07 21:23 UTC, proteusvacuum requested changes
I think this needs to be modeled after the data that we are sending them in the repeater (I'm assuming that I should be looking at `BETSUserPayloadGenerator`)?

There are slight differences here that I think are going to be very confusing for them. It seems to me as though there is a bunch of important data missing here too.

Or was this just a proof of concept and you are waiting on their document to update all these names?

2017-08-07 21:23 UTC, proteusvacuum commented on custom/enikshay/management/commands/get_users_for_bets.py
> +        filename = 'agency_users.csv'
won't this get saved in the `current` release directory? Are the permissions set up correctly to be able to scp from there?

2017-08-07 21:23 UTC, proteusvacuum commented on custom/enikshay/management/commands/get_users_for_bets.py
> +    def confirm(self):
this doesn't look used.

2017-08-07 21:23 UTC, proteusvacuum commented on custom/enikshay/management/commands/get_users_for_bets.py
> +            print "user {} {} has no virtual location".format(user.username, user._id)
should we output a list of all of these users and their IDs so that we can handle them in some way?

2017-08-07 21:23 UTC, proteusvacuum commented on custom/enikshay/management/commands/get_users_for_bets.py
> +            for user in CommCareUser.by_domain(domain):
might want to add `with_progress_bar` here so that whoever runs this knows what's happening.

2017-08-07 21:23 UTC, proteusvacuum commented on custom/enikshay/management/commands/get_users_for_bets.py
> +                'user_id',
this is `id` in the repeater

2017-08-07 21:23 UTC, proteusvacuum commented on custom/enikshay/management/commands/get_users_for_bets.py
> +                'phone_number',
this is `phone_numbers` in the repeater

2017-08-07 21:23 UTC, proteusvacuum commented on custom/enikshay/management/commands/get_users_for_bets.py
> +            user.phone_number,
this is `user.phone_numbers` in the repeater

2017-08-07 21:23 UTC, proteusvacuum commented on custom/enikshay/management/commands/get_users_for_bets.py
> +                'language',
this isn't in the repeater

2017-08-07 21:23 UTC, proteusvacuum commented on custom/enikshay/management/commands/get_users_for_bets.py
> +            writer.writerow([
There's `privateSectorOrgId`, `dtoLocation`, and `default_phone_number` in the repeater that seem like they might be important.

2017-08-07 21:23 UTC, proteusvacuum commented on custom/enikshay/management/commands/get_users_for_bets.py
> +            user.raw_username,
this is `user.username` in the repeater.

2017-08-07 21:23 UTC, proteusvacuum commented on custom/enikshay/management/commands/get_users_for_bets.py
> +                'location_id',
this isn't in the repeater

2017-08-07 21:23 UTC, proteusvacuum commented on custom/enikshay/management/commands/get_users_for_bets.py
> +                'location_name',
this isn't in the repeater

2017-08-07 21:45 UTC, esoergel commented on custom/enikshay/management/commands/get_users_for_bets.py
> +        filename = 'agency_users.csv'
Yup, I can scp from that dir

2017-08-07 21:45 UTC, esoergel commented on custom/enikshay/management/commands/get_users_for_bets.py
> +            for user in CommCareUser.by_domain(domain):
:+1:

2017-08-07 21:47 UTC, esoergel commented on custom/enikshay/management/commands/get_users_for_bets.py
> +            print "user {} {} has no virtual location".format(user.username, user._id)
When I ran this on Friday, there was only one such user, which was some test thing that didn't seem concerning.  I don't have any objections to adding it, but I don't think it'll be needed.

2017-08-07 21:52 UTC, esoergel commented
@proteusvacuum This is the script I ran on Friday to look at the relevant set of agency data.  This is primarily here for the "get" logic, and I'll rewrite the serialization logic once we get the final set of fields (I tried to say as much in my PR comment).

2017-08-07 22:02 UTC, esoergel commented
@proteusvacuum updated

2017-08-07 22:22 UTC, proteusvacuum commented
@esoergel I didn't see the description for some reason.

2017-08-09 15:55 UTC, mkangia approved these changes
Dont have the context of the change so would still defer to @proteusvacuum for a better review. Nothing blocking otherwise, just added couple of comments.

2017-08-09 15:55 UTC, mkangia commented on custom/enikshay/integrations/bets/repeaters.py
> +        return (user.user_data.get('user_level', None) == 'real'
Do we need `None` here? Get would anyway return `None`

2017-08-09 15:55 UTC, mkangia commented on custom/enikshay/integrations/bets/repeater_generators.py
> +            for field in BETSUserPayloadGenerator.user_data_fields
Just checking if making this change makes things better?

2017-08-09 18:20 UTC, esoergel commented on custom/enikshay/integrations/bets/repeater_generators.py
> +            for field in BETSUserPayloadGenerator.user_data_fields
I made this a staticmethod so I could access it from the management command, which means `self` is no longer available.

2017-08-09 18:21 UTC, merged

2017-08-10 16:52 UTC, proteusvacuum commented on custom/enikshay/management/commands/get_users_for_bets.py
> +            return user_data.get(field, '')
won't `migrationCrtdRecordId` always end up as `''` here? I thought it needed to be set to the UATBC id of the agency.

2017-08-10 16:52 UTC, proteusvacuum commented
Looks good. Had one comment after the merge.