Finish up BETS data dump commands
dimagi/commcare-hq pull request #17413
Opened 2017-08-09 22:09 UTC by esoergel

https://docs.google.com/spreadsheets/d/1yOrEgKyWKpwyIf4NCzY978LD6xzZaIyqu2FhrBKv22g/edit#gid=1696100868
@proteusvacuum @sravfeyn

2017-08-10 17:19 UTC, proteusvacuum requested changes

2017-08-10 17:19 UTC, proteusvacuum commented on custom/enikshay/management/commands/get_vouchers_for_bets.py
> +                    payload[u'PersonID'] = voucher_case.get_case_property('person_enikshay_id')
I don't think voucher cases have this property. Where did you find that? 
I think better to use `person_case.get_case_property('person_id')`

2017-08-10 17:19 UTC, proteusvacuum commented on custom/enikshay/integrations/bets/repeater_generators.py
> +        else:
in theory we should only be sending them approved vouchers. If this property isn't set, then something has gone wrong somewhere...

2017-08-10 17:19 UTC, proteusvacuum commented on custom/enikshay/management/commands/get_vouchers_for_bets.py
>                      payload['Succeeded'] = record.succeeded
Looks like they don't want this any more, and instead want `PaymentStatus` (you might have fixed in a later commit)

2017-08-10 17:19 UTC, proteusvacuum commented on custom/enikshay/integrations/bets/repeater_generators.py
> +        case_json["properties"]["phone_number"] = case_properties.get("contact_phone_number", "")
this is going to be of the form `91123456789`. Just making sure they are aware that it will have the `91` part at the beginning.

2017-08-10 17:53 UTC, esoergel commented on custom/enikshay/management/commands/get_vouchers_for_bets.py
> +                    payload[u'PersonID'] = voucher_case.get_case_property('person_enikshay_id')
:+1:

2017-08-10 17:54 UTC, esoergel commented on custom/enikshay/management/commands/get_vouchers_for_bets.py
>                      payload['Succeeded'] = record.succeeded
I think I'll come back to this and update with the rest of the changes - the voucher dump also needs to include the payment confirmation information, but that won't be part of this next set of dumps.

2017-08-10 17:56 UTC, esoergel commented on custom/enikshay/integrations/bets/repeater_generators.py
> +        case_json["properties"]["phone_number"] = case_properties.get("contact_phone_number", "")
I added an example in that format to the spec doc, although we didn't discuss specifically.

2017-08-10 17:59 UTC, esoergel commented on custom/enikshay/integrations/bets/repeater_generators.py
> +        else:
Good point. Making this fail hard.

2017-08-10 18:45 UTC, proteusvacuum approved these changes
One question, looks good though

2017-08-10 18:45 UTC, proteusvacuum commented on custom/enikshay/management/commands/get_users_for_bets.py
> +        user_data['migrationCrtdRecordId'] = user.user_data.get('agency_id_legacy', '')
are they aware that this won't be set on agencies that were created in eNikshay? 
I think they might be looking for something else here?

2017-08-11 03:48 UTC, proteusvacuum commented on custom/enikshay/integrations/bets/repeater_generators.py
> +        registered_by_location = episode_case_properties.get("registered_by")
If it was only test cases that were failing this test, then I'm happy to leave this as it was, as users are only on the newest version of the app, which sets this property correctly.

2017-08-11 04:04 UTC, esoergel commented on custom/enikshay/integrations/bets/repeater_generators.py
> +        registered_by_location = episode_case_properties.get("registered_by")
:+1:

2017-08-11 14:03 UTC, merged