Hide all info in email from report
dimagi/commcare-hq pull request #17427
Opened 2017-08-10 18:56 UTC by proteusvacuum

Email body was including all the data. Which in some cases was making the email to large to send.
We just want the excel export anyway.
@mkangia 
cc @gcapalbo

2017-08-10 20:39 UTC, gcapalbo approved these changes

2017-08-11 07:10 UTC, mkangia requested changes
@proteusvacuum would it be possible to have the count of cancelled records for each repeater in the email body instead. It would help to take a quick look at that number to have an idea about the cancelled records without needing to open each report.

2017-08-11 07:10 UTC, mkangia commented on custom/enikshay/reports/repeaters.py
> +            return []
It would be better to not even call this method if it is to return []. Or atleast return at first step instead of fetching repeater and state first?

2017-08-11 15:50 UTC, proteusvacuum commented
@mkangia good idea.

2017-08-11 16:22 UTC, mkangia commented on custom/enikshay/reports/repeaters.py
> +                ]
@proteusvacuum I think we should include Failed in this as well.

2017-08-11 16:23 UTC, mkangia commented on custom/enikshay/reports/repeaters.py
> -                DataTablesColumn(_('Payload')),
👍

2017-08-11 16:23 UTC, mkangia approved these changes
Looks good. 
Just requested to include Failed count as well if that makes sense. Not a blocker

2017-08-11 17:07 UTC, proteusvacuum commented on custom/enikshay/reports/repeaters.py
> +                ]
Since failed is a transient state, I figured the count doesn't mean much.

2017-08-11 20:58 UTC, merged