Referral report
dimagi/commcare-hq pull request #18018
Opened 2017-09-29 13:24 UTC by kkrampa

http://manage.dimagi.com/default.asp?262732#1398937
@calellowitz

2017-10-03 11:34 UTC, kkrampa commented
@calellowitz Could you merge this PR?

2017-10-09 05:39 UTC, calellowitz requested changes
You appear to have missed the case definition column, as well as the separate columns for TU and PHI.
Additionally, these columns should be added to `referral_report.json`. Since the report is live right now, it would be good to create a v2 of that as well. It is also possible to do the display transforms I commented on, in the report itself if you prefer but it seems a bit cleaner to store them in the data source.

2017-10-09 05:39 UTC, calellowitz commented on custom/enikshay/ucr/data_sources/person_for_referral_report_v2.json
> +                "expression": {
i dont think this meets the spec. it looks like you should display `Confirmed DSTB (Patient) ` for `confirmed_tb` and `Confirmed DRTB (Patient)` for `confirmed_drtb`. additionally, i spoke with sarvesh and it seems there should be a third option `Presumptive TB` for `presumptive_tb`

2017-10-09 05:39 UTC, calellowitz commented on custom/enikshay/ucr/data_sources/person_for_referral_report_v2.json
> +                "display_name": "adherence_schedule_id",
same as above. i dont think this meets the spec. It should be `schedule_daily` -> `Daily`, `schedule_mwf` -> `Intermittent (MWF)`, and `schedule_trs` -> `Intermittent (TTS)`

2017-10-09 05:46 UTC, kkrampa commented
@calellowitz I prefer to do this on the report side since when a new value will be added we don't need to rebuild data source. Any benefits from keeping this in the data source?

2017-10-09 05:48 UTC, calellowitz commented
@kkrampa report is fine

2017-10-09 12:30 UTC, kkrampa commented
@calellowitz Updated

2017-10-10 13:41 UTC, calellowitz commented
I think you are still missing the case definition column

2017-10-11 13:07 UTC, kkrampa commented
Added

2017-11-20 05:46 UTC, calellowitz commented
@kkrampa looking to push this out today. can we fix the merge conflicts

2017-11-20 14:13 UTC, calellowitz commented
@kkrampa looks good once you fix those lint issues

2017-11-21 12:40 UTC, merged