Filtered Mobile worker download
dimagi/commcare-hq pull request #18038
Opened 2017-10-02 15:07 UTC by sravfeyn

@emord

2017-10-02 21:01 UTC, emord requested changes
lgtm once you change the inline js code.

2017-10-02 21:01 UTC, emord commented on corehq/apps/users/templates/users/filter_and_download.html
> +<script>
I think that this should be in a separate javascript file and you should use initial_page_data to pass any data to it.

2017-10-02 21:01 UTC, emord commented on corehq/apps/users/views/mobile/users.py
> +        context = super(FilteredUserDownload, self).main_context
I think you could just use `self.main_context` here right?

2017-10-03 05:41 UTC, sravfeyn commented
@emord updated

2017-10-03 18:36 UTC, emord approved these changes

2017-10-03 18:36 UTC, merged