Add command to find applications enabled for an add on [skip ci]
dimagi/commcare-hq pull request #18657
Opened 2017-11-25 10:58 UTC by mkangia

2017-11-29 03:18 UTC, orangejenny requested changes

2017-11-29 03:18 UTC, orangejenny commented on corehq/apps/app_manager/management/commands/applications_with_add_ons.py
> +                                'status': application.add_ons.get('custom_icon_badges')
should be `add_on_name`

2017-12-03 17:55 UTC, mkangia commented on corehq/apps/app_manager/management/commands/applications_with_add_ons.py
> +                                'status': application.add_ons.get('custom_icon_badges')
oops, thanks for catching.

2017-12-04 15:39 UTC, orangejenny approved these changes
Updates look good, feel free to self-merge once py3 check passes.

2017-12-07 12:01 UTC, mkangia commented
@sheelio unsure of what label this should have. 
`product/feature-flag` + `product/all-users-all-environment`?

2017-12-07 14:00 UTC, sheelio commented
I would use all users-all-environments (since we're changing behaviour for potentially non feature flagged projects).

2017-12-07 16:27 UTC, merged