Changes for Referral Report.
dimagi/commcare-hq pull request #18733
Opened 2017-11-30 14:38 UTC by lwyszomi

Hi @calellowitz 

I added changes to the Referral Report. Please let me know if you have any questions.

Regards,
Łukasz

2017-12-01 11:58 UTC, calellowitz requested changes
got some questions, and one possible issue

2017-12-01 11:58 UTC, calellowitz commented on custom/enikshay/case_utils.py
> +        return sorted(valid_cases, key=(lambda case: case.opened_on))[0]
i think this will sort in the opposite order. its supposed to be the latest opened case right?

2017-12-01 11:58 UTC, calellowitz commented on custom/enikshay/case_utils.py
> -    return get_open_episode_case_from_occurrence(
is this function used anymore?

2017-12-01 11:58 UTC, calellowitz commented on custom/enikshay/case_utils.py
>  def get_open_episode_case_from_person(domain, person_case_id):
it looks like this is used all over the code base. have you verified that this change is ok for all of them?

2017-12-01 11:58 UTC, calellowitz commented on custom/enikshay/case_utils.py
> +        episode_cases += [case for case in all_cases if case.type == CASE_TYPE_EPISODE]
it looks like this is used in more than just the referral report, are these changes ok for that as well

2017-12-01 12:51 UTC, lwyszomi commented
Hi, @calellowitz 

I will revert this changes and I will add a new expression for referral and episode case. I didn't notice that this code is used in other places than Referral report.

Regards,
Łukasz

2017-12-04 11:08 UTC, calellowitz requested changes
It would be great if the two expressions you made could be cached since they are used so much in that data source. You can look at `ReferralExpressionBase` to see how to use the expression context to cache.

2017-12-04 11:08 UTC, calellowitz commented on settings.py
> +    ('enikshay_key_populations', 'custom.enikshay.expressions.most_recent_referral_expression'),
i think you forgot to change the first part of the tuple when you copied and pasted for both of the new expressions

2017-12-04 11:09 UTC, calellowitz commented
i think you also forgot to add the new datasource to settings

2017-12-04 12:05 UTC, lwyszomi commented
Hi @calellowitz 

Thanks for the review. I send updates on the new commit. Please let me know if you have any questions.

Regards,
Łukasz

2017-12-04 12:46 UTC, calellowitz approved these changes
thanks for the fast turnaround on all these PRs

2017-12-04 12:58 UTC, jordanhlerner commented
@lwyszomi @calellowitz Thank you both for being thorough and efficient!

2017-12-04 12:59 UTC, merged