Add More Domain Calculations
dimagi/commcare-hq pull request #18753
Opened 2017-12-01 15:04 UTC by sheelio

@nickpell 
I'm working on adding some new domain level calculations to support some of our retention / pricing analysis work. 

Is this the right approach?  Eventually we'd like this data pushed to Salesforce.

2017-12-01 15:15 UTC, nickpell commented
Seems reasonable that we could have an API that retrieves these calculations.

The accounting APIs use tastypie to retrieve postgres models:
https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/api/accounting.py

2017-12-01 15:42 UTC, sheelio commented
Cool - are you suggesting we should add an API instead for these? The code I modified is used here:
https://github.com/dimagi/commcare-hq/blob/194113c1d571bc6bbe206b7115d0f48f449215ca/corehq/apps/reports/tasks.py

And then exposed as a resource here:
https://github.com/dimagi/commcare-hq/blob/2ed89103410b228196fb7c9f564e3b00f3c80ef5/corehq/apps/api/domain_metadata.py

2017-12-01 16:00 UTC, nickpell commented
Using ```DomainMetadataResource``` looks right

2017-12-01 19:25 UTC, sheelio commented
@nickpell 
I think this is good to review.

2017-12-01 19:26 UTC, sheelio commented
@calellowitz   Not sure if you or Nick are best suited to review these changes.

2017-12-01 19:50 UTC, nickpell requested changes

2017-12-01 19:50 UTC, nickpell commented on corehq/apps/api/resources/__init__.py
> +            if type(self) is DomainSpecificResourceMixin:
should use ```isinstance```

2017-12-01 20:17 UTC, nickpell approved these changes

2017-12-04 19:17 UTC, sheelio commented
@nickpell 
Tests are now passing - let me know if good to merge or if you want to review once more.

2017-12-05 02:48 UTC, merged