Icds change adolescent age range
dimagi/commcare-hq pull request #19341
Opened 2018-02-02 12:46 UTC by dmydlo

Hi @emord,
This PR consists of 3 changes:
1st is Fix for AwcReportsView where the variable 'month' was used as datetime when it was an integer.
2nd is the change of adolescent girls age range shown in program summary and map/ chart view.
And the 3rd one is switch on how we prevent tooltip content from overflowing to wrap content itself rather than adjust tooltip width. Thanks to which tooltips that contain a bigger amount of data will be long rather than wide.

So as you can see 2nd commit is the change mentioned in name and other two are adjustments for previous changes.

Let me know if you have any questions or comments.

2018-02-02 17:07 UTC, emord commented
> 1st is Fix for AwcReportsView where the variable 'month' was used as datetime when it was an integer.

Why wasn't that sort of thing caught by our view tests? Can you make a test for that?

> 2nd is the change of adolescent girls age range shown in program summary and map/ chart view.

The original ticket says to do this by using the beta features dashboard flag. so it should show the old columns by default, but the new ones when https://github.com/dimagi/commcare-hq/blob/master/corehq/toggles.py#L901-L906 is enabled

2018-02-02 17:07 UTC, emord requested changes
see above comment

2018-02-05 12:28 UTC, dmydlo commented
As Sriya mentioned in the task, right now this shouldn't be behind feature flag, so I am just rebasing it.

2018-02-05 13:36 UTC, emord approved these changes

2018-02-05 13:37 UTC, merged