ejs repeat record report
dimagi/commcare-hq pull request #19416
Opened 2018-02-12 21:49 UTC by jmtroth0

2018-02-13 15:24 UTC, orangejenny requested changes

2018-02-13 15:24 UTC, orangejenny commented on corehq/apps/domain/static/domain/js/repeat_record_report.js
> +                url: initialPageData.get("repeat_record"),
use `reverse` instead of `get` for urls

2018-02-13 15:24 UTC, orangejenny commented on corehq/apps/domain/templates/domain/repeat_record_report.html
> +    <script src="{% static 'domain/js/repeat_record_report.js' %}"></script>
not blocking, but this could go inside the `compress` block so it gets minified

2018-02-15 20:36 UTC, jmtroth0 commented
@orangejenny this is updated. can you take another look? I think ethan is working on something related, so I'd love to get it out

2018-02-15 21:08 UTC, orangejenny approved these changes

2018-02-15 21:08 UTC, merged

2018-02-15 21:16 UTC, jmtroth0 commented
thanks!