Fix the Undo button on app deletion
dimagi/commcare-hq pull request #19720
Opened 2018-03-08 19:14 UTC by pr33thi

Ticket: https://manage.dimagi.com/default.asp?271883#1468765
Problem: The `undo_delete_app` function has a `@no_conflict_require_POST` decorator, which requires a post request. Before, the undo was an `href` (which will always be a link), so I changed it to a form containing a button that makes a post request.

2018-03-08 19:59 UTC, proteusvacuum requested changes

2018-03-08 19:59 UTC, proteusvacuum commented on corehq/apps/app_manager/templates/undo_delete_app.html
> +    <input type="submit" class="btn btn-default" value="Undo" />
"Undo" should be translated

2018-03-08 19:59 UTC, proteusvacuum commented on corehq/apps/app_manager/templates/undo_delete_app.html
> +</form>
nit: no newline at the end of this file

2018-03-08 21:46 UTC, proteusvacuum approved these changes

2018-03-09 19:57 UTC, pr33thi commented
Fixing it with this instead: https://github.com/dimagi/commcare-hq/pull/19737
Closing this PR

2018-03-09 19:57 UTC, closed without merging