Add LinkedApplication to view.
dimagi/commcare-hq pull request #20097
Opened 2018-04-04 18:03 UTC by emord

http://manage.dimagi.com/default.asp?273668
https://sentry.io/dimagi/commcarehq/issues/512593578/?query=domain:vectorlink-uganda

This is [used in UCRs](https://github.com/dimagi/commcare-hq/blob/je/linked-app-data-source/corehq/apps/userreports/views.py?utf8=%E2%9C%93#L937) when building a data source in the app. Was there any reason that Linked Apps weren't added to this view?

@snopoke @calellowitz guessing you guys are the best to answer

2018-04-05 08:20 UTC, snopoke requested changes
I don't think it was excluded on purpose

2018-04-05 08:20 UTC, snopoke commented on corehq/apps/app_manager/_design/views/xforms_index/map.js
> +    if (doc.doc_type.indexOf(['Application', 'LinkedApplication']) === -1) {
shouldn't this be reversed `['Application', 'LinkedApplication'].indexOf(doc.doc_type)`

2018-04-05 15:32 UTC, emord commented
@proteusvacuum This interrupt ticket was closed as I provided a workaround that unblocked the project, but I think this should still go out. Can you take this over next week since I'll be on vacation?

From my understanding it should be a quick preindex since it's only on the application db

2018-04-06 04:58 UTC, calellowitz commented
One thing to be wary of, and worth testing app install in addition to UCRs with this, is that for a while (and maybe in some cases still), linked application forms had the same unique ids as the master app. If that remains the case for apps, it could cause some install errors as it tries to fetch a form by id, which we saw on ICDS when we overwrote their live apps with test apps and kept the IDs. A fix was made so that new linked apps get clean unique ids but there may be some older apps that still share IDs with the master.

@snopoke Do you have any recollection if we modified existing linked apps when we made the unique id fix. I do not recall doing so which makes me think the install of any linked app made before that PR will break after this.

2018-04-06 08:26 UTC, snopoke commented
@calellowitz I think you are correct. It shouldn't be hard to run a script in a shell on each env to validate whether or not there will be an issue.

2018-04-13 01:18 UTC, proteusvacuum commented
I didn't get to this during my interrupt cycle. Pinging @dannyroberts

2018-09-12 20:31 UTC, closed without merging