Remove unnecessary SQLData's and use SQL views to collect data
dimagi/commcare-hq pull request #20899
Opened 2018-06-14 10:26 UTC by lwyszomi

Hi @emord,

Regarding this case: http://manage.dimagi.com/default.asp?276465#1496539 I changed the implementation of the monthly register report and now we using SQL views to collect data.

Please Let me know if you have any questions.

Regards,
Łukasz

2018-06-14 20:47 UTC, emord requested changes
I believe that the tests shouldn't need to be modified if they are querying hte same data. Looks like the definitions changed when you moved them to the new tables

2018-06-14 20:47 UTC, emord commented on custom/icds_reports/reports/issnip_monthly_register.py
> +            }, 'rations_21_plus_distributed')),
These definitions changed from `pse_days_attended` to `rations_21_plus_distributed`. It looks like in agg child health you we don't have a pse_days_attended > 21 column, so you should be able to query child_health_monthly view with these same columns but counting the rows where `pse_days_attended >=21`

2018-06-14 20:47 UTC, emord commented on custom/icds_reports/reports/issnip_monthly_register.py
> +            }, 'rations_21_plus_distributed')),
These filters should look like `ccs_status = pregnant/lactating` instead of `pregnant/lactating = 1`

2018-06-18 09:17 UTC, lwyszomi commented
Hi @emord 

I added requested changes, but build fail. Could you kick off it, I think this is not related.

Thanks,
Łukasz

2018-06-18 14:32 UTC, emord approved these changes

2018-06-18 14:32 UTC, merged