support partial file downloads for exports
dimagi/commcare-hq pull request #20900
Opened 2018-06-14 11:46 UTC by snopoke

This should allow failed downloads to be resumed.

https://manage.dimagi.com/default.asp?277653

```
# download first 10000 bytes
curl -n <export url> -u username -o export.zip -r 0-10000

# download rest
curl -n <export url> -u username -o export.zip -C -
```

2018-06-14 14:20 UTC, pr33thi requested changes
Just found the 1 bug, besides that it looks good

2018-06-14 14:20 UTC, pr33thi commented on corehq/util/download.py
> +    if "HTTP_RANGE" in request.META:
I believe this will error if no `request` is passed in and the default value of `request=None` is used

2018-06-14 14:30 UTC, pr33thi approved these changes

2018-06-15 08:28 UTC, merged

2018-06-15 19:09 UTC, dannyroberts commented
Seems to be causing problems because `werkzeug` isn't in `requirements.txt` (it's in `dev-requirements.txt`. That said, I can't for the life of me figure out why tests didn't catch that. Running tests locally without `werkzeug` installed gives me an import error

```
...
    from werkzeug.http import parse_range_header
ImportError: No module named werkzeug.http
```

2018-06-15 19:12 UTC, pr33thi commented
@dannyroberts  @proteusvacuum pointed out that dev-requirements.txt is installed in docker, so it's used in travis:
https://github.com/dimagi/commcare-hq/blob/master/Dockerfile#L29

I'm making a pr to move it from dev-requirements to requirements.txt

2018-06-15 19:20 UTC, proteusvacuum commented
Also: https://github.com/dimagi/commcare-hq/pull/20930

2018-06-18 07:21 UTC, snopoke commented
Shucks, sorry about that.