Fix filter warning criteria for report builder `Default Filter`
dimagi/commcare-hq pull request #20923
Opened 2018-06-15 15:00 UTC by pr33thi

Ticket: https://manage.dimagi.com/default.asp?277574
Any date selected would display a "Filter Value should not be blank" warning. This fixes a bug that made it always show up for dates.

2018-06-15 15:05 UTC, snopoke approved these changes

2018-06-15 15:32 UTC, kaapstorm requested changes
I think you'll need to make the same change on line 165 too.

2018-06-15 17:44 UTC, pr33thi commented
Added here: https://github.com/dimagi/commcare-hq/pull/20923/commits/92d5c0e0d9aaa4799b674430ecf4599f9e12c2cf

2018-06-18 08:07 UTC, kaapstorm approved these changes

2018-06-18 08:09 UTC, kaapstorm commented
Awesome, thanks.

Test failure unrelated. :recycle: :construction_worker_woman:

2018-06-18 14:50 UTC, merged