Change source for individual Beneficiary Child Page to ChildHealthMon…
dimagi/commcare-hq pull request #21048
Opened 2018-06-27 12:00 UTC by dmydlo

…thly table from view
Hi @emord,
I have change source of individual Beneficiary Child Page to a ChildHealthMonthly table from ChildHealthMonthly view to make it respond faster.
Let me know if You have any questions.
Regards, Dawid.

2018-06-27 15:27 UTC, emord requested changes
I think that this won't help. The issue is that this query is doing some sequential scans on some old tables that only have an index on (awc_id, case_id). I added these indexes to the old tables, but I think it is still good practice to change it to awc_id, case_id

Can you change this to also filter using the `awc_id` ? It should be possible to pass that in to this function from the view

2018-06-28 13:13 UTC, dmydlo commented
Hi @emord @lwyszomi,
I have updated PR with filtering by awc_id.

Regards, Dawid

2018-06-28 13:16 UTC, emord commented on custom/icds_reports/reports/awc_reports.py
> +    data = ChildHealthMonthly.objects.filter(
I think that you can move this back to `ChildHealthMonthlyView` as that wasn't the cause for slowness

2018-06-28 13:53 UTC, emord approved these changes
Thanks!

2018-07-02 16:12 UTC, emord commented on custom/icds_reports/reports/awc_reports.py
> +        awc_ic=awc_id
`awc_ic`  -> `awc_id`

2018-07-03 14:43 UTC, merged