updating billing to include gateway fees
dimagi/commcare-hq pull request #21309
Opened 2018-07-24 10:41 UTC by Rohit25negi

http://manage.dimagi.com/default.asp?280243
https://docs.google.com/document/d/16aH39sj7OixeYI_FwiJH3lmJCCMI4ZJzhn-kZ8bucUs/edit?ts=5b47a681#heading=h.o4xghqm2btkm

2018-07-24 10:45 UTC, Rohit25negi commented
@nickpell @calellowitz  please review the changes. Are these enough for billing change for UCLA project?. 

PS: unittest cases under writing.

2018-07-24 19:46 UTC, nickpell requested changes
Implementation of the feature looks good.  Had one request regarding tests.

2018-07-24 19:46 UTC, nickpell commented on corehq/apps/smsbillables/tests/test_gateway_fees.py
> +        self.assertIsNotNone(billable.gateway_fee)
I would also be good to check that the gateway fee charge assigned is correct.

Here's an example of how to mock a response from the twilio api:

https://github.com/dimagi/commcare-hq/blob/1bfe88ffe51eee2424a48e998b5f09926096f2c3/corehq/apps/smsbillables/tests/test_gateway_fees.py#L236-L272

2018-07-25 18:14 UTC, nickpell approved these changes

2018-07-26 05:03 UTC, merged

2018-07-30 13:37 UTC, nickpell commented
@Rohit25negi I just got a travis test failure:

```
ERROR: corehq.apps.smsbillables.tests.test_gateway_fees:TestGatewayFee.test_fee_for_non_global_backend

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/mnt/commcare-hq-ro/corehq/apps/smsbillables/tests/test_gateway_fees.py", line 242, in test_fee_for_non_global_backend

    arbitrary_message = messages[randint(0, len(messages))]

IndexError: list index out of range
```

I think this will happen every 1 out of ```len(messages)``` times tests are run.  Can you please fix?

2018-07-30 14:05 UTC, Rohit25negi commented
@nickpell can you share the travis job url

2018-07-30 14:13 UTC, Rohit25negi commented
Oh got it. @nickpell  Thanks for pointing it out.