Avoiding Text leaking
dimagi/commcare-hq pull request #21437
Opened 2018-08-03 08:58 UTC by Rohit25negi

preventing text leaking by breaking the text with ellipses at the end:
https://manage.dimagi.com/default.asp?280994

2018-08-06 17:47 UTC, biyeun approved these changes

2018-08-06 17:49 UTC, biyeun requested changes

2018-08-06 17:49 UTC, biyeun commented on corehq/apps/hqwebapp/static/hqwebapp/less/_hq/navs.less
> +  text-overflow: ellipsis;
hmm, actually, can you make this change specific to the navigation class for this use case? What you are changing here affects ALL nav links. not a good idea as we do want overflow for some of them

2018-08-10 09:34 UTC, Rohit25negi commented
@biyeun updated the code.

2018-08-16 22:10 UTC, biyeun approved these changes

2018-08-16 22:26 UTC, merged