Rn app manager update with ajax
dimagi/commcare-hq pull request #21451
Opened 2018-08-06 12:31 UTC by Rohit25negi

this code enables the ajax form submission for update prompt setting.
Here is the ticket:
http://manage.dimagi.com/default.asp?272410

2018-08-06 13:05 UTC, orangejenny commented on corehq/apps/app_manager/static/app_manager/js/apps_base.js
> +            const form = $(this),
yeah, we're ES5 for the foreseeable future

2018-08-06 13:11 UTC, orangejenny requested changes
Hi Rohit, could you take a look at implementing this with the SaveButton? It takes care of a bunch of standard functionality (try again logic, disabling the button until changes are made, etc.) The [linked whitelist](https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/app_manager/static/app_manager/js/settings/linked_whitelist.js) is an small area that uses the SaveButton.

2018-08-07 05:40 UTC, Rohit25negi commented
@orangejenny  replaced the previous ajax implementation with save Button implementation.
Tested also.

2018-08-07 13:10 UTC, orangejenny commented on corehq/apps/app_manager/templates/app_manager/partials/releases.html
> +                 <script src="{% static 'app_manager/js/releases/update_prompt.js' %}"></script>
This should go in `app_manager/app_view.html`. We're moving away from using script tags and towards using requirejs, and that migration is a little bit easier if all the script tags are in the `js` blocks in the big base templates.

2018-08-07 13:10 UTC, orangejenny approved these changes
This looks good, thank you for reworking it. Left one minor comment.

2018-08-08 09:15 UTC, Rohit25negi commented
@orangejenny   fyi shifted that script import.

2018-08-08 14:47 UTC, orangejenny approved these changes

2018-08-09 06:53 UTC, merged