Rn validate copy app form
dimagi/commcare-hq pull request #21466
Opened 2018-08-07 11:26 UTC by Rohit25negi

Added the form validation on client side for copy application form
http://manage.dimagi.com/default.asp?272584

2018-08-08 15:05 UTC, orangejenny requested changes
Looks good overall, had some minor comments.

2018-08-08 15:05 UTC, orangejenny commented on corehq/apps/app_manager/static/app_manager/js/app_view_application.js
> +            form.find('.help-block').remove();
If you turn on the feature flag for linking domains, you'll see this additional checkbox and help text, and the help text is getting removed if there's an error in the form.

<img width="728" alt="screen shot 2018-08-08 at 11 04 25 am" src="https://user-images.githubusercontent.com/1486591/43845817-d980be62-9afa-11e8-88fd-9c1263ec77ef.png">

2018-08-10 05:06 UTC, Rohit25negi commented
Updated the code.

2018-08-10 15:13 UTC, orangejenny approved these changes

2018-08-14 05:06 UTC, merged