Fix appnope issue
dimagi/commcare-hq pull request #21612
Opened 2018-08-21 21:22 UTC by dannyroberts

Fixes https://github.com/dimagi/commcare-hq/issues/21580

2018-08-21 21:28 UTC, emord approved these changes

2018-08-22 09:29 UTC, kaapstorm requested changes
Those build failures look like `_test_make_requirements` is failing. Maybe `echo` an error message before `exit 1` on failure.

2018-08-23 17:35 UTC, dannyroberts commented
@kaapstorm the build failures were due to my mistaken use of `[[ condition ]] && expression` as an if statement (it fails with non-zero when condition doesn't hold, instead of continuing silently like we want.)

2018-08-24 08:12 UTC, kaapstorm approved these changes

2018-08-24 17:07 UTC, biyeun approved these changes

2018-08-28 00:08 UTC, dannyroberts commented
Thanks for the review all, decided to go with a different strategy, so replacing this PR with this one: https://github.com/dimagi/commcare-hq/pull/21667.

2018-08-28 00:08 UTC, closed without merging