allow blank case tags
dimagi/commcare-hq pull request #21624
Opened 2018-08-22 18:40 UTC by nickpell

2018-08-22 20:26 UTC, esoergel reviewed
It looks like there are only two one-line changes in the JS - could you instead just reference the feature flag there using
```javascript
hqImport('hqwebapp/js/toggles').toggleEnabled('ALLOW_BLANK_CASE_TAGS')
```
As is, this'll be a "spot-the-differences" nightmare if anyone needs to update these files.

It'd help reviewing if you can commit the copy separately from the changes - I had to set up the diff myself locally to see what the actual changes are.

2018-08-22 20:40 UTC, nickpell commented
@esoergel Updated - should be easier to read now.

Thanks for explaining how to reference toggles in JS.

2018-08-22 20:50 UTC, esoergel requested changes

2018-08-22 20:50 UTC, esoergel commented on corehq/apps/app_manager/static/app_manager/js/forms/advanced/actions.js
> +            } else if (!case_tag || (self.warn_blank_case_tag() && hqImport('hqwebapp/js/toggles').toggleEnabled('ALLOW_BLANK_CASE_TAGS'))) {
Shouldn't this be "not toggle enabled"?

2018-08-22 20:50 UTC, esoergel commented on corehq/apps/app_manager/static/app_manager/js/forms/advanced/actions.js
> +                    if(hqImport('hqwebapp/js/toggles').toggleEnabled('ALLOW_BLANK_CASE_TAGS')) {
I think this is also backwards (assuming the default is to preserve the old behavior).
Also, what does this part do?

2018-08-22 20:50 UTC, esoergel commented
Nice, thanks for the switch!

2018-08-22 20:52 UTC, esoergel approved these changes

2018-08-22 20:53 UTC, nickpell commented
Merging, since this shouldn't affect tests and L10K is waiting for this

2018-08-22 20:54 UTC, merged

2018-08-23 14:42 UTC, orangejenny commented
@nickpell Hmm, this is a tricky issue. L10K may get themselves into the same bind that Jordan ran into. I'll think about potential longer-term solutions - but this is a decent quick fix, thank you! (And thank you for being conscientious and putting it behind a feature flag.)