[ICDS] Fixed problem with broken zip file
dimagi/commcare-hq pull request #22936
Opened 2019-01-10 16:37 UTC by lwyszomi

Hi @calellowitz @Rohit25negi 

I fixed a problem with the broken zip file and also I added a message if the file doesn't exist to don't throw a 500 error.
TICKET: https://dimagi-dev.atlassian.net/browse/QA-138

I think this is ready to merge to unblock QA process.

Please let me know if you have any questions.

Regards,
Łukasz

2019-01-10 16:38 UTC, lwyszomi commented
![cas_data_export](https://user-images.githubusercontent.com/429541/50982927-907ef980-14fe-11e9-9b43-ca880ee9a93e.png)

2019-01-10 20:22 UTC, calellowitz requested changes
couple small questions, but mostly looks fine.

2019-01-10 20:22 UTC, calellowitz commented on custom/icds_reports/views.py
> +            f = zipfile.ZipFile(output, 'w', zipfile.ZIP_DEFLATED)
What does this change by switching from `export_response`?  Also, why is the zipfile necessary? It is already a single file?

2019-01-11 10:19 UTC, lwyszomi commented
@calellowitz I updated the PR

2019-01-15 12:11 UTC, lwyszomi commented
@calellowitz bump

2019-01-15 18:58 UTC, calellowitz approved these changes

2019-01-15 18:58 UTC, merged