[JavaScript] standardize inheritance: UCR
dimagi/commcare-hq pull request #22974
Opened 2019-01-15 12:08 UTC by lwyszomi

Hi @orangejenny 

I sent the next part of javascript changes, currently, I refactored UCR.

Please let me know if you have any questions.

Regards,
Łukasz

2019-01-15 23:03 UTC, orangejenny requested changes
Just one comment, the rest looks great.

2019-01-15 23:03 UTC, orangejenny commented on corehq/apps/userreports/static/userreports/js/expression_evaluator.js
>          var self = this;
`var self = {};` and then `return self;` at the end

2019-01-15 23:07 UTC, orangejenny commented
Hi Łukasz, one more issue: when I edit a report builder report locally (http://localhost:8000/a/DOMAIN/reports/builder/edit/ID/), this error comes up. Can you check it out?

<img width="1350" alt="screen shot 2019-01-15 at 6 05 48 pm" src="https://user-images.githubusercontent.com/1486591/51215873-580d6000-18f0-11e9-905f-dc5fa3696c37.png">

2019-01-16 13:17 UTC, lwyszomi commented
@orangejenny updated

2019-01-16 14:25 UTC, orangejenny approved these changes

2019-01-16 14:25 UTC, merged