Rn add home visit agg awc
dimagi/commcare-hq pull request #23164
Opened 2019-02-06 04:54 UTC by Rohit25negi

Add Total home visits expected and valid in agg_awc with same calculation as [performance report](https://github.com/dimagi/commcare-hq/blob/master/custom/icds_reports/utils/aggregation_helpers/aww_incentive.py).

FOR Service delivery dashboard: https://docs.google.com/spreadsheets/d/1m6QplhblN7HbOULgUiKqv78At-W5d9RF3u7DYuHosn8/edit?ts=5c471250#gid=0

@calellowitz  @emord 

@sravfeyn   tagging you as code buddy

2019-02-06 13:18 UTC, sravfeyn commented on custom/icds_reports/utils/aggregation_helpers/agg_awc.py
> +        UPDATE "{tablename}" agg_awc SET
nit: Could indent below for better readability.

2019-02-06 13:18 UTC, sravfeyn approved these changes

2019-02-06 23:10 UTC, calellowitz requested changes
I believe this has a migration conflict as well as the other small changes I said

2019-02-06 23:10 UTC, calellowitz commented on custom/icds_reports/utils/aggregation_helpers/agg_awc.py
> +                sum(valid_visits) AS valid_home_visits,
I think it could be a little confusing that the name changes here. Better to stay consistent for easier code grepping

2019-02-06 23:10 UTC, calellowitz commented on custom/icds_reports/utils/aggregation_helpers/agg_awc.py
> +        UPDATE "{tablename}" agg_awc SET
Same comment as the other pr about adding more updates. This is going to be an incredibly slow step, if we do all of these bits as separate update queries

2019-02-06 23:10 UTC, calellowitz commented on custom/icds_reports/utils/aggregation_helpers/agg_awc.py
> +        valid_home_visits = valid_home_visits + ut.valid_visits,
same thing about name consistency

2019-02-13 13:49 UTC, calellowitz approved these changes

2019-02-18 09:57 UTC, merged