Only show custom properties for Application doc_type
dimagi/commcare-hq pull request #23292
Opened 2019-02-19 04:39 UTC by emord

Product note: removes custom properties from linked apps (setting them didn't work anyways)

https://github.com/dimagi/commcare-hq/pull/23281#issuecomment-464956632

2019-02-19 14:48 UTC, orangejenny requested changes
This keeps the custom properties themselves from displaying, but you can still see the panel and add properties. Probably need to update `app_manager/partials/settings/commcare_settings.html`

2019-02-20 15:29 UTC, emord commented
Thanks for pointing that out. When I first looked, it seemed like we didn't quite have the app context in that page.

Planning to look again and timebox this to an hour at some point in the next 2 weeks.

2019-02-26 22:35 UTC, emord commented
@orangejenny updated

2019-02-27 05:28 UTC, orangejenny approved these changes

2019-02-27 15:55 UTC, merged