update config_report_icds-cas_static-dashboard_growth_monitor_8f61534c
dimagi/commcare-hq pull request #23301
Opened 2019-02-19 11:01 UTC by sravfeyn

2019-02-20 09:16 UTC, snopoke requested changes

2019-02-20 09:16 UTC, snopoke commented on custom/icds_reports/ucr/data_sources/dashboard/dashboard_growth_monitoring.json
> +          "property_path": ["form", "meta", "userID"]
this needs to be a root doc expression

2019-02-20 09:40 UTC, sravfeyn commented on custom/icds_reports/ucr/data_sources/dashboard/dashboard_growth_monitoring.json
> +          "property_path": ["form", "meta", "userID"]
Fixed it

2019-02-21 08:29 UTC, sravfeyn commented
@snopoke

2019-02-21 09:07 UTC, snopoke approved these changes

2019-02-21 09:07 UTC, merged