Format phone numbers with +91 at the beginning
dimagi/commcare-hq pull request #23447
Opened 2019-02-27 14:07 UTC by dmydlo

Hi @calellowitz,
I have changed the formatting of phone numbers in the tabular reports to start with +91.
Need QA: Yes
Environment: n/a
Locally Tested: Yes
Regards, Dawid.

2019-03-12 18:30 UTC, calellowitz requested changes
Is there a way this could be pulled into a separate util function instead of being defined on all of them.

2019-03-12 18:30 UTC, calellowitz commented on custom/icds_reports/sqldata/exports/pregnant_women.py
> +    def phone_number_fucntion(self, x):
spelling (same on all of them)

2019-03-28 14:48 UTC, calellowitz approved these changes

2019-03-28 15:16 UTC, kaapstorm commented on custom/icds_reports/utils/__init__.py
> +    return "+{0}{1}".format('' if str(x).startswith('91') else '91', x) if x else x
We already use the [phonenumberslite][1] library. You could do this more generically with
```python
    def phone_number_function(x, from_country='IN'):
        number = phonenumbers.parse(x, from_country)
        return phonenumbers.format_number(number, phonenumbers.PhoneNumberFormat.INTERNATIONAL)
```

  [1]: https://github.com/daviddrysdale/python-phonenumbers

2019-03-28 15:21 UTC, kaapstorm commented on custom/icds_reports/utils/__init__.py
> +    return "+{0}{1}".format('' if str(x).startswith('91') else '91', x) if x else x
(That's not to say that you **should**. Use it / don't use it.)

2019-03-29 13:50 UTC, merged

2019-03-29 13:51 UTC, calellowitz commented
Merging for now, to get this out, but @kaapstorm's comments would be a good followup @dmydlo