make multimedia upload an async operation
dimagi/commcare-hq pull request #23643
Opened 2019-03-14 08:14 UTC by sravfeyn

https://dimagi-dev.atlassian.net/browse/ICDS-319

@calellowitz

2019-03-14 11:24 UTC, orangejenny requested changes

2019-03-14 11:24 UTC, orangejenny commented on corehq/apps/hqmedia/views.py
> +            profile_and_process_bulk_upload_zip.delay(processing_id, self.domain, self.app_id,
This one shouldn't use `delay`.

2019-03-15 06:36 UTC, sravfeyn commented on corehq/apps/hqmedia/views.py
> +            profile_and_process_bulk_upload_zip.delay(processing_id, self.domain, self.app_id,
(updated)

2019-03-15 12:50 UTC, orangejenny approved these changes

2019-03-18 05:02 UTC, merged