Use UTC for ICDS aggregation
dimagi/commcare-hq pull request #23747
Opened 2019-03-22 18:07 UTC by emord

best guess for now

2019-03-22 19:22 UTC, nickpell approved these changes

2019-03-22 19:35 UTC, calellowitz requested changes
i think we should change all the other tasks in this file as well

2019-03-25 21:22 UTC, emord commented
@calellowitz I adjusted them by 5 hours (figured it was close enough)

2019-03-26 00:07 UTC, calellowitz commented on custom/icds_reports/tasks.py
> +@periodic_task(run_every=crontab(hour=18, minute=0, day_of_month='12'), acks_late=True, queue='icds_aggregation_queue')
This one needs to run before the aggregation (so 17:30 is probably fine). 5 hours seems good enough for the rest

2019-03-26 02:21 UTC, emord commented on custom/icds_reports/tasks.py
> +@periodic_task(run_every=crontab(hour=18, minute=0, day_of_month='12'), acks_late=True, queue='icds_aggregation_queue')
updated. but should this be part of the groups and chains?

2019-03-26 13:29 UTC, merged

2019-03-26 13:30 UTC, calellowitz commented on custom/icds_reports/tasks.py
> +@periodic_task(run_every=crontab(hour=18, minute=0, day_of_month='12'), acks_late=True, queue='icds_aggregation_queue')
um, maybe. i have mixed feeling about all of the logic that specifies certain things on certain days in the main task, and it is not a strict dependency, but it does make some sense