Merge 10a, 10b MPR UCR reports
dimagi/commcare-hq pull request #23884
Opened 2019-04-03 10:32 UTC by sravfeyn

The two sources use the same data source and are filtered exactly on same fields by MPR report. The only difference is the columns. Merging this avoids the double loading of the same UCR data and same aggregations thereon.

@emord @calellowitz 
@Rohit25negi

2019-04-03 16:16 UTC, emord requested changes
These reports are referenced by the mobile app. If you delete them the restores will fail to return the correct data. You need to add a new report without changing the existing ones

Otherwise I thikn this approach is good and an easy win

2019-04-04 09:29 UTC, sravfeyn commented
Ha, thanks. I enquired on Skype chats before doing this, but no one knew. I added a feature to display apps that refer a UCR report to prevent things like this to some extent. https://github.com/dimagi/commcare-hq/pull/23904

2019-04-04 09:43 UTC, sravfeyn commented
Added the two UCRs back

2019-04-04 16:10 UTC, emord approved these changes

2019-04-04 17:30 UTC, merged