Round expected visits in denominator for home visits in performance r…
dimagi/commcare-hq pull request #23999
Opened 2019-04-11 14:54 UTC by dmydlo

…eport

Hi @Rohit25negi @calellowitz,
I have changed casting to an integer to rounding of the expected visits that are used as a denominator for home visits in the performance report.
These changes are related to JIRA [ICDS-482](https://dimagi-dev.atlassian.net/browse/ICDS-482) ticket.
Need QA: No
Environment: n/a
Locally Tested: Yes
Regards, Dawid

2019-04-11 19:05 UTC, Rohit25negi commented
Weird That this did not affect any test cases?.

2019-04-12 12:53 UTC, Rohit25negi approved these changes
Looks good to me.  Will wait untill @calellowitz  have a look.

2019-04-12 22:57 UTC, calellowitz requested changes
I realize this is what the ticket is asking for, but I do not think that ticket is correct. I think this report should be left as is, going to hold off merging this until the conversation on that ticket is resolved.

2019-04-15 16:00 UTC, calellowitz approved these changes
Confirmed that this is the new behavior, however, as per the stickler warning, this will break in python3.  The rounding behavior changes the round numbers ending in 5 to the nearest even, instead of always up. I will confirm with Heena, whether or not that is ok, but merging for now.

2019-04-15 16:00 UTC, merged