[ICDS] Changed place of allert in the ICDS Dashboard
dimagi/commcare-hq pull request #24247
Opened 2019-05-08 14:52 UTC by lwyszomi

Hi @calellowitz @Rohit25negi 

I changed the place of HQ alerts in the ICDS dashboard, also I had to change an HTML tree to fix a problem with ```position: fixed``` in top menus. I attached screenshot how the dashboard looks after my change.

Need QA: yes
Environment: ICDS
Locally tested: yes

Regards,
Lukasz

![icds-alert](https://user-images.githubusercontent.com/429541/57384870-9b4a5200-71b1-11e9-9365-dc2aa3260b3a.png)

2019-05-08 15:10 UTC, orangejenny commented on custom/icds_reports/static/js/angular-services/baseControllers.service.js
> +            vm.showInfoMessage = function () {
Could this function be extracted into a separate file and shared among the directives?

2019-05-08 15:11 UTC, orangejenny commented on custom/icds_reports/templates/icds_reports/icds_app/awc-opened-yesterday.directive.html
> +    <div class="alert-container" ng-if="$ctrl.showInfoMessage()">
Could this block be extracted into a partial template?

2019-05-09 10:29 UTC, lwyszomi commented
Hi @orangejenny 

I created a new directive for info-message.

Please let me know if you have any questions.

Regards,
Lukasz

2019-05-09 16:30 UTC, orangejenny approved these changes
Thanks Lukasz, this is much more concise.

2019-05-09 16:32 UTC, orangejenny commented
@calellowitz @Rohit25negi I don't know enough about dashboard process to know whether or not to merge this, since it says it needs QA. Leaving that to you to decide/merge.

2019-05-10 06:00 UTC, Rohit25negi commented
@lwyszomi  Did you try it on small resolution screen where person has to scroll up-down. Earlier that was messing for me, when I tried putting banner. If not can you test this?

2019-05-10 06:07 UTC, Rohit25negi requested changes
Left one small change request and one test request. Else Looks good.

2019-05-10 06:07 UTC, Rohit25negi commented on custom/icds_reports/static/js/directives/info-message/info-message.directive.js
> +        return true;
it looks returning returns needs to be corrected. This function is always returning true.

2019-05-10 06:07 UTC, Rohit25negi commented on custom/icds_reports/static/js/directives/info-message/info-message.directive.js
> +        return true;
This will lead the banner to always show

2019-05-10 11:52 UTC, lwyszomi commented
Hi @Rohit25negi,

Thanks you for reminding me that this should looks good on the small resolution, I forgot about this.

small resolution:
![small-resolution](https://user-images.githubusercontent.com/429541/57525379-dae87980-732a-11e9-89fd-d5f5aa697af4.gif)

big resolution:
![big-resolution](https://user-images.githubusercontent.com/429541/57525388-e0de5a80-732a-11e9-89a3-e3e25710e606.png)

Please let me know if you have any questions.

Regards,
Lukasz

2019-05-10 11:59 UTC, lwyszomi commented
hold of merge

2019-05-10 12:30 UTC, Rohit25negi commented
adding do not merged tag based on lukasz last comment

2019-05-10 15:59 UTC, lwyszomi commented
@Rohit25negi ready for review and merge.

2019-05-14 09:29 UTC, Rohit25negi commented
Will there be two alerts on Icds if its 1st of the month and because of some error on dashboard we also applied one  alert message?

2019-05-14 09:37 UTC, Rohit25negi approved these changes
Looks good to me

2019-05-14 09:39 UTC, Rohit25negi commented
This looks good. Only one questions. Is this needs to be under FF or to be released without FF?

2019-05-17 13:18 UTC, Rohit25negi commented
Ok Merging this based on the go ahead without FF on the ticket, https://dimagi-dev.atlassian.net/browse/ICDS-463.

2019-05-17 13:19 UTC, Rohit25negi commented
Also @lwyszomi  its always good to add the ticket in the PR to add more context who don't know. I would really appreciate If you can do that in future PRs.

2019-05-17 13:20 UTC, merged