Fix error when there is large exponent
dimagi/commcare-hq pull request #24461
Opened 2019-05-30 15:15 UTC by emord

https://sentry.io/organizations/dimagi/issues/1044666856/?cursor=0%3A100%3A0&project=136860&referrer=slack Someone's GPS accuracy is extremely large (6.1743444E7) and this code is choking on it because its trying to compare that exponent value with '61743444' which means they're going ot be blocked on submitting at least one form.

This string comparison code pre-existed https://github.com/dimagi/commcare-hq/pull/15405/ and I can't tell what the sentry error was there because the error has been deleted, but I'm assuming it was to catch `InvalidOperation` which I think/hope should catch a super-set of errors compared to this string comparison.

@snopoke @calellowitz fyi since you are the last who touched this a couple years ago

2019-05-30 15:24 UTC, kaapstorm approved these changes

2019-05-30 18:44 UTC, calellowitz reviewed
This seems dangerous. That clause was the original one the exception was added for. Do we know why decimals are supposed to be canonically formatted, and what issues they could cause if not?

2019-05-30 18:56 UTC, calellowitz commented
perhaps @dannyroberts does as he was the original committer for this https://github.com/dimagi/commcare-hq/commit/b5d3f6209786b8f63fd25f5acacb6f71137bc5e0 (and worked on some bugs related to it https://github.com/dimagi/commcare-hq/commit/b5d3f6209786b8f63fd25f5acacb6f71137bc5e0)

2019-06-03 19:12 UTC, calellowitz requested changes
changing my review to request changes so it is clear that I think there are open questions and no one comes by and merges by mistake

2019-06-06 16:13 UTC, dannyroberts commented
I took a look at this change, the current code, and the original code @calellowitz, and the story I have is this:
- when i first added the error, I think it was just out of a sense of restricting input to exactly what I expected
- I later realized, sometimes we get decimals in E notation when the value's very small, so I made an exception for that that rounded it, but we didn't loosen the overall restriction that the input already be canonically formatted in other cases
- Now it looks like the E notation isn't just for very small numbers either, and these numbers' canonical format differs from the input format (though `Decimal` _does_ accept this different input format)

I think the original restriction wasn't necessary. I think this is a good change, and I don't think it will cause any issues

2019-06-06 16:13 UTC, dannyroberts approved these changes

2019-06-06 17:35 UTC, calellowitz approved these changes

2019-06-06 17:35 UTC, calellowitz commented
Thanks for looking into this @dannyroberts

2019-06-06 17:39 UTC, merged