Query fact sheet on Same level which is requested
dimagi/commcare-hq pull request #24772
Opened 2019-07-09 16:41 UTC by Rohit25negi

previously what was happening is if the when the report is fetched, the database is queried for a level below. i.e is state level is pulled then the database is queried at the level of the district. which was increasing the response time. This code change will allow to query the database at same level(expect National level).
https://dimagi-dev.atlassian.net/browse/ICDS-296

2019-07-09 16:43 UTC, Rohit25negi commented on custom/icds_reports/views.py
>          config.update(get_location_filter(location, domain))
`get_location_filter` sets the aggregation_level   to + 1 to the actual one.

2019-07-22 04:23 UTC, Rohit25negi commented
@calellowitz  @emord  can I please a review on this one ? It's a quick one

2019-07-22 18:02 UTC, calellowitz requested changes
Couple questions:
1) What happens when the national one is loaded (so the aggregation level is `0`)?
2) How does this determine what to group by, is it related at all to the aggregation level passed in?

2019-07-23 08:49 UTC, Rohit25negi commented
> Couple questions:
> 
> 1. What happens when the national one is loaded (so the aggregation level is `0`)?
> 2. How does this determine what to group by, is it related at all to the aggregation level passed in?

1. On national level Aggregation level remain 1 and the data is summed up for all state at agg level 1

2. yes query is related to aggregation level very much. Though It uses the aggregation level in `where` clause. It Only group by month with location and aggregation in the where clause.

2019-07-23 14:02 UTC, calellowitz commented
> On national level Aggregation level remain 1 and the data is summed up for all state at agg level 1

How is this true? You have subtracted 1 from all aggregation levels passed in, wont that also then subtract 1 from the national query (which used to be occurring at state level, agg level 1), making it have `aggregation_level=0`

> yes query is related to aggregation level very much. Though It uses the aggregation level in where clause. It Only group by month with location and aggregation in the where clause.

Cool, i think this makes sense to me now

2019-07-23 17:29 UTC, Rohit25negi commented
> > On national level Aggregation level remain 1 and the data is summed up for all state at agg level 1
> 
> How is this true? You have subtracted 1 from all aggregation levels passed in, wont that also then subtract 1 from the national query (which used to be occurring at state level, agg level 1), making it have `aggregation_level=0`

It wont make it 0 as its under a if statement. get_location_filter function set the aggregation_level=1 when the National level is selected.
@calellowitz

2019-07-23 19:20 UTC, calellowitz commented
I see, looks good

2019-07-23 19:20 UTC, calellowitz approved these changes

2019-07-23 19:20 UTC, merged