AWW report year/month dropbox restrictions added
dimagi/commcare-hq pull request #24832
Opened 2019-07-15 10:41 UTC by dborowiecki

Hi @calellowitz @Rohit25negi

I updated year/month dropbox options in AWW report, TICKET: https://dimagi-dev.atlassian.net/browse/ICDS-675

Need QA: no
Environment: ICDS
locally tested: yes

2019-08-27 05:44 UTC, Rohit25negi requested changes
Left One Comment. @dhiraj-beehyv  It looks you will be handling this PR Since Lukaz has left

2019-08-27 05:44 UTC, Rohit25negi commented on custom/icds_reports/static/js/directives/download/download.directive.js
> +                        vm.selectedMonth = 12;
Should not it be set to october. as the ticket says that 'We want the filter options to be available from October 2018'

2019-08-27 05:44 UTC, Rohit25negi commented on custom/icds_reports/static/js/directives/download/download.directive.js
> +                        vm.selectedMonth = 12;
It currently looks that it sets to December.

2019-08-27 06:08 UTC, Rohit25negi requested changes
@dhiraj-beehyv  can you also test this locally. The expected behaviour from the ticket is that the report should be available from oct 2018. and the year and month filter should behave accordingly

2019-09-13 12:37 UTC, dborowiecki commented
Changes implemented in [this PR](https://github.com/dimagi/commcare-hq/pull/25250). Closing.

2019-09-13 12:37 UTC, closed without merging