[ICDS Dashboard] awc data changed from daily table to monthly table in
dimagi/commcare-hq pull request #25008
Opened 2019-08-05 03:37 UTC by dhiraj-beehyv

[Jira Ticket](https://dimagi-dev.atlassian.net/browse/ICDS-747)

Changes for pulling the "AWC launched" from the monthly table instead of the daily table. 

@Rohit25negi, I didn't remove the data being fetched from daily table as it is seems to be used in "Number of AWCs open yesterday" card. Can you please have a look and give some guidance on it.

The tests didn't break so I didn't had to make any changes.

2019-08-06 13:11 UTC, Rohit25negi requested changes
Looks fine. left One change request.

2019-08-06 13:11 UTC, Rohit25negi commented on custom/icds_reports/reports/cas_reach_data.py
> +                    'value': get_value(awc_this_month_data, 'awcs'),
this column is not more needed you should removed: 
https://github.com/dimagi/commcare-hq/pull/25008/files#diff-50b8c0baaef34ca763dda94410624738R42

2019-08-08 09:19 UTC, Rohit25negi commented
@dhiraj-beehyv Pinging for the change.

2019-08-13 02:55 UTC, dhiraj-beehyv commented
@Rohit25negi , I've updated the pr with the changes. Please have a look.

2019-08-14 09:13 UTC, Rohit25negi requested changes
Can you please put this change under the feature flag

2019-08-14 09:13 UTC, Rohit25negi commented on custom/icds_reports/reports/cas_reach_data.py
> +            'all': get_value(awc_this_month_data, 'awcs'),
@dhiraj-beehyv  can you put these under feature flag. `pre_release_features` variable(boolean) in its caller function should have that info.

2019-08-16 06:06 UTC, dhiraj-beehyv commented
Hi @Rohit25negi ,

Should I put both getting the data from the daily table and the change you requested under the feature flag?

2019-08-23 11:15 UTC, calellowitz requested changes
Looks good to me but it looks like rohit left one comment

2019-08-26 03:12 UTC, dhiraj-beehyv commented
@calellowitz ,

I've updated the pr with changes which Rohit requested (putting the changes under the feature flag)

2019-08-26 11:48 UTC, calellowitz approved these changes

2019-08-27 06:51 UTC, Rohit25negi approved these changes
Thanks for working on this. Waiting for the build to complete. Will merge after it.

2019-08-27 06:51 UTC, Rohit25negi commented on custom/icds_reports/reports/cas_reach_data.py
> +                    'value': get_value(awc_this_month_data, 'awcs'),
@dhiraj-beehyv feature flag check will also be applied to this line same as what you did on 86 line.

2019-08-27 06:51 UTC, Rohit25negi commented on custom/icds_reports/reports/cas_reach_data.py
> +                    'value': get_value(awc_this_month_data if pre_release_features else daily_yesterday, 'awcs'),
it should be more like
`daily_yesterday if pre_release_features and current_month_selected else awc_this_month_data`
@dhiraj-beehyv

2019-08-27 09:04 UTC, merged