combine multiple case-updates in one form
dimagi/commcare-hq pull request #26105
Opened 2019-12-03 10:25 UTC by sravfeyn

Attempting one piece of https://dimagi-dev.atlassian.net/browse/IIO-502

2019-12-03 10:33 UTC, sravfeyn commented on corehq/apps/callcenter/sync_user_case.py
> +            self._tasks_to_trigger = (add_inferred_export_properties, (
Doesn't really apply here

2019-12-03 10:50 UTC, snopoke requested changes

2019-12-03 10:50 UTC, snopoke commented on corehq/apps/callcenter/sync_user_case.py
> +                task.delay(task_args))
how about moving this to a function on the helper that can be called here and in `commit` that would keep it encapsulated in the class

2019-12-03 10:50 UTC, snopoke commented on corehq/apps/callcenter/sync_user_case.py
> +        case_blocks = [h._case_block_to_submit for h in helpers if h]
```suggestion
        case_blocks = itertools.chain([h.get_case_blocks() for h in helpers if h])
```

Then you can move the next line into the `get_case_blocks` function and you won't be accessing a private field

2019-12-04 08:01 UTC, snopoke approved these changes

2019-12-04 17:09 UTC, millerdev requested changes
Don't know why stickler got so confused on this PR. I deleted a bunch of comments because they were making it very hard to review.

2019-12-04 17:09 UTC, millerdev commented on corehq/apps/callcenter/sync_user_case.py
>      if config.enabled and config.config_is_valid():
There's a smell in having this function implicitly return `None` when this condition evaluates to false. In the process of trying to think of a better solution I ended up doing some refactoring (https://github.com/dimagi/commcare-hq/pull/26118). I think the comments on that PR demonstrate why this one is not safe to merge.

2019-12-10 10:21 UTC, sravfeyn commented
Hi @millerdev I have updated the code to make it pretty much logically consistent with the way it was, except in the combined case. Apart from the DRYness of commit/commit_multiple, is there any issue that you see related to the locks in this PR anymore?

2019-12-10 20:05 UTC, millerdev commented
> Apart from the DRYness of commit/commit_multiple, is there any issue that you see related to the locks in this PR anymore?

Yes. It is using different values for critical section lock keys, which is a significant change from the original design. Without a much deeper analysis I can only conclude that such a change is not safe. `commit_multiple` is especially unsafe as explained in https://github.com/dimagi/commcare-hq/pull/26118#discussion_r354304346.

2019-12-11 09:04 UTC, snopoke commented
@millerdev I think your original concern was that things were not happening inside the lock, this has now been changed. The comment you reference says that locking used to be on `owner_id` which is not true, the locking previously was on `case_type, user_id`. I think changing that to `user_id` is safe.

@sravfeyn is there a reason not to include the changes from https://github.com/dimagi/commcare-hq/pull/26118?

2019-12-11 09:48 UTC, sravfeyn commented
> @sravfeyn is there a reason not to include the changes from #26118?

I have now included some part of that PR (yielding instead of returning None). The only thing I didn't include is combining `commit` and `commit_multiple`. Personally, I prefer the ease of readability of separate functions over the little DRYness when combined. But happy to change if you both feel that's not true.

2019-12-11 11:48 UTC, snopoke commented
Personally I think the combined version is very readable - especially if assertion logic is simplified (I think you only need to check that the there is only 1 user ID being changed (change `_UserCaseHelper.owner_id` to `_UserCaseHelper.user_id` since `owner_id` is not used)

2019-12-11 19:38 UTC, millerdev commented
I got confused while writing #26118 because multiple different lock keys were being used (see https://github.com/dimagi/commcare-hq/pull/26118#discussion_r356786413). Right now the lock key in this PR is still different than it was before:

```diff
- old key: 'user_case_%s_for_%s' % (case_type, commcare_user._id)
+ new key: "sync_user_case_for_%s" % user_id
```

I do not think this change is necessary and is possibly unsafe for a sort period during/after deploy. Maybe that's not a big deal?

I think I can sign off on this once the changes suggested in https://github.com/dimagi/commcare-hq/pull/26105#issuecomment-564505371 have been implemented.

2019-12-12 09:24 UTC, sravfeyn commented
@snopoke @millerdev Unified

2019-12-12 13:58 UTC, snopoke approved these changes

2019-12-12 15:28 UTC, millerdev commented
@snopoke does the lock key change not seem like an issue to you?

2019-12-12 18:28 UTC, snopoke commented
@millerdev I'm not concerned about the locking changes given the low frequency of these and that there is already locking at the case level + the fact that repeated calls will almost certainly not conflict with each other in terms of the changes that are being made

2019-12-12 18:33 UTC, snopoke commented on corehq/apps/callcenter/sync_user_case.py
>          )
```suggestion
        ))
```
*** Error compiling 'corehq/apps/callcenter/sync_user_case.py'...
  File "corehq/apps/callcenter/sync_user_case.py", line 72
    self._user_case_changed(fields)
       ^
SyntaxError: invalid syntax

2019-12-12 18:35 UTC, millerdev approved these changes

2019-12-24 05:55 UTC, merged