add columns for data pull
dimagi/commcare-hq pull request #26111
Opened 2019-12-03 20:11 UTC by mkangia

Add 4 columns to the view to help easy monthly data pull for ICDS.
Example where this can be used: Combine https://github.com/dimagi/commcare-hq/pull/26110/files#diff-9062393ba2f429d7e000ac60dc62ac8aR97 in the query above it

2019-12-04 04:17 UTC, Rohit25negi requested changes
Overall looks good. Left one comment.

2019-12-04 04:17 UTC, Rohit25negi commented on custom/icds_reports/migrations/sql_templates/database_views/agg_awc_monthly.sql
> +        "agg_awc"."stadiometer" AS "stadiometer",
hey, @mkangia can you also add these columns to its django model view. here https://github.com/dimagi/commcare-hq/blob/master/custom/icds_reports/models/views.py#L365

2019-12-04 04:31 UTC, Rohit25negi requested changes

2019-12-04 04:31 UTC, Rohit25negi commented on custom/icds_reports/migrations/sql_templates/database_views/agg_awc_monthly.sql
>      FROM "public"."awc_location_months_local" "awc_location_months"
it will also be helpful you other datapull queries if you add the state_is_test column so that you can filter out the state columns easily

2019-12-04 16:23 UTC, mkangia commented
Thanks @Rohit25negi , updated.

2020-01-21 11:19 UTC, Rohit25negi approved these changes
Looks good.

2020-01-21 13:16 UTC, merged