Sb/create mig form ucr
dimagi/commcare-hq pull request #26240
Opened 2019-12-17 09:49 UTC by ShubhamBansal1997

##### SUMMARY

This PR is made to add a new UCR for the Migration Form, this is the sub task of this JIRA ticket https://dimagi-dev.atlassian.net/browse/ICDS-1025

##### FEATURE FLAG

##### PRODUCT DESCRIPTION

2019-12-18 04:59 UTC, Rohit25negi requested changes
I think problem is here.

2019-12-18 04:59 UTC, Rohit25negi commented on settings.py
> +    os.path.join('custom', 'icds-reports', 'ucr', 'data_sources', 'migrations_form.json'),
hey, I think problem is here. Its not `icds-reports`, Its `icds_reports`

2019-12-18 14:36 UTC, czue commented
I don't think I have the right context to review this so will defer to @Rohit25negi

2019-12-20 04:50 UTC, Rohit25negi requested changes
Just formating nits! Else looks good. 
We might also need to consider the migrated_in case.

2019-12-20 04:50 UTC, Rohit25negi commented on custom/icds_reports/ucr/data_sources/migrations_form.json
> +			{
nitpick: can you fix the formating

2019-12-20 05:00 UTC, Rohit25negi requested changes
can you also make this UCR distributed. If you want to see the example. you can refer https://github.com/dimagi/commcare-hq/blob/master/custom/icds_reports/ucr/data_sources/adolescent_girl_register_form_ucr.json#L188

2019-12-24 04:56 UTC, Rohit25negi requested changes

2019-12-24 04:56 UTC, Rohit25negi commented on custom/icds_reports/ucr/data_sources/migrations_form.json
> +        "create_index": true,
I think this property is not required here as its creating  a primary key on supervisor_id and timeend.

2019-12-26 07:00 UTC, Rohit25negi approved these changes

2019-12-26 07:04 UTC, merged