[ICDS Dashboard] Removed the feature flag for ICDS-904
dimagi/commcare-hq pull request #26532
Opened 2020-01-30 11:36 UTC by challabeehyv

https://dimagi-dev.atlassian.net/browse/ICDS-905

##### SUMMARY
Removed feature flag for ICDS-904 - Use awc daily table on demographics page(program summary and awc report both) instead of daily table(UNDER Feature flag). Merged the retreieval of adolscent girls info to older data. Removed the unwanted tests

##### FEATURE FLAG
No

2020-02-14 08:00 UTC, Rohit25negi requested changes
A few cleanup comments

2020-02-14 13:02 UTC, challabeehyv commented on custom/icds_reports/reports/awc_reports.py
>          del config['date']
removed

2020-02-14 13:02 UTC, challabeehyv commented on custom/icds_reports/reports/demographics_data.py
>          del config['date']
removed

2020-02-17 10:46 UTC, Rohit25negi approved these changes

2020-02-17 10:46 UTC, merged