put yes/no for cbe and vhnd in SDR
dimagi/commcare-hq pull request #26753
Opened 2020-03-02 11:44 UTC by Rohit25negi

Fixes QA Ticket: https://dimagi-dev.atlassian.net/browse/QA-1063
Add text(Yes/No) instead of the number(0/1)

2020-03-03 01:13 UTC, calellowitz requested changes

2020-03-03 01:13 UTC, calellowitz commented on custom/icds_reports/reports/service_delivery_report.py
> +                        'Anganwadi center conducted at least 2 CBEs?',
its probably safer to match these on the column names, since those are less likely to change than the text

2020-03-08 12:49 UTC, Rohit25negi commented
@calellowitz  your requested changed were done on this. Does this look good to you now?

2020-03-09 17:23 UTC, calellowitz approved these changes

2020-03-09 17:23 UTC, merged