Enable the reconcilation script to rebuild cases as well
dimagi/commcare-hq pull request #26786
Opened 2020-03-05 12:12 UTC by Rohit25negi

condition `if doc_id not in docs_in_ucr:` was only allowing the missing forms to rebuild not the outdated cases. Because cases can be existing in the UCR and yet get outdated. 
This is identified while debugging this ticket: https://dimagi-dev.atlassian.net/browse/ICDS-1290.

I found that there were some child cases that are open in the UCR and their corresponding person case in the UCR is closed. But in the HQ both child health case and its person case is closed.
I tried republishing the close form of one child case and it successfully reached to the ucr. So I think its just a general case of cases-updates not reaching to UCR same as forms and not specific to person and child case. 
 
After this is merged, This reconciliation script will need to rerun only for cases

2020-03-05 12:14 UTC, Rohit25negi commented on custom/icds_reports/tasks.py
> +                    if sql_modified_on - ucr_doc[1] >= timedelta(seconds=-1):
Added this `if` condition based on my best understanding of the time drifts between the database. Refering (https://github.com/dimagi/commcare-hq/blob/master/custom/icds_reports/management/commands/stale_data_in_ucr.py#L102) which may be wrongly handling it

2020-03-05 23:08 UTC, calellowitz requested changes
I think there are some possible performance problems with this code that can be addressed while also simplifying the logic a bit

2020-03-05 23:08 UTC, calellowitz commented on custom/icds_reports/tasks.py
> +            in_ucr = False
Might be good to also include your comment in my suggested change because I agree its a bit confusing

2020-03-06 05:15 UTC, Rohit25negi commented
@calellowitz  Simplified the code as suggested, please check

2020-03-06 16:38 UTC, calellowitz approved these changes

2020-03-06 16:38 UTC, calellowitz commented on custom/icds_reports/tasks.py
> +        doc_id_and_inserted_in_ucr = _get_docs_in_ucr(domain, status_record.table_id, doc_ids)
merging this now so we can get it out but can you change this name back. I think the new name is much more confusing that the old.

2020-03-06 16:38 UTC, merged