[ICDS Dashboard] Added number of household members in demographics tabular reports
dimagi/commcare-hq pull request #26902
Opened 2020-03-19 07:44 UTC by challabeehyv

https://app.asana.com/0/0/1143121160741089/f

##### SUMMARY
Added number of household members in demographics tabular reports

##### FEATURE FLAG
YES - ICDS: Enable access to pre-release features in the ICDS Dashboard reports

2020-03-19 07:46 UTC, challabeehyv commented
[Demographics (1).xlsx](https://github.com/dimagi/commcare-hq/files/4353229/Demographics.1.xlsx)
with feature flag ON

2020-03-19 07:46 UTC, challabeehyv commented
[Demographics (4).xlsx](https://github.com/dimagi/commcare-hq/files/4353231/Demographics.4.xlsx)
with feature flag OFF

2020-03-30 07:53 UTC, Rohit25negi requested changes

2020-03-30 07:53 UTC, Rohit25negi commented on custom/icds_reports/sqldata/exports/demographics.py
> +        if self.beta:
can you add a test case for this?

2020-04-21 10:30 UTC, Rohit25negi approved these changes
looks good. gtg once the test cases passed. Can you also update the ticket that this needs testing from GS team and  this is going under the feature flag for now. @challabeehyv

2020-04-22 06:36 UTC, merged