Bihar API mother table
dimagi/commcare-hq pull request #27183
Opened 2020-04-16 12:44 UTC by Rohit25negi

This pr creates the API for the Bihar API to fetch the mother details. This is the usual flow of steps we follow:
1. creating a model
2. aggregate it.
3. pull the data
4. create the endpoint

2020-04-16 14:34 UTC, Rohit25negi commented on custom/icds_reports/tasks.py
> +    _agg_bihar_api_demographics.delay(current_month)
delay because. I will be kicking it off via airflow only and don't want this to block the aggregation completion time.

2020-04-16 14:35 UTC, Rohit25negi commented on custom/icds_reports/tests/agg_tests/fixtures/person_cases.csv
> +fb1ad76b-dbba-4d60-8ea3-536455d20f00,2017-07-01 0:00:00,a11,s3,b2,d1,st1,2017-01-04 0:00:00,,test_husband_name,F,1992-04-10,,24,,1,,,,,,,,,,,0,1,,,1,,,,,,,,,
this fixture change is intentional to focused testing

2020-04-17 16:09 UTC, calellowitz requested changes
one blocking change, rest looks fine, but i think we will need to figure out indexing for the db

2020-04-17 16:09 UTC, calellowitz commented on custom/icds_reports/utils/aggregation_helpers/distributed/ccs_record_monthly.py
> +            LEFT OUTER JOIN "{add_preg_ucr}" preg ON (
same point about indices if you expect this to be slow

2020-04-17 16:09 UTC, calellowitz commented on custom/icds_reports/views.py
> +@method_decorator([api_auth, toggles.ICDS_BIHAR_DEMOGRAPHICS_API.required_decorator()], name='dispatch')
nit: may want to rename this flag if its used for more than the demographics api

2020-04-17 16:19 UTC, Rohit25negi commented on custom/icds_reports/reports/bihar_api.py
> +    classes = {
Yes

2020-04-18 03:13 UTC, Rohit25negi commented on custom/icds_reports/migrations/sql_templates/database_views/bihar_api_mother_view.sql
> +    LEFT JOIN "public"."bihar_api_demographics"
final query plan after the index creation:
```

commcare_ucr_citus=# EXPLAIN SELECT "bihar_api_mother_view"."person_id", "bihar_api_mother_view"."ccs_case_id" FROM "bihar_api_mother_view" WHERE ("bihar_api_mother_view"."month" = '2017-05-01' AND "bihar_api_mother_view"."state_id" = 'st1' AND "bihar_api_mother_view"."ccs_case_id" > '') ORDER BY "bihar_api_mother_view"."ccs_case_id" ASC;
                                                                                                    QUERY PLAN                                                                                                    
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Sort  (cost=0.00..0.00 rows=0 width=0)
   Sort Key: remote_scan.ccs_case_id
   ->  Custom Scan (Citus Real-Time)  (cost=0.00..0.00 rows=0 width=0)
         Task Count: 32
         Tasks Shown: One of 32
         ->  Task
               Node: host=citus_worker1 port=5432 dbname=commcare_ucr_citus
               ->  Nested Loop  (cost=0.29..16.94 rows=1 width=64)
                     ->  Append  (cost=0.14..8.76 rows=1 width=68)
                           ->  Index Scan using "bihar_api_demographics_2017-05-01_108378_pkey" on "bihar_api_demographics_2017-05-01_108378" bihar_api_demographics  (cost=0.14..8.75 rows=1 width=68)
                                 Index Cond: (month = '2017-05-01'::date)
                                 Filter: (state_id = 'st1'::text)
                     ->  Index Only Scan using crm_supervisor_person_month_idx_102360 on ccs_record_monthly_102360 ccs_record_monthly  (cost=0.14..8.17 rows=1 width=100)
                           Index Cond: ((supervisor_id = bihar_api_demographics.supervisor_id) AND (person_case_id = bihar_api_demographics.person_id) AND (month = '2017-05-01'::date) AND (case_id > ''::text))
(14 rows)
```

2020-04-18 16:51 UTC, calellowitz approved these changes

2020-04-18 18:56 UTC, merged