[ICDS Dashboard]: past data correction due to missing thr forms
dimagi/commcare-hq pull request #27206
Opened 2020-04-20 12:02 UTC by ShubhamBansal1997

##### SUMMARY

##### FEATURE FLAG

##### PRODUCT DESCRIPTION
https://dimagi-dev.atlassian.net/browse/ICDS-1391

2020-04-21 12:34 UTC, Rohit25negi requested changes
generally looks good. left one query correction comment. Also, it would be a lot easier to review if the query could be separated out in SQL file.

2020-04-21 12:34 UTC, Rohit25negi commented on custom/icds_reports/management/commands/fix_missing_thr_forms.py
> +    FROM awc_location_local awc_location
why do you need this join?

2020-04-21 12:34 UTC, Rohit25negi commented on custom/icds_reports/management/commands/fix_missing_thr_forms.py
> +    awc_location.state_id as state_id,
is it required to have all these location fields except awc_id which is already present in  thr table

2020-04-21 12:34 UTC, Rohit25negi commented on custom/icds_reports/management/commands/fix_missing_thr_forms.py
> +        GROUP BY state_id, district_id
it will be group by state_id.

2020-04-21 15:09 UTC, ShubhamBansal1997 commented
@Rohit25negi since the queries are small, that's why I go for a single file only. Would take care in future to keep separate files!!

2020-04-23 11:04 UTC, Rohit25negi requested changes
left two comments. Overall looks good.

2020-04-23 11:04 UTC, Rohit25negi commented on custom/icds_reports/management/commands/fix_missing_thr_forms.py
> +        date = options["date"] if options["date"] else "2020-09-01"
hey, its default to `2019-09-01` not 2020

2020-04-23 11:04 UTC, Rohit25negi commented on custom/icds_reports/management/commands/fix_missing_thr_forms.py
> +    WHERE t.awc_id = ut.awc_id AND t.month = ut.month;
can you add a filter here. where ut.month=`<month>`

2020-04-23 14:38 UTC, calellowitz requested changes
How are you testing these data correction scripts? The fact that it looks like it won't run at all makes me concerned, because it implies that it has never been run. This is going to modify live data on the system, so it needs to be tested to ensure it works correctly, before we run it on our production data. As does every data correction script.

2020-04-23 14:38 UTC, calellowitz commented on custom/icds_reports/management/commands/fix_missing_thr_forms.py
> +    UPDATE "agg_awc_{month}_5" t
I don't think this will work, you are trying to update a local table from a distributed table.

2020-04-23 14:38 UTC, calellowitz commented on custom/icds_reports/management/commands/fix_missing_thr_forms.py
> +        intervals = final_date.month - initial_date.month + 12 * (final_date.year - initial_date.year) + 1
I have mentioned this in other PRs but I think this method is hard to reason about and overcomplicates what is really a simple operation. This set of things can mostly be reduced to
```
date = start_date
while date < end_date:
    update_data(date)
    date = date + relativedelta(months=1)
```

2020-04-23 14:38 UTC, calellowitz commented on custom/icds_reports/management/commands/fix_missing_thr_forms.py
> +        final_date = datetime.now()
this should probably be a date not a datetime

2020-04-23 14:38 UTC, calellowitz commented on custom/icds_reports/management/commands/fix_missing_thr_forms.py
> +                icds_state_aggregation_task(state_id=state_id, date=monthly_date,
i don't know how long this step takes, but this runs each state sequentially in a blocking way each month. Even if its only a few minutes per state (say 2), thats still over an hour per month

2020-04-23 14:51 UTC, Rohit25negi approved these changes
meant to approve a few hours back. I thought I clicked this. but apparently did not

2020-04-29 16:16 UTC, closed without merging