[ICDS Dashboard]: Custom data pull
dimagi/commcare-hq pull request #27219
Opened 2020-04-21 14:44 UTC by ShubhamBansal1997

##### SUMMARY

https://app.asana.com/0/1170926687436985/1172140180002393/f

##### FEATURE FLAG

##### PRODUCT DESCRIPTION

2020-04-22 07:01 UTC, Rohit25negi requested changes
left a few minor comments

2020-04-22 10:30 UTC, Rohit25negi requested changes
Left some final comments.

2020-04-22 10:30 UTC, Rohit25negi commented on custom/icds_reports/management/commands/national_user_data_pull.py
> +        for user in users:
you will also need to append users from 'Webuser.by_domain('icds-cas')` to include the webusers(eg. dimagi users)

2020-04-22 10:30 UTC, Rohit25negi commented on custom/icds_reports/management/commands/national_user_data_pull.py
> +                print(usage)
This will flood the terminal. Could you add more useful log messages

2020-04-22 10:30 UTC, Rohit25negi commented on custom/icds_reports/management/commands/national_user_data_pull.py
> +            if user.has_permission('icds-cas', 'access_all_locations'):
it turns out that finding national level is trickier. I think a better condition would be:
```
if ((len(user.assigned_location_ids)==0 or 'cpmu' in user.username.tolower() ) and user.has_permission('icds-cas', 'access_all_locations')):
```

2020-04-22 15:35 UTC, calellowitz commented
@ShubhamBansal1997 can you give this PR a more descriptive name. its hard to tell what it does from the PR list (or email notifications)

2020-04-22 17:36 UTC, ShubhamBansal1997 commented
@calellowitz Updated!!

2020-04-23 15:07 UTC, Rohit25negi approved these changes
Meant to approve this earlier but realized did not click the approve button

2020-04-29 16:16 UTC, closed without merging