ICDS Dashboard: Adding "not launched" to map legend
dimagi/commcare-hq pull request #27326
Opened 2020-04-30 10:27 UTC by saiprakash-v

https://app.asana.com/0/1172925702295169/1173537631663916
##### SUMMARY

This pr adds "Not Launched" to the fills of the map Legend

2020-05-12 07:19 UTC, saiprakash-v commented
@Rohit25negi This is ready for review

2020-05-12 11:52 UTC, Rohit25negi requested changes
hey looks good. Should this change be under FF?

2020-05-12 11:55 UTC, saiprakash-v commented
> hey looks good. Should this change be under FF?

Yes. Just got confirmation from Nitish. I will update

2020-05-13 10:44 UTC, Rohit25negi commented
@saiprakash-v is it ready to next round of review
?

2020-05-13 10:45 UTC, saiprakash-v commented
> @saiprakash-v is it ready to next round of review
> ?

Yes, I was waiting to inform you after the build succeed

2020-05-13 11:02 UTC, Rohit25negi reviewed
its almost there.  left one comment which is not blocking but good to have. I think single line if statements are usually used when we want to assign the return to some variable. In case of this, no need of that and we can simply use nromal if statement.

2020-05-13 11:02 UTC, Rohit25negi commented on custom/icds_reports/reports/adolescent_girls.py
> +    fills.update({'Not Launched': MapColors.GREY}) if beta else None
could this simply be.
```
if beta:
    fills.update({'Not Launched': MapColors.GREY})

```

2020-05-13 11:03 UTC, Rohit25negi commented
Also, Did you test this locally. Both, the FF is working and the change you expect is working.

2020-05-13 11:30 UTC, saiprakash-v commented
> Also, Did you test this locally. Both, the FF is working and the change you expect is working.

It was working until I merged master and resolved merge conflicts. Must have messed up something :facepalm: . Looking into it

2020-05-26 13:49 UTC, Rohit25negi commented
is this good for next round of review? @saiprakash-v

2020-05-26 13:50 UTC, saiprakash-v commented
> is this good for next round of review? @saiprakash-v

Yes @Rohit25negi

2020-06-08 14:07 UTC, Rohit25negi approved these changes
Looks good. Did you test it locally with/without feature flag for all the pages you made the change on?

2020-06-08 14:29 UTC, saiprakash-v commented
> Looks good. Did you test it locally with/without feature flag for all the pages you made the change on?

Just tested it after updating with latest master code. It is looking good on all the pages with/without feature flag

2020-06-09 11:50 UTC, merged