ICDS Dashboard: LS launched ff removal
dimagi/commcare-hq pull request #27954
Opened 2020-06-26 05:59 UTC by saiprakash-v

https://app.asana.com/0/1181308556651785/1179465415936472
##### SUMMARY

removing feature flag for ls launched in PS and Map views

2020-06-26 07:26 UTC, Rohit25negi requested changes
Change looks good.
Left one question though

2020-06-26 07:26 UTC, Rohit25negi commented on custom/icds_reports/tests/agg_tests/reports/test_icds_cas_reach.py
> +                            'value': 6
Why all these number changed?

2020-06-26 07:35 UTC, saiprakash-v commented on custom/icds_reports/tests/agg_tests/reports/test_icds_cas_reach.py
> +                            'value': 6
date is changed to may 2017

2020-06-27 07:39 UTC, Rohit25negi approved these changes

2020-06-29 11:37 UTC, merged