refactor: use ESQuery instead of raw queries
dimagi/commcare-hq pull request #28264
Opened 2020-07-31 11:38 UTC by sravfeyn

Stripped from the big ES7 PR

@millerdev @snopoke @calellowitz

2020-07-31 14:53 UTC, dannyroberts approved these changes
These are awesome. So much cleaner!

2020-07-31 20:57 UTC, millerdev reviewed
I don't know ES query syntax very well, so it's hard for me to evaluate if these are all equivalent. Do you feel like the test coverage is good enough to verify that?

2020-07-31 23:10 UTC, esoergel requested changes

2020-07-31 23:10 UTC, esoergel commented on corehq/apps/domain/calculations.py
> +        query.case_type(case_type)
```suggestion
        query = query.case_type(case_type)
```

2020-07-31 23:10 UTC, esoergel commented on corehq/apps/data_pipeline_audit/dbacessors.py
> +        es.filters.term("base_doc", "couchuser-deleted" if deleted else "couchuser")
```suggestion
        return es.filters.term("base_doc", "couchuser-deleted" if deleted else "couchuser")
```

2020-07-31 23:10 UTC, esoergel commented on custom/succeed/fields.py
> +            query.user(user._id.lower())
wow that old filter logic was bad.  `subterms` can't be falsy, but it's used in an if/else.  `and` is used to join a list, but that list contains only one filter.

However, I think the owner and user filters need to be joined with a `filters.OR`

2020-08-04 05:38 UTC, sravfeyn commented on corehq/apps/domain/calculations.py
> +    return query.run().total
Thanks!

2020-08-04 10:34 UTC, sravfeyn commented
Thanks for the great comments @esoergel ! Addressed all of them

2020-08-04 10:36 UTC, sravfeyn commented
>  Do you feel like the test coverage is good enough to verify that?

@millerdev There is coverage for couple of them and the others don't have coverage. But these queries are pretty simple and straightforward, specially after Ethan's review

2020-08-04 13:10 UTC, millerdev commented
@sravfeyn If some of them are not covered by tests then I think there is not adequate test coverage to verify that the results are the same for ES2 vs ES7. Would it be hard to add tests for queries that are currently untested?

2020-08-04 18:41 UTC, esoergel approved these changes

2020-08-05 07:11 UTC, sravfeyn commented on corehq/apps/es/forms.py
> +    if not isinstance(user_ids, (list, set, tuple)):
I stumbled upon this in a ES7 test where the data was coming in tuples.

2020-08-05 08:01 UTC, sravfeyn commented
> Would it be hard to add tests for queries that are currently untested?

@millerdev 
Except the custom report  query change (which hasn't been used in last 3 months and a bit hard to add test to) everything else is fairly obvious and small.  So, I am not very keen.

2020-08-05 08:26 UTC, snopoke commented on custom/succeed/fields.py
> +        return [(case['_source']['_id'], case['_source']['full_name']['#value']) for case in results]
you could avoid fetching the full case:

```suggestion
        results = query.values("full_name.#value")
        return [(case['_id'], case['full_name']['#value']) for case in results]
```

2020-08-05 16:45 UTC, esoergel commented on corehq/apps/domain/calculations.py
> +    return CaseES().domain(domain).modified_range(lt=then).is_closed(False).count()
Actually I think `lt` is correct, though the docstring is wrong.  Looks like the docstring was copied from `cases_in_last` above.  This is `inactive_cases_in_last`, which is meant to be cases _not_ modified in however many days.  The raw query had a `must_not` wrapping the "from then to now" logic, equivalent to `.NOT(modified_range(gte=then))`

2020-08-05 20:02 UTC, millerdev commented on corehq/apps/domain/calculations.py
> +    return CaseES().domain(domain).modified_range(lt=then).is_closed(False).count()
@snopoke's suggestion was committed in https://github.com/dimagi/commcare-hq/pull/28264/commits/e64cb569e514b38f85e561eb6e72726673dd18c9. Should that be reverted @esoergel?

2020-08-06 06:56 UTC, sravfeyn commented on corehq/apps/data_pipeline_audit/dbacessors.py
> +        return es.filters.term("base_doc", "couchuser-deleted" if deleted else "couchuser")
Haven't added a test, it's a very basic change.

2020-08-06 06:57 UTC, sravfeyn commented on corehq/apps/domain/calculations.py
> +    return query.count()
Added a test

2020-08-06 06:57 UTC, sravfeyn commented on corehq/apps/domain/calculations.py
> +    return CaseES().domain(domain).modified_range(gte=then).is_closed(False).count()
Added a test

2020-08-06 07:01 UTC, sravfeyn commented on corehq/apps/domain/calculations.py
> +    return CaseES().domain(domain).modified_range(lt=then).is_closed(False).count()
I just came back to say this. I will revert. The docstring is wrong.

2020-08-06 07:05 UTC, sravfeyn commented
@millerdev I have added tests where it makes sense. The custom report is bit more involved to test and hasn't been used since September 2019 and falls under SaaS and is also straightforward change for those with ES context. If you think this is not enough to add a test let me know.

2020-08-06 08:25 UTC, snopoke commented on corehq/apps/domain/calculations.py
> +    return CaseES().domain(domain).modified_range(lt=then).is_closed(False).count()
sorry for the confusion

2020-08-06 11:22 UTC, millerdev approved these changes

2020-08-06 11:36 UTC, millerdev commented
> The custom report is bit more involved to test, hasn't been used since September 2019

Can we remove it?

2020-08-06 11:50 UTC, sravfeyn commented
> Can we remove it?

Unfortunately we can't remove a custom report just based on usage. See Clayton's comment regarding this to a similar question of mine https://dimagi-dev.atlassian.net/browse/SAAS-10957

2020-08-06 13:41 UTC, sravfeyn commented
Thanks for all the feedback guys.

2020-08-06 13:42 UTC, merged