dry edit role modal
dimagi/commcare-hq pull request #28383
Opened 2020-08-17 16:38 UTC by stephherbers

##### SUMMARY
Modified edit_role_modal.html to add a template for Access Areas and Report sections.

https://trello.com/c/bzrYuuZ7/103-dry-up-editrolemodalhtml

2020-08-17 22:10 UTC, calellowitz requested changes
Woohoo first PR and net 200 negative is a strong start! Few small things but looks good

2020-08-18 14:05 UTC, orangejenny reviewed
What beautiful code deletion. Looks good, pending Cal's feedback.

2020-08-18 14:05 UTC, orangejenny commented on corehq/apps/users/static/users/js/roles.js
> +                    srEditAndViewText: gettext("Edit & View Mobile Workers"),
`sr` isn't a common prefix in our js. What would you think of renaming this to either `screenReaderEditAndViewText` or just `editAndViewText`?

2020-08-18 19:26 UTC, stephherbers commented on corehq/apps/users/templates/users/partials/edit_role_modal.html
> +                  <div class="form-check" data-bind="visible: $parent.permissions.edit_commcare_users() && editPermission() && showAllowCheckbox">
Confirmed that is is true for both of the inner checkboxes

2020-08-20 16:04 UTC, calellowitz reviewed
Few small things that aren't blocking and one question. I think stickler is right as well

2020-08-20 16:04 UTC, calellowitz commented on corehq/apps/users/static/users/js/roles.js
> +                        editPermission: function () {return false},
Does this work in the places that refer to `editPermission` rather than `editPermission()`

2020-08-25 03:06 UTC, calellowitz approved these changes
One nit that isn't blocking but would be good to fix in follow up

2020-08-25 03:06 UTC, calellowitz commented on corehq/apps/users/static/users/js/roles_and_permissions.js
> +            DataFileDownloadEnabled: initialPageData.get("data_file_download_enabled"),
nit: these should be lowerCamelCase

2020-08-25 03:06 UTC, merged

2020-08-28 22:01 UTC, esoergel commented
Hi @stephherbers, it looks there's an issue with the scoping in `roles.js`, which makes the dropzone permission stay hidden.  It should appear when that feature flag is enabled, like this:

![image](https://user-images.githubusercontent.com/2367539/91617500-32fb2300-e956-11ea-9e89-224c2ffde148.png)

However, it only displays if `self.DataFileDownloadEnabled == true`.  That's set a bit lower in the file:

https://github.com/dimagi/commcare-hq/blob/0ae9226a6ea37e7aea13461b2f4cb90738bb5902/corehq/apps/users/static/users/js/roles.js#L307

That's a different `self`, though, so that variable is out of scope

2020-08-28 22:01 UTC, calellowitz commented
This had some incorrect logic that caused the two permissions controlled by feature flags to never appear. Fix is https://github.com/dimagi/commcare-hq/pull/28447