[fix] Removed the role condition for the appending custom logo on the apps
dimagi/commcare-hq pull request #28831
Opened 2020-12-02 14:55 UTC by ShubhamBansal1997

## Summary
https://dimagi-dev.atlassian.net/browse/SAAS-11517
On debugging it was found that if a role is not present for a user then the custom logo won't be loaded for that app. The role is not mandatory for users, especially mobile workers. So, removing that condition. 

## Feature Flag

## Product Description

## Safety Assurance

- [ ] Risk label is set correctly
- [ ] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [ ] If QA is part of the safety story, the "Awaiting QA" label is used
- [ ] I am certain that this PR will not introduce a regression for the reasons below

### Automated test coverage

### QA Plan

### Safety story

### Rollback instructions

- [ ] This PR can be reverted after deploy with no further considerations

2020-12-02 16:02 UTC, esoergel requested changes
Can you add a "Product Description" section, since this is a user-facing change?  (It'll go in the deploy summary email).  Can you also update the PR title and description?

This change definitely needs to be tested out, and someone from SaaS will probably want to be aware of it, and may request a QA pass on staging (@dannyroberts ?).  I'll also bring in @orangejenny since USH uses web apps extensively and she wrote [the original](https://github.com/dimagi/commcare-hq/commit/d3c18a434c9ce86563958d4aec38a4680937355c#diff-038c798c3fb4d9875e7ae85cb28457af41e60efa0e2e08fa3ed7df90cb8f613eL134).

2020-12-03 12:47 UTC, ShubhamBansal1997 commented on corehq/apps/cloudcare/views.py
> +        apps = [_format_app(app) for app in apps if app['_id']]
updated!

2020-12-03 19:39 UTC, esoergel approved these changes
Thanks Shubham, this looks correct to me now.  Can you run it through QA on staging since WebApps is such a crucial component right now?

2020-12-07 16:59 UTC, orangejenny approved these changes

2020-12-11 18:41 UTC, merged