use dict instead of wrapped fixture item
dimagi/commcare-hq pull request #30303
Opened 2021-08-27 01:02 UTC by calellowitz

## Summary

This changes our fixture restore code to not wrap `FixtureDataItem`s. For domains with large fixtures, they form the dominant part of restore memory usage. This is in large part due to the fact that we are not able to effectively chunk user fixtures (those where we need to look up ownership of the individual rows). That will likely be much easier when fixtures are in SQL, but in the mean time this provides a fair amount of relief. Wrapping is expensive in both time and memory, and this provides significant improvement in both places.

For a specific user with ~600k fixture rows and ~7k cases (such that almost all restore time was in fixtures), I compared this code to `master`. Memory usage on the restore went from 3.5GB to 1.6GB and time went from 183 seconds to 50 seconds. Notably memory usage on restores seems to be mostly influenced by fixtures, as similar restores in the domain with over 100k cases, but fewer fixture rows had far less memory usage, although longer timing, so this should pull down memory peaks for these domains regardless of casedb size.

## Safety Assurance

- [x] Risk label is set correctly
- [x] All migrations are backwards compatible and won't block deploy
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change
- [x] If QA is part of the safety story, the "Awaiting QA" label is used
- [x] I have confidence that this PR will not introduce a regression for the reasons below

### Automated test coverage

Both the xml serialization function, and the larger fixture generator have automated testing, unmodified in this PR. Restores more generally are also well tested.

### Safety story

I plan to put this on staging, for some added sanity checks.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

2021-08-27 10:17 UTC, snopoke requested changes
Looks good once the comments have been addressed.

2021-08-27 15:18 UTC, snopoke approved these changes

2021-08-31 17:51 UTC, calellowitz commented on corehq/apps/fixtures/fixturegenerators.py
> +    def to_xml(item):
As is our tendency, there are a number of 7 or 8 year old lazy migrations in the `wrap` method, which I think means what your are asking is extremely unlikely, but possible

2021-08-31 22:14 UTC, calellowitz commented on corehq/apps/fixtures/fixturegenerators.py
> +    def to_xml(item):
I added both a `catch` for the `KeyError` and a default value in this method, so we should be good

2021-09-03 19:32 UTC, merged