Create LiveGoogleSheetView
dimagi/commcare-hq pull request #31322
Opened 2022-03-25 09:07 UTC by RynhardPietersen

## Product Description

Adds a new view to export side-bar to allow for user interfacing with gsheets.

## Technical Summary

[This](https://dimagi-dev.atlassian.net/browse/SAAS-13100) ticket was created in order for us to add in a new view in the same style as was done with OData.

## Feature Flag

Google Sheets

## Safety Assurance

### Safety story

Local testing. This is also available to test on staging.

### Automated test coverage

### QA Plan

QA will be done when the entire Google Sheets function is complete

### Migrations

- [x] The migrations in this code can be safely applied first independently of the code

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

2022-03-25 09:09 UTC, RynhardPietersen commented
In [this pr](https://github.com/dimagi/commcare-hq/pull/31310) I mention that I will add in code to fix the hard coded projectlimit for google sheets. Unfortunately that pr is yet to be merged and I was unable to add in that code as of yet. Once it has been merged I will merge master into this branch and add in that code.

2022-03-25 16:48 UTC, biyeun requested changes
great work so far! so happy to see this working end-to-end 🥳 

left a few comments for changes needing to be addressed

2022-03-25 16:48 UTC, biyeun commented on corehq/apps/export/static/export/js/models.js
> +const { contains } = require("jquery");
curious what this was for?

2022-03-25 16:48 UTC, biyeun commented on corehq/apps/export/templates/export/partials/export_list_controller.html
> +        {% include 'export/partials/odata_feed_limit_reached_modal.html' %}
i think the URLs to these partials might need to be updated?

2022-03-25 16:48 UTC, biyeun commented on corehq/apps/export/views/list.py
> +            google_sheet_url = "https://spreadsheets.google.com/feeds/worksheets/{}".format(google_sheet_id)
nit: i think an `f` string would be more readable here

2022-03-25 16:48 UTC, biyeun commented on corehq/apps/export/views/list.py
> +            cls - CreateGoogleSheetFormView
this looks like a syntax error? should be `=`

2022-03-25 16:48 UTC, biyeun commented on corehq/apps/export/templates/export/partials/export_list_controller.html
> +        {% include 'export/partials/odata_feed_limit_reached_modal.html' %}
also need to ensure that they get cleaned up / removed if they are no longer being used

2022-03-25 16:48 UTC, biyeun commented on corehq/apps/export/views/list.py
> +            domain_object = ProjectLimit.objects.get(domain=self.domain)
this needs to be filtered by the gsheet `limit_type`. Also i think `domain_object` doesn't make sense as the variable name here? maybe `project_limit` instead?

2022-03-25 16:48 UTC, biyeun commented on corehq/apps/export/views/list.py
> +        test = IntegrationFormat.is_integration_format(export['export_format'])
i think you want to actually see if the integration format is for live google sheets, not just if it is an integration format?

2022-03-25 16:48 UTC, biyeun commented on corehq/apps/export/views/list.py
> +       id="js-gsheet-track-learn-more"
nit: usually attributes are indented so that they are all in line with the first attribute used (`href`)

2022-04-04 12:51 UTC, RynhardPietersen commented on corehq/apps/export/static/export/js/models.js
> +const { contains } = require("jquery");
I'm not entirely sure...

2022-04-06 19:20 UTC, biyeun commented on corehq/apps/export/templates/export/partials/export_list_controller.html
> +        {% include 'export/partials/odata_feed_limit_reached_modal.html' %}
@RynhardPietersen bump on this one

2022-04-11 13:51 UTC, biyeun commented on corehq/apps/export/static/export/js/models.js
> +        const availableExportFormats = Object.assign({}, constants.EXPORT_FORMATS, constants.INTEGRATED_EXPORT_FORMATS);
did you test these new changes on a regular export to ensure that google sheets doesn't show up in the dropdown? @RynhardPietersen

2022-04-26 17:56 UTC, AddisonDunn commented
Hey @RynhardPietersen, I just merged in a branch that had been used to merge our conflicts on staging. There was only a small conflict for a single line in settings.py. I think I did this correctly but let me know if you notice any problems!

2023-03-08 16:03 UTC, snopoke commented
Closing old PRs, reopen if needed.

2023-03-08 16:03 UTC, closed without merging