HQ permissions for Tableau reports
dimagi/commcare-hq pull request #31659
Opened 2022-05-20 20:43 UTC by orangejenny

## Product Description
https://dimagi-dev.atlassian.net/browse/USH-1938 and https://dimagi-dev.atlassian.net/browse/USH-1939

Review by commit.

This adds permissions for viewing tableau reports. Users can either be granted permissions to all tableau reports, or to specific reports:
![Screen Shot 2022-05-20 at 4 20 48 PM](https://user-images.githubusercontent.com/1486591/169607497-be6739a7-7016-4a1b-afdc-3dba4b3fadcd.png)

This also updates the nav to grant access to the reports section if a user has access to tableau but not to any other reports. A user who only has access to tableau reports sees this (hypothetically they could see an actual report instead of an error message):
![Screen Shot 2022-05-20 at 4 19 18 PM](https://user-images.githubusercontent.com/1486591/169607723-9f52e22f-a7f4-4dab-ae37-19ac8881a492.png)

Their reports dropdown just contains tableau reports:
![Screen Shot 2022-05-20 at 4 19 23 PM](https://user-images.githubusercontent.com/1486591/169607783-173c9e32-09ac-4e9a-877e-264b981f05c8.png)

## Feature Flag
USH: Enable retrieving and embedding tableau visualizations from a Tableau Server

## Safety Assurance

### Safety story
Pretty standard feature extending existing parts of HQ.

### Automated test coverage
There are backend roles/permissions tests. I didn't add anything new.

### QA Plan

Requesting QA.

### Migrations
- [ ] The migrations in this code can be safely applied first independently of the code

No? The migration is to create the new permission, which depends on the code. This is a short migration.

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

Labeled medium risk just because bugs in permissions are bad news.

2022-05-24 15:53 UTC, AddisonDunn requested changes
Very cool, I like how the Tableau permissions were split out from the non-Tableau ones. A couple of blocking concerns with the `couch_user` methods.

2022-05-24 17:42 UTC, orangejenny commented on corehq/apps/reports/views.py
> +            return HttpResponseRedirect(reverse(TableauView.urlname, args=[domain, viz.id]))
We also redirect to the `/a/<domain>/reports/` url in a bunch of places (mostly in breadcrumbs).

2022-05-24 17:49 UTC, orangejenny commented on corehq/apps/reports/standard/tableau.py
> +        if not self.request.couch_user.can_view_tableau_viz(self.domain, f"{self.kwargs.get('viz_id')}"):
Why's that? This is the view for a specific report, so I'm checking the user has access to that report.

2022-05-24 18:47 UTC, AddisonDunn commented on corehq/apps/reports/standard/tableau.py
> +        if not self.request.couch_user.can_view_tableau_viz(self.domain, f"{self.kwargs.get('viz_id')}"):
Sorry, you're right, you'd want a report-specific permission. But where is the `can_view_tableau_viz` permission for a couch user defined?

2022-05-24 19:03 UTC, AddisonDunn commented on corehq/apps/reports/standard/tableau.py
> +        if not self.request.couch_user.can_view_tableau_viz(self.domain, f"{self.kwargs.get('viz_id')}"):
Ok, nevermind, I now see the __getattr__ method in CouchUser ([link](https://github.com/dimagi/commcare-hq/blob/694ce30a29b84ec726fe4c1d6fc05b37899a1911/corehq/apps/users/models.py#L1537)). I'll make a general complaint to nobody that this kind of stuff makes it difficult to understand existing code for an new developer, but now all the permissions methods you're using make sense to me. Feel free to ignore all the related comments and sorry for any confusion I may have caused!

2022-05-24 19:04 UTC, AddisonDunn commented on corehq/apps/reports/models.py
> +            if couch_user.can_view_tableau_viz(domain, f"{viz.id}")
Resolving since I now see how this works (re: other thread).

2022-05-24 19:54 UTC, orangejenny commented on corehq/apps/reports/standard/tableau.py
> +        if not self.request.couch_user.can_view_tableau_viz(self.domain, f"{self.kwargs.get('viz_id')}"):
Totally agreed that getattr method is confusing - I meant to link it earlier but got pulled into something else when I was only partway through your comments.

2022-05-24 21:42 UTC, orangejenny commented on corehq/tabs/tabclasses.py
> +            reports = TableauVisualization.for_user(self.domain, self.couch_user)[:2]
huh, I hadn't noticed that the top nav lost the "View All" option. I'll investigate...that code looks intriguing.

2022-05-25 17:45 UTC, orangejenny commented
@AddisonDunn I believe the blocking feedback is resolved, do you agree? I'm going to do the top nav changes in another PR - I'd like to get this deployed tonight, delivery is interested in starting to use it.

2022-05-25 20:23 UTC, AddisonDunn approved these changes
:)

2022-05-25 20:57 UTC, merged