Change multimedia export to check for duplicates
dimagi/commcare-hq pull request #31840
Opened 2022-06-28 10:55 UTC by RynhardPietersen

## Product Description

## Technical Summary

[This ticket](https://dimagi-dev.atlassian.net/browse/SAAS-13564) contains any relevent explanations.
Some form exports with repeat groups prepare duplicate attachments for download. This should stop the duplicates from downloading. 

## Feature Flag

## Safety Assurance

### Safety story

Tested locally and currently testing on staging.

### Automated test coverage

### QA Plan

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

2022-06-28 18:33 UTC, biyeun commented on corehq/apps/reports/analytics/esaccessors.py
> +            attachment_id = attachment.get('id', 0)
i think the default value of `None` should be fine for getting the `id`?

2022-06-28 18:33 UTC, biyeun commented on corehq/apps/reports/analytics/esaccessors.py
> +            if attachment_id not in unique_attachments:
would then check to see if `attachment_id` is not `None`

2022-06-28 18:36 UTC, biyeun commented on corehq/apps/reports/analytics/esaccessors.py
>  def media_export_is_too_big(es_query):
@RynhardPietersen is it possible to also include tests for this?

2022-07-01 12:53 UTC, RynhardPietersen commented on corehq/apps/reports/tasks.py
> +    unique_attachment_ids = []
Sure, that sounds reasonable.

2022-07-04 03:36 UTC, AmitPhulera requested changes

2022-07-04 15:33 UTC, AmitPhulera approved these changes
Great work @RynhardPietersen 🎉

2022-07-05 13:12 UTC, biyeun approved these changes
looks good!

2022-07-07 08:31 UTC, merged