Embedded tableau explorer access
dimagi/commcare-hq pull request #31974
Opened 2022-08-02 19:40 UTC by AddisonDunn

## Product Description

[USH-2283](https://dimagi-dev.atlassian.net/browse/USH-2283).

This PR will allow different levels of embedded Tableau report permissions so that some HQ users can have edit/explorer access while others have just view access.

This replaces any prior work to get edit permissions up and running. Sorry for any confusion or inconvenience while some of the design/plan around this has been figured out on the fly.

## Technical Summary

Currently, you configure a single Tableau user for a domain and every embedded Tableau view is pulled with that username. This PR will cause HQ to send a username "HQ/{role name}" with the request for the Tableau view. Users will be configured with the desired permissions on the Tableau side.

For example, the role "App Editor" can be given explorer permissions on Tableau by creating a user in Tableau with the username "HQ/App Editor" and giving it explorer permissions. Then, the role "Field Implementer" may be given viewer permissions by creating a user in Tableau with the username "HQ/Field Implementer" and giving it only viewer permissions.

The planned deploy date is Thursday 10/11. Appropriate Tableau users in the BHA domain will be created before then. Note that deploys are usually done ~2am EST and Tableau Server is down during that time, so we don't have to worry about this feature being unusable for a brief period during deploy. 

Two other small things are included:
- Code that closes up a hole in security by making the Tableau config page only configurable by superusers 
- A small bug fix for error messaging on a failed request to get a Tableau report

## Feature Flag

EMBEDDED_TABLEAU

## Safety Assurance

### Safety story

This was tested on staging.

### Automated test coverage

None.

### QA Plan

None, to my knowledge there is no smoke testing for embedded Tableau and the QA team does not have their own Tableau site to test with, although it may soon be time to get that set up. I am going to try to get smoke testing of this set up on staging before deploying.

### Migrations

- [X] The migrations in this code can be safely applied first independently of the code

### Rollback instructions

- [X] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [X] Risk label is set correctly
- [X] The set of people pinged as reviewers is appropriate for the level of risk of the change

2022-08-04 15:59 UTC, orangejenny requested changes
The tabclasses comment is blocking, but that's minor. This looks good.

2022-08-04 15:59 UTC, orangejenny commented on corehq/apps/reports/views.py
> +    @cls_require_superuser_or_contractor
You should also update tabclasses.py so people who don't have access don't see the link in the menu.

2022-08-04 15:59 UTC, orangejenny commented on corehq/apps/reports/standard/tableau.py
> +    tableau_username = f"HQ/{request.couch_user.get_role(domain).name}"
It might be worth catching `DomainMembershipError` here and making sure it's displayed in an intelligible way - I think right now it will just 500.

2022-08-04 20:19 UTC, orangejenny commented on corehq/tabs/tabclasses.py
> +        if couch_user.is_superuser:
should this also check for contractor, to match the decorator?

2022-08-04 20:57 UTC, orangejenny commented on corehq/apps/reports/views.py
> +    @cls_require_superusers
Is there a reason for using this instead of `@method_decorator(require_superuser)`?

2022-08-05 14:29 UTC, orangejenny approved these changes

2022-08-08 21:27 UTC, esoergel approved these changes

2022-08-08 21:27 UTC, esoergel commented on corehq/apps/reports/views.py
> +    @method_decorator(require_superuser)
Not really part of this PR, but FWIW you can pass a `name` argument to `method_decorator` and stick it on the class, so you don't need to override a method just to decorate it:
```python
@method_decorator(require_superuser, name="dispatch")
class TableauServerView(BaseProjectReportSectionView):
    ...
```

2022-08-17 12:45 UTC, merged