Add privilege for accessing global sms gateway
dimagi/commcare-hq pull request #32049
Opened 2022-08-23 14:22 UTC by AmitPhulera

## Product Description

https://dimagi-dev.atlassian.net/browse/SAAS-13649
## Technical Summary

This is a followup of https://github.com/dimagi/commcare-hq/pull/31750 where we are restricting Global SMS Gateways page to the user who have `GLOBAL_SMS_GATEWAY`
## Feature Flag

## Safety Assurance
Has been tested on local and would be putting it on staging to test it.
### Safety story

### Automated test coverage

### QA Plan

NA

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

2022-08-24 14:49 UTC, biyeun requested changes
Hey @AmitPhulera looking good! I just added some comments to clarify the difference between using the privileges for plans vs superusers

2022-08-31 12:07 UTC, AmitPhulera commented on corehq/privileges.py
> +    GLOBAL_SMS_GATEWAY,
Done.

2022-08-31 12:08 UTC, AmitPhulera commented on corehq/privileges.py
> +GLOBAL_SMS_GATEWAY = 'global_sms_gateway'
Added at the end with the relevant comment. https://github.com/dimagi/commcare-hq/pull/32049/commits/87d2e30390c44940d47d940aab3bc8703a839730

2022-08-31 20:35 UTC, calellowitz approved these changes
Pending biyeuns approval (and minor language changes) looks good to me

2022-09-05 15:15 UTC, RynhardPietersen approved these changes
Looking good!

2022-09-05 16:03 UTC, biyeun approved these changes
🎉

2022-09-06 12:02 UTC, merged