GA show_owner_location_property_in_report_builder feature flag
dimagi/commcare-hq pull request #33132
Opened 2023-06-19 15:52 UTC by Charl1996

Creating this PR so long, but there's something I need to sort out locally.

## Product Description
GA show_owner_location_property_in_report_builder feature flag to Advanced Plan and higher.

## Technical Summary
[Ticket](https://dimagi-dev.atlassian.net/browse/SC-2866)

## Feature Flag
None

## Safety Assurance

### Automated test coverage
Tests included

### QA Plan
No formal QA planned.

### Migrations
- [ ] The migrations in this code can be safely applied first independently of the code

The migration depends on the code.

### Rollback instructions
Once this migration is applied, there's no turning back.

- [ ] This PR can be reverted after deploy with no further considerations

If this PR is reverted, we'd have to removing the created privilege. 

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

2023-06-20 07:13 UTC, SmittieC requested changes
Not sure if you missed it, but the `advanced_v0` in `features.py` file should also be updated

2023-06-20 08:02 UTC, Charl1996 commented on corehq/apps/userreports/tests/test_report_builder.py
> +    @patch('corehq.apps.userreports.reports.builder.forms.domain_has_privilege', return_value=True)
@privilege_enabled did not work here for me. Not sure why, but also not going to fix it in this PR.

2023-06-20 08:28 UTC, SmittieC approved these changes

2023-06-20 12:12 UTC, zandre-eng approved these changes

2023-06-20 12:22 UTC, merged

2023-06-20 13:20 UTC, calellowitz commented
What happens if someone selects this filter/field and their cases are not owned by locations, or owned by a mix of locations and something else (users or groups)?

2023-06-22 08:46 UTC, Charl1996 commented
@calellowitz
 
> What happens if someone selects this filter/field and their cases are not owned by locations

From my own testing I've noticed the following:
- Adding location owner as filter presents the user with the filter option to filter by location when viewing the report
- Having no cases owned by locations (only owned by web user) yields expected results when filtering by location, i.e. no cases shows up when applying location filter
- Having cases owned by a location yields expected results, i.e returns the cases owned by the location when applying the location filter

(I have an inkling this might not 100% answer your question, so feel free to tell me so) 

> or owned by a mix

What do you mean by being owned by a mix? Do you mean have some cases owned by users/groups and other cases owned by locations?