[B5] Migrate schedule demo modal to bootstrap 5
dimagi/commcare-hq pull request #33446
Opened 2023-09-06 21:11 UTC by biyeun

## Technical Summary
I noticed that the schedule demo modal was misbehaving on prelogin pages using a bootstrap 5 template. This fixes the Schedule a Demo modal so that it actually works now.

## Safety Assurance

### Safety story
Currently doesn't work on prelogin bootstrap 5 templates, so this fixes it. Additionally, there are not too many live pages that fall under this category (right now just the licensing pages)

### Automated test coverage
Yes

### QA Plan
Not needed

### Migrations

- [x] The migrations in this code can be safely applied first independently of the code

### Rollback instructions

- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

2023-09-11 20:03 UTC, mjriley approved these changes
Looks good, and I appreciate the small commits! It made digesting this much HTML much more approachable. I expect you've tested that the Bootstrap 5 modal looks and behaves like the previous version, however, because that much HTML was still difficult for me to reason about.

2023-09-11 20:04 UTC, mjriley requested changes
Amending my previous approval because I didn't see the failing test. Changes are approved once the tests pass

2023-09-13 19:39 UTC, biyeun commented on corehq/apps/analytics/static/analytix/js/hubspot.js
> +                $('#get-demo-cta-form-content').addClass('hidden').addClass('d-none');
yes, good idea. added

2023-09-13 19:44 UTC, biyeun commented
thanks @mjriley, had temporarily left this PR alone while trying to resolve the requirejs stuff from another PR. this should be good to go (i think the tests will be passing soon) :)

2023-09-18 16:25 UTC, mjriley approved these changes

2023-09-18 17:10 UTC, merged