Add config for lazy loading case lists
dimagi/commcare-hq pull request #33842
Opened 2023-12-05 17:54 UTC by MartinRiese

## Product Description

* Add config at module level
* Add attribute to details tag in suite.xml when flag is set

## Technical Summary

## Feature Flag

## Safety Assurance

### Safety story

### Automated test coverage

### QA Plan

### Migrations

- [ ] The migrations in this code can be safely applied first independently of the code

### Rollback instructions

- [ ] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [ ] Risk label is set correctly
- [ ] The set of people pinged as reviewers is appropriate for the level of risk of the change

2023-12-05 19:57 UTC, shubham1g5 commented
Noting that this is a Web Apps only feature, so we should somehow make sure that it's evident from the description. Probably change the description to add - "..... Web Apps only". Furthermore we should only display this - 

1. When Web Apps checkbox is checked in settings 
2. Only for case lists modules

2023-12-06 21:47 UTC, orangejenny approved these changes

2023-12-06 21:54 UTC, orangejenny requested changes
based on spec conversation I think this should be feature flagged

2023-12-06 23:42 UTC, Jtang-1 approved these changes

2023-12-06 23:53 UTC, closed without merging