Cap active banners to 3 on screen
dimagi/commcare-hq pull request #33855
Opened 2023-12-08 08:23 UTC by Charl1996

## Product Description
Currently any number of banners can be displayed (activated) on the screen in HQ. This PR restricts this to only 3. When at least 3 banners have been activated the other banners' Active action will be disabled.

## Technical Summary
[Ticket](https://dimagi-dev.atlassian.net/browse/SC-3233)
In addition to disabling the activation action on a banner on the UI, the banner update is also restricted in the backend to disallow more than 3 banners at a time.

## Feature Flag
CUSTOM_DOMAIN_BANNER_ALERTS

## Safety Assurance

### Safety story
Tested locally

### Automated test coverage
No automated testes included

### QA Plan
QA not necessary.

### Rollback instructions
- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

2023-12-08 12:06 UTC, SmittieC commented on corehq/apps/domain/static/domain/js/manage_alerts.js
> +        initialPageData.get('alerts').forEach(function (alert) {
This loop can be merged with the previous one

2023-12-08 12:06 UTC, SmittieC reviewed
Just one comment

2023-12-12 09:08 UTC, mkangia requested changes
Thanks for keeping this simple @Charl1996 

Can you highlight why there were changes needed to javascript? I believe the first commit is all that should have been needed.

2023-12-12 10:26 UTC, Charl1996 commented on corehq/apps/domain/views/settings.py
> +    if command == "activate" and len(Alert.get_active_alerts()) >= MAX_ACTIVE_ALERTS:
@mkangia Yes! Oh my!

2023-12-12 12:00 UTC, Charl1996 commented
Closing in favour of https://github.com/dimagi/commcare-hq/pull/33863

2023-12-12 12:00 UTC, closed without merging