Use default appearance for form controls
dimagi/commcare-hq pull request #34762
Opened 2024-06-12 16:01 UTC by orangejenny

## Product Description
This came up during web apps QA, but I'm creating a separate PR because it's a broader change.

B5 sets `appearance: none` on form inputs, which results in dropdowns no longer looking like dropdowns (see the language setting):
![Screenshot 2024-06-12 at 11 54 13 AM](https://github.com/dimagi/commcare-hq/assets/1486591/49617a0c-65a9-49e5-8b38-a81be5c3083d)

This PR restores the default appearance. Inputs will still look bootstrap-y, but they'll also have basic affordance:
![Screenshot 2024-06-12 at 11 53 02 AM](https://github.com/dimagi/commcare-hq/assets/1486591/8294f929-6987-4667-ad54-b069b216ad93)

Also see https://developer.mozilla.org/en-US/docs/Web/CSS/appearance

## Safety Assurance

### Safety story
No technical risk. Will have a subtle UI impact on B5 pages.

### Automated test coverage

no

### QA Plan

no

### Rollback instructions
- [x] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [x] Risk label is set correctly
- [x] The set of people pinged as reviewers is appropriate for the level of risk of the change

2024-06-12 17:20 UTC, millerdev approved these changes

2024-06-13 11:16 UTC, biyeun requested changes
@orangejenny by "dropdowns" do you mean select elements? Do the select elements in web apps have the appropriate bootstrap 5 styling applied? Because the selects in bootstrap 5 do have this styling but it requires the `form-select` class, not the `form-control` class

See https://getbootstrap.com/docs/5.3/forms/select/

2024-06-17 14:08 UTC, orangejenny commented
@biyeun Thank you for the info, I'm going to close this and make the `form-select` changes on the web apps B5 PR.

2024-06-17 14:08 UTC, closed without merging

2024-06-17 21:07 UTC, orangejenny commented
Ended up replacing with this commit: https://github.com/dimagi/commcare-hq/pull/34682/commits/290fe23a0a644eeffefcc003303c50be1a068492