Add UserAudit for user activation and deactivation
dimagi/commcare-hq pull request #35134
Opened 2024-09-17 20:03 UTC by jingcheng16

## Product Description

## Technical Summary

Ticket: https://dimagi.atlassian.net/browse/SAAS-15968

## Feature Flag

## Safety Assurance

### Safety story

### Automated test coverage

### QA Plan

### Migrations

- [ ] The migrations in this code can be safely applied first independently of the code

### Rollback instructions

- [ ] This PR can be reverted after deploy with no further considerations

### Labels & Review
- [ ] Risk label is set correctly
- [ ] The set of people pinged as reviewers is appropriate for the level of risk of the change

2024-09-17 23:39 UTC, orangejenny commented
> UserHistory report only shows record that are for current domain, I made the change so we can see record for current domain and for no specific domain

Just verifying, did you discuss this change with product? Visibility into information that isn't "owned" by the domain is a grey area.

2024-09-18 13:12 UTC, jingcheng16 commented
@orangejenny Hi Jenny, I haven't. I will ask in gtd-product.

2024-09-19 12:04 UTC, mkangia requested changes
> Just verifying, did you discuss this change with product? Visibility into information that isn't "owned" by the domain is a grey area.

Yup. The report should not show data not "owned" by the domain i.e data that is not relevant to the project.
You could show the web user's membership activated/deactivated only for that domain.

Definitely to be discussed with product before continuing with this.

2025-02-27 22:37 UTC, jingcheng16 commented
This PR is ready for re-reviewing. I have reverted the commits for changing UserHistoryReport. This PR now only have the first commit.

2025-03-03 18:54 UTC, millerdev approved these changes

2025-03-04 12:37 UTC, mkangia commented on corehq/apps/sso/backends.py
> +            log_user_change(by_domain=None, for_domain=None,
"No longer adding changes to UserHistory because it is controversial."

Is the PR description still true?

2025-03-04 12:41 UTC, mkangia commented on corehq/apps/sso/backends.py
> +                            changed_via=USER_CHANGE_VIA_REACTIVATION)
nit: The order to kwargs would be nice to retain as the calling function. I had added them in order of relevance which had a nice flow to it.

2025-03-04 12:43 UTC, mkangia commented on corehq/apps/sso/backends.py
> +            log_user_change(by_domain=None, for_domain=None,
I see that since we have the two domain kwargs None, this would not be visible anywhere for projects though a record would still be added to `UserHistory` model.

I got a bit confused by that statement in the description. I'd suggest framing it as something like

`The change is not visible to projects since its a change to the web user which is not owned by any project and the change does not impact the project's membership for the user`

2025-03-04 12:43 UTC, mkangia approved these changes

2025-03-04 13:49 UTC, jingcheng16 commented on corehq/apps/sso/backends.py
> +            log_user_change(by_domain=None, for_domain=None,
Sorry for the confusion. I guess by saying "No longer adding changes to UserHistory because it is controversial." I mean "User History Report" 😂 
Updated the description as you suggested!

2025-03-04 13:59 UTC, jingcheng16 commented on corehq/apps/sso/backends.py
> +                            changed_via=USER_CHANGE_VIA_REACTIVATION)
Thank you. 5bbeaf408b5e83f6cb01af0d61bdf9aa85b84f3b

2025-03-04 14:04 UTC, mkangia commented on corehq/apps/sso/backends.py
> +            log_user_change(by_domain=None, for_domain=None,
well "controversial" is a strong word.

Thanks!

2025-03-04 14:05 UTC, mkangia commented
Also, I am happy to re-approve is you want to get rid of the commits you reverted for a smaller PR.

2025-03-04 14:31 UTC, jingcheng16 commented
@mkangia Thanks! I don't plan to make a smaller PR. Can you reapprove this one since I make the commit to update the order of kwargs?

2025-03-04 14:32 UTC, jingcheng16 commented on corehq/apps/sso/backends.py
> +            log_user_change(by_domain=None, for_domain=None,
Haha I don't know that is a strong word. 😂 I'll be more cautious about word selection next time!

2025-03-04 18:35 UTC, millerdev approved these changes

2025-03-04 19:10 UTC, merged

2025-03-05 18:02 UTC, mkangia commented
apologies for the delay @jingcheng16 , I thought I approved it post the refactor but I missed.